org-roam/org-roam

- org-roam.el
If the org-roam buffer is already in org-mode, don't try to re-enable
it (since this essentially turns org-mode hooks into post-command-hooks
and can be computationally expensive).
> Don't re-enable org-mode

- org-roam-polyfill.el
- org-roam.el
make-empty-file was only introduced in Emacs 27, which some people are not yet running #17
> Add polyfill for make-empty-file

- README.md
- org-roam.el
org-roam-find-file can be used to quickly navigate to a file in Org-Roam.
> Add function org-roam-find-file

- org-roam.el
Similar to `org-roam-today`:
- `org-roam-tomorrow`: Add a file for tomorrow
- `org-roam-date`: Add a file for any date (choose via date picker)
> Add org-roam-tomorrow and org-roam-date

- org-roam.el
One of the conditions of `org-roam--maybe-update-buffer ` checks the true name of the current buffer. However, When populating `org-roam-files`, the true name is not used. This causes symlinks to not work, at least for me.
This PR adds the true file name to `org-roam-files` instead.
> Add or fix symlink support

- org-roam.el
2 changes:
1. Allows setting of the width of the org-roam buffer (as a percentage of frame-width), with `org-roam-buffer-width`
2. Propertize some the title, and preview contents. Depending on your theme, it might not look as nice. I recommend a theme with a background for `org-block`, or just setting that yourself.
> Small updates to org-roam buffer

- org-roam.el
Allow customizing of org-roam-insert title links and id links via `org-roam-link-title-format` and `org-roam-link-id-format` respectively.
> Add customizability for org-roam link insert formats

- org-roam.el
`org-roam-new-file` quickly creates a new file using the current timestamp. This is for #23 .
> Add org-roam-new-file

- org-roam.el
`(org-roam--find-all-files)` can take a really long time, and should be shifted to the async process. Thanks @l3kn for pointing it out. Should fix #46 .
> Move all expensive build-cache computation to async-process

- org-roam.el
Part of #49 . First order of business was to move the caches into their own variables. This made me discover that the `after-save-hook` was not local, so I fixed that as well.
> Refactoring the cache implementation

- org-roam.el
Fixing #54 . Like #55 , but without the double-checking in `org-roam--maybe-update-buffer`.
> Add checks before updating cache with org-roam--update-cache

- org-roam.el
Adds initial input for title-based links. Motivation: #53
> add org-roam--title-to-id

- doc/configuration.md
- doc/installation.md
- mkdocs.yml
- org-roam.el
This removes the `org-roam-link-representation` option, making the choice more automatic: If your Org files have titles, use the titles, else use the slug from the filename.
This also adds several customization options:
1. `org-roam-use-timestamp-as-filename`: Defaults to t. If t, uses the timestamp as file name. If false, the user will be prompted for a file name, generated from the title.
2. `org-roam-file-format`: This defaults to "%Y%m%d%H%M%S", a format string for the current time.
> Simplify org-roam-insert and org-roam-find-file

- doc/configuration.md
- org-roam.el
Add documentation for all of Org-roam's configuration options (#63 ).
> Add documentation for configuration options

- CHANGELOG.md
- org-roam-utils.el
org-roam--parse-content always computed the to-path relative to the `org-roam-directory`, when it should be relative to the file-path in question. Fixes #81.
> fix org-roam--parse-content incorrect :to computation

- CHANGELOG.md
- org-roam-utils.el
Seems to work both for building the initial cache as well as jumping to a note via a back link (password prompt is shown if password not cached).
Fixes #85
> Look for encrypted org-files (.org.gpg) in files and links

- org-roam.el
Fixes org-roam--maybe-enable not working with a symlinked directory. By the way, should all the file-truename calls be optimized somehow?
> Add a missed (file-truename org-roam-directory)

- CHANGELOG.md
- doc/configuration.md
- org-roam.el
If org-roam-encrypt-files is t, org-roam creates files with .org.gpg extension instead.
Might be a good idea to rename `org-roam--get-file-path` to `org-roam--make-new-file-path`, since given an existing ID it no longer reliably gets the path for it (could be either encrypted or unencrypted). I think it's only used for creating new files now anyways.
See #85
> Add support for file encryption by default

- CHANGELOG.md
- doc/configuration.md
- org-roam.el
The new function is controlled by variable `org-roam-file-name-function`.
This allows for more flexible naming of files. Now filename defaults
to yyyymmddhhmmss_title_here.org. Also, remove
`org-use-timestamp-as-filename`, and change it to
`org-roam-filename-noconfirm` to better describe what it is doing.
> (breaking): change org-roam-file-format to a function

- .gitignore
- org-roam-utils.el
- org-roam.el
- shell.nix
- tests/test-org-roam.el
Testing the basic combinations for `org-roam-insert`.
> (tests): add tests for org-roam-insert

- CHANGELOG.md
- org-roam.el
Add a custom org-mode link type that reuses the last window `org-roam` was called from to open files,
for use in the org-roam buffer.
Closes issue #30
@jethrokuan Should this go under "New Features" or "Internal" in the changelog?
> WIP: Add org_roam_file link type

- CHANGELOG.md
- org-roam-utils.el
- org-roam.el
This adds a link that goes directly to the line containing the backlink for each entry in the backlinks buffer. It does this by changing the the data structure in the backlinks cache that stores content from being a list of content strings to a list of cons pairs, where the `car` of the pair is the content string and the `cdr` of the pair is the line number where the content was found. This structure allows the backlinks buffer to link directly to the content lines in the linking file rather than just linking to the file as a whole.
> (feature) Add link to backlink line to backlinks buffer

- org-roam.el
`file-truename` can be an expensive function on a slow filesystem like NFS. I removed a lot of the unneeded code and refactored to improve performance. In my testing it took the execution time from `13ms` per call to `2µs`; over a 1000x speedup. This is important since `post-command-hook` is called with every character you type.
This change is a little more involved, so let me know what you think.
On a separate note, Another thing I noticed is that you code has a lot of `(buffer-file-name (current-buffer)` and `(file-truename (buffer-file-name (current-buffer)))`. Both of these values are cached in buffer local variables with `buffer-file-name` and `(expand-file-name buffer-file-truename)` respectively. It might be worth it it use the cached variables instead of calling the functions.
> Increase performance of post-command-hook

- org-roam.el
I am super excited to start using this package. It looks really well done. 
With this change it is no longer required to load org-roam before use. You can just add the `org-roam-mode` to `org-mode-hook` and it will load the package when needed.
> Add autoload to org-roam-mode

- org-roam.el
If you delete a org-roam buffer it can still trigger an update. Need to make sure that their exists a file for the buffer before we proceed.
> Check for buffer file in post-command-hook

- README.md
- doc/installation.md
As requested in issue #24, I added some instructions on how to install org-roam as a Spacemacs user.
> Add Spacemacs installation instructions

- org-roam.el
I ran into trouble evaluating source blocks in an org document having nothing to do with org-roam. This function was encountering an error whenever I evaluated the source block due to `nil` being passed to `file-truename`. We can detect that, and avoid the trouble.
> Handle nil file names

- org-roam.el
Implement a buffer-switching mechanism for only org-roam files.
For issue #126
> Add function org-roam-switch-to-buffer

- CHANGELOG.md
- org-roam.el
Adds a new variable `org-roam-new-file-directory` for new Org-roam files.
#140
> (feature): add a variable `org-roam-new-file-directory`

- CHANGELOG.md
- org-roam.el
- tests/test-org-roam.el
Maintains cache-consistency on file-deletes. Caveat: doesn't check if other files link to this file before deleting.
https://github.com/jethrokuan/org-roam/issues/119
> Add advice to delete-file

- CHANGELOG.md
- README.md
- doc/installation.md
- org-roam.el
- tests/test-org-roam.el
Makes org-roam-mode a global minor mode. This mode adds an advice to `find-file-function`, which decides whether to turn on the local post-command-hook and after-save-hook.
It also advices delete-file and rename-file to ensure cache consistency.
Ensures that Org-roam can be cleanly turned on and off. 
Also, fixes a bug introduced with the advice for #142 .
> (feature): global org-roam-mode

- org-roam.el
This pull request allows the customization of the appearance of exported graphviz nodes.
Two new customizable variables were introduced:
- `org-roam-graph-max-title-length` (default value: `100`)
- `org-roam-graph-node-shape` (default value: `ellipse`)
If the title length is longer than `org-roam-graph-max-title-length`, the title is shortened and `...` is concatenated to the end of the title.
`org-roam-graph-node-shape` is simply a string that is passed to the shape option of the node definition.
> allow customization of graphviz node appearance

- CHANGELOG.md
- org-roam.el
If your Emacs build has SVG support (most likely), you can view SVGs without using an external program.
> Fallback to Emacs SVG viewer functionality

- org-roam.el
After typing some text, it's easy to highlight part of the text and link it to another page.  Keeping the text the same is preferable to overwriting it with the title of the targeted page.  Uses the existing `competing-read` of the existing insert function and only changes the behavior when text is highlighted.
Addresses #127
> Insert with region keep text

- doc/configuration.md
- org-roam.el
This adds 'org-roam-link-face. When org-roam-mode is on, all roam
links take this face. By default, it is exactly the same as 'org-link,
and would require styling.
Addresses #161 .
Org-roam links can be styled differently from ordinary links. Here's how I style it:
```
(use-package ...
:custom-face
(org-roam-link ((t (:inherit org-link :foreground "#C991E1"))))
)
```
To give the pink links. I'm not sure if there's a sane default.
> (feature): add custom font styling for org-roam links

- org-roam.el
Currently duplicate space on the right side and missing padding on the left side:
> (bugfix): Use correct padding for modeline lighter

- org-roam.el
When converting a title to something acceptable as a file name, keep Unicode alphanumeric characters.
Ref #158
Example output:
```lisp
(mapcar #'org-roam--title-to-slug
'("!!!!Org-Roam is great!!!!"
"Sobre a formação dos planetas"
"1\\2.3///**"
"10-2+3=45"))
;; ("org_roam_is_great" "sobre_a_formação_dos_planetas" "1_2_3" "10_2_3_45")
```
> (bugfix): keep unicode alphanumerics in filename

- org-roam.el
ref #165
Without this change I am getting the error:
org-roam--make-new-file: Symbol’s function definition is void: file-name-fn
> (bugfix): fix new file template default case

- doc/configuration.md
One of the recent changes looks to have broken the docs on [this](https://org-roam.readthedocs.io/en/latest/configuration/) page by inserting one too many back-ticks in the closing part of the src block. This PR just removes one of the back-ticks.
> Fixed broken markdown src block

- org-roam-utils.el
- org-roam.el
- tests/roam-files-multi/mf1.org
- tests/roam-files-multi/mf2.org
- tests/roam-files-multi/mf3.org
- tests/roam-files-multi/multi-no-title.org
- tests/roam-files-multi/nested/mf1.org
- tests/roam-files-multi/nested/mf2.org
- tests/test-org-roam.el
ref #80 
I have multiple contexts that I use org-roam in. I would like to use org-roam concurrently with my various repositories of org files. At the same time, I want to keep them separate, as work files shouldn't link to my personal files and vice-versa.
This commit gives each org-roam-directory its own cache.  This was anyone that wants to have multiple org-roam directories can do so by configuring a `.dir-locals.el` for the extra repository.
Example .dir-locals.el file:
```lisp
((org-mode . ((eval . (setq-local org-roam-directory (expand-file-name "./"))))))
```
> Allow dir locals override dir

- org-roam.el
Opening the backlinks from doesn't work in the org-roam buffer, because of the modified `RET` behaviour. This fixes it.
> (feature): fix org-roam-open-at-point

- CHANGELOG.md
- org-roam-utils.el
- org-roam.el
- tests/roam-files/alias.org
- tests/test-org-roam.el
This adds support for title aliases, for a particular note via the `#+ROAM_ALIAS` key, e.g.:
```
#+ROAM_ALIAS: "alias 1" "alias 2" three four five
```
These aliases are valid in `org-roam-find-file` and `org-roam-insert`.
Addresses #91.
> (feature): support file aliases

- org-roam.el
- tests/test-org-roam.el
Prevent needless repeated calls to org-roam-directory-normalized by having a reference to the cache object that matches the local buffer.
May be better to avoid repeated calls of `file-truename` and `directory-file-name` and `equal` when the local buffer can keep a reference to its local repository cache object.
> (performance): avoid path expansion by referencing cache obj

- doc/anatomy.md
- mkdocs.yml
Documents the new Org-roam specific `#+ROAM_ALIAS` property.
> (docs): Add documentation for #+ROAM_ALIAS property

- README.md
- doc/installation.md
Some of org-roam's functions (e.g. org-roam-today and org-roam-find-file) should not need to have org loaded before use.
I'm not sure if this will fix it, since the `:hook` specification should cause the package to load. In any case, the Spacemacs installation instructions should be updated to bind the keys to the `org-roam-mode` minor mode, instead of the global org-mode.
#133 and #181 show people having issues with installation.
> (docs): remove `:after` from package install

- CHANGELOG.md
- doc/graph_setup.md
- org-roam-protocol.el
We emulate org-protocol, and advise server-find-files, stripping the
roam protocol from the filename. 
https://www.reddit.com/r/emacs/comments/f97twk/using_orgroam_on_windows_10/
This reduces the setup required to open `roam://` links, and shifts more of the handling into Org-roam. In future we may also extend the `roam://` protocol beyond file opening.
> (feature): emacs-lisp handling for `roam://` links

- doc/configuration.md
- org-roam.el
Older versions of Org don't support `org-link-set-parameters` well. We're seeing it fail on `9.1.9`, and it working fine on `9.3.6`.
Given that this functionality is not critical, we disable it for any Org versions less than `9.2`.
Closes #180
> (fix): Require a minimum version of Org 9.2 for roam link styling

- org-roam-utils.el
- org-roam.el
- tests/roam-files/web_ref.org
- tests/test-org-roam.el
This adds a cache for roam keys.
Each file has 1 roam key (string), specified by the the global `#+ROAM_KEY` attribute.
The key should point to a unique source of information: e.g.
1. `#+ROAM_KEY: https://google.com` notes for a website
2. `#+ROAM_KEY: cite:bibkey` notes for a bibliographic key
These keys will be used in future applications: e.g. having a firefox bookmark open up notes for a particular website.
> (feature): add a cache for roam keys

- org-roam.el
Pull request #178 regarding multiple org directories and following PRs use `alist-get` with the `equal` test function. Unless there is a good reason for association lists over hash tables, we could achieve the same effect with `gethash` and `puthash` to support emacs 25, since the `alist-get` with a test function argument was introduced in emacs 26.
> (fix) Change locals to use hash tables for emacs 25

- doc/roam_protocol.md
- mkdocs.yml
- org-roam-protocol.el
- org-roam-utils.el
- org-roam.el
- tests/test-org-roam.el
Rather than having our own protocol, we use org-protocol's underlying functionality and extend org-protocol instead.
We add 2 custom handlers:
1. `roam-file?file=path`: this simply opens the file at `path` in Emacs.
2. `roam-ref?ref=ref&template=roam-template&title=title&...`: attempts to open a roam note with a given `ROAM_KEY`. If the note doesn't exist, create one. Else, open it.
If you're curious, I uploaded a video of it on Twitter:
https://twitter.com/jethroksy/status/1233408971437821952?s=09
See #189
> (feature): deprecate roam-protocol, extend org-protocol instead

- org-roam.el
files with quotes used to break the graph export. This change escapes the strings.
Fixes #205 hopefully.
> (bugfix): escape file strings for graph export

- org-roam.el
`org-roam-build-cache` takes very little time, when the cache is already built running it on `org-roam-mode` ensures that the cache is consistent with the files.
> (fix): build org-roam cache on org-roam-mode

- org-roam.el
Adding a predicate for the delete-file advice ensures that expensive SQL operations do not run when not necessary.
> (bugfix): fix delete-file advice triggering on non-org-roam files

- org-roam.el
The graphname is displayed as tooltip when hovering over non-node
areas in the SVG viewer.
When grahname is undefined Chrome and Firefox just displays
"%3" (ETX/End of Text).
> (bugfix): use "org-roam" as graphname

- org-roam.el
`org-roam-capture` is meant to be called by other functions only.
https://github.com/jethrokuan/org-roam/issues/218#issuecomment-595007882
> (bugfix): remove interactive from org-roam-capture

- doc/roam_protocol.md
These extra settings for Platypus are required.
> (docs): add more org-protocol instructions for MacOS

- org-roam.el
Relative links in multidir contexts are being opened from the global `org-roam-directory` unless we update the `default-directory` for the backlinks buffer.
> (fix): relative links should work from org-roam-buffer with multidir

- org-roam.el
Unicode characters in filenames remain a pain for cross-platform work. I use my org-roam database under both Linux and macOS (on a dual-boot machine), and that creates trouble because Linux and macOS use different Unicode normalization conventions in filenames. So... it's easiest just to remove all nonspacing marks, which solves the problem for most European languages.
> Remove nonspacing marks (accents, umlauts, ...) from slugs

- org-roam.el
This lets the viewer application watch the file, or have the user manually refresh the view rather than, say, opening a new browser tab.
> org-roam-show-graph: PREFIX to generate a graph but not display it

- doc/org_export.md
- mkdocs.yml
Addresses #220 
Adding a basic version of @jdiez17's preprocessing advice to the appendix in the docs.
> (docs): add documentation for exporting backlinks in Org file

- org-roam.el
With org-capture integration, it does not seem to be used anymore.
> (chore): drop org-roam-filename-noconfirm

- CHANGELOG.md
- doc/configuration.md
- org-roam.el
I don't like org-block styling in backlinks buffer as it looks ugly
with my color scheme.
Add org-roam-backlink face for styling backlinks instead of using
org-block. It inherits from org-block, so that shouldn't affect the
default styling, but allows to override it without modifying
legitimate org-blocks.
> (feature): introduce org-roam-backlink face

- README.md
- doc/installation.md
Develop branch is going away. The develop branch was created so people who didn't want to keep up with the rapid pace of change could continue to use the unstable but unchanging master branch. 
Now that things have more or less stabilized, we're shifting back to `master` being the main branch, the default flow for MELPA.
> (chore): change main branch to master

- org-roam.el
Graceful shutdown is already guaranteed via `kill-emacs-hook`.
Refs #200
Prevents needless interaction on Emacs exit:
```
Active processes exist; kill them and exit anyway? (yes or no)
```
> (bugfix): Don't query about SQL proccess on Emacs exit

- CHANGELOG.md
- org-roam.el
> (feat): add optional initial-prompt to org-roam-find-file

- org-roam.el
Addresses #255
One may do something fancy like:
```
(defun my-format-fn (title)
"my format function"
"hi")
(setq org-roam-link-title-format #'my-format-fn)
```
> (feat): Allow function for org-roam-link-title-format

- org-roam.el
Not a fix to #262 , but a warning rather. `org-roam-insert` is meant to be called from an Org-roam file.
> (fix): Error if org-roam-insert is not called from Org-roam file

- org-roam.el
`buffer-file-name` uses the current-buffer if the argument is not passed
> (chore): cleanup buffer-file-name calls

- org-roam.el
Fixing an issue with #264, where `org-roam-insert` stops working for capture templates.
> (fix): allow org-roam-insert in Org-roam file indirect buffers

- org-roam.el
The line `(org-roam-sql [:delete :from files])` unnecessarily occurred twice in `org-roam--db-clear`.
> Remove duplicate line from `org-roam--db-clear'

- CHANGELOG.md
- org-roam.el
Add `org-roam-graphviz-extra-options` which allows passing of extra options during Graphviz graph generation.
Ref #263
> (feat): add org-roam-graphviz-extra-options

- doc/roam_protocol.md
fix typo in MacOS platypus installation.
> (docs):fix typo in platypus installation

- org-roam.el
Fixes rebuilding the database and creating the graph when `org-roam-directory` is overridden by .`dir-locals.el`.
> (bugfix): propagate org-roam-directory to temp buffers

- CHANGELOG.md
- doc/configuration.md
- org-roam.el
Currently implemented choices:
- `'default` for Emacs' `completing-read`
- `'helm` for Helm
> Customizable org-roam-completion-system

- CHANGELOG.md
- org-roam.el
Fixes #286 
Also adds `org-roam-fuzzy-match`, which for ivy and helm controls
whether completion candidates are fuzzy matched. 
cc @khinsen , fuzzy-match is off by default, you'll need to turn it on if you want.
> (feat): add 'ido and 'ivy support for completing-read

- CHANGELOG.md
- org-roam.el
This PR supercedes #280. It allows users who use the date
functionality in Org-roam to customize the filename and title formats
of the created files.
Closes #280 and closes #277
> (feat): add org-roam-date-title-format and org-roam-date-filename-format

- CHANGELOG.md
- org-roam.el
Addresses the main concern of #285. Uses a 1 time hook to run final actions after org-capture finishes.
> (bugfix): fix unintuitive behaviour of capture insertion

- CHANGELOG.md
- doc/configuration.md
- org-roam.el
Closes #295.
Now `org-roam-graph-exclude-matcher` takes a list of strings.
> (feat): upgrade `org-roam-graph-exclude-matcher` to accept a list

- org-roam.el
- `org-roam--capture-new-file` does not write anything to a file, all the
templating is delegated to vanilla `org-capture`.
- `org-roam--capture-get-point` injects the desired template adjustments and
behavior using `org-capture-put`
- `org-roam-capture-templates` variables work as before
- `org-capture-templates` wildcards work as intended except for "%?"
- depending functions adjusted accordingly
- new variable to `org-roam--capture-immediate-finish` to control the capture
process finishing unattended
1. The original org-roam behaviour as presented to the end user did not change.
2. The changes, however, have not been thoroughly tested, so some things may not work.
3. Point is not set as indicated by "%?" in a template, this must be fixed.
1. The main idea is to use the `:target` …
> Less abusive use of org-capture - proof of concept

- org-roam.el
Order backlinks by "file-from" file name, which seems preferable to the current non-sort. This would address (at least part of) #237.
> natural ordering of backlinks

- org-roam.el
#294 introduced a bug where header templates are injected on every capture call. This happens to be fine for `org-roam-find-file`, and `org-roam-insert`, but this breaks the capture system for references.
> (bugfix): capture: prepend header template only on new file

- org-roam.el
The org-roam graph would not link properly through org-protocol when using the Emacs Mac Port. This did address the issue. For your consideration, please.
> hexify file url for org-protocol link

- org-roam.el
Node labels on certain note titles are ugly. `'` gets escaped to `&apros;`
> (bugfix): fix ugly node labels in org-roam graph

- org-roam.el
- tests/test-org-roam.el
Addresses #310.
This introduces 2 user-facing changes:
1. If a capture process is aborted, the file is not created if it
doesn't yet exist
2. If a capture process is aborted, org-roam-insert will not insert a
link
> (feat): clean-ups for org-roam-capture system

- org-roam.el
When `org-roam-completion-system` is set to `ido`, the following errors occur:
* After `M-x org-roam-switch-to-buffer`:
> Error in post-command-hook (ido-exhibit): (wrong-type-argument sequencep #\<buffer filename.org>)
* When hitting tab after `M-x org-roam-find-file`:
> ido-file-lessp: Wrong type argument: listp, "/path/to/filename.org"
These errors occur because `ido-completing-read` can only deal with a list of strings. Suggested fix: Only pass the names.
> For `ido-completing-read', `choices' must be a list of strings.

- org-roam.el
cl is a deprecated library. cl-lib replaces it.
> Update cl.el functions to cl-lib versions

- org-roam.el
Removing hooks in a loop should be easier to extend/maintain.
More "DRY" than repeating calls to `remove-hook'.
> Remove hooks in a loop

- org-roam.el
- addresses #298
- fixes `org-capture-place-plain-text` throwing 'invalid search bound'
when both :unnarowed t and "%?" is missing from the template string
See #298
> ensure "%?" is present in the template string

- org-roam.el
This is to guard against scenarios where a db connection is still live, although it may already be invalid. Closes #331
> (internal): force a reconnect on org-roam-build-cache

- org-roam.el
This takes care of properly escaping backslashes in file names.
> Use org-link-make-string

- .github/FUNDING.yml
- .github/workflows/test.yml
Removes sponsor button, and disables 26.3 in testing matrix
> (chore): update internal Github settings

- doc/installation.md
This happened to me. The error message and backtrace information were not very clear
> Add warning: binding conflict with ranger layer

- org-roam.el
Previously the filename was not used in the capture template.
Fixes #347
> (bugfix): fix org-roam date functions filename format

- CHANGELOG.md
- org-roam.el
Fixes #342.
`org-roam-db-location` sets the location of the Org-roam sqlite database.
> (feature): add `org-roam-db-location`

- org-roam.el
`helm-build-sync-source` is in "helm-source.el". Hopefully this addresses #343 .
> (bugfix): change declare-function for `helm-build-sync-source`

- org-roam.el
This change makes `org-roam-open-at-point` non-interactive and adds it to
`org-open-at-point-functions`.  As a consequence, `org-open-at-point` will try
to visit an Org-roam link or preview text, before falling back to the default
behavior of Org mode.
In addition, `org-roam-backlinks-mode` is turned into a minor mode as discussed in #312.
There are some questions/remarks that came up during this change, I'll add them inline.
> Turn org-roam-backlinks-mode into a minor mode

- CHANGELOG.md
- org-roam.el
Adds `org-roam-verbose`, which echoes messages that are not errors.
Fixes #356 .
> (feat): add variable for muting messages

- company-org-roam.el
- org-roam-capture.el
- org-roam-completion.el
- org-roam-db.el
- org-roam-graph.el
- org-roam-macs.el
- org-roam-protocol.el
- org-roam.el
- tests/test-org-roam.el
Make distinction between org-roam features. Migrating each feature to its own file will separate development concerns and allow easier maintenance.
Addresses #357
> Modularize features

- org-roam-capture.el
This ensures custom templates don't break
> (fix): Add alias for 'org-roam--capture-get-point

- doc/templating.md
- org-roam-capture.el
- org-roam-protocol.el
- org-roam.el
Adds an interactive function `org-roam-capture`, which captures information into new or existing notes.
> (feat): Add interactive org-roam-capture

- org-roam-capture.el
This is a hotfix for #369. Currently, calling `org-roam-capture` sets
`org-roam-capture--in-process` to `t`, but cancelling the capture
process does not reset it to `nil`, causing false errors. The whole
nested org-capture processes workaround is brittle, this change moves it
as far back as possible, but the whole thing needs to be redesigned.
> (hotfix): move capture in-process setting as late as possible

- org-roam-completion.el
Addresses #343 .
Byte-compiled code should not contain macros.
> (fix?): use helm-make-source instead

- doc/installation.md
With the new `+roam` flag now added to doom emacs, this simplifies the instructions.
> simplifying doom installation instructions

- CHANGELOG.md
- org-roam.el
I like to have two files opened in my emacs side by side. Having a sidebar on the left or on the right messes that up, because I don't have enough horizontal space for 3 windows. So I wanted to be able to open it on the bottom instead.
Since there already was code that opened the sidebar on the side, it was trivial to modify to do it on top or on the bottom. I have manually tested that it works.
* Added `org-roam-buffer height`
* `org-roam-buffer-position` can now be either `top`, or `bottom`, or `left`, or `right`
> Allow top and bottom placement of the sidebar in addition to left and right

- CHANGELOG.md
- org-roam-graph.el
Fixes #382 .
`org-roam-graph-node-extra-config` is an alist containing additional node configuration options, as per
https://graphviz.gitlab.io/_pages/doc/info/attrs.html
This also deprecates org-roam-graph-node-shape, which is a special case
of the node options.
> (feat): Add org-roam-graph-node-extra-config

- org-roam.el
> (fix): undo font locking changes in backlinks buffer

- org-roam.el
Change function name org-roam--setup-buffer to org-roam--set-up-buffer.
Notify user and default to 'right when org-roam-buffer-position is
an invalid position.
Make better use of pcase to avoid repeating code.
> Refactor org-roam--setup-buffer

- org-roam.el
Also add prefix argument to `org-roam-yesterday`.
This makes it possible to jump back or forward several days.
I often plan several days in the future
> (feature): Add numeric prefix argument to `org-roam-tomorrow`

- doc/configuration.md
- doc/tour.md
Remove references to obsolete variable.
org-roam-build-cache -> org-roam-db-build-cache
See: #394
> (docs): org-roam-db-build-cache

- org-roam-capture.el
- org-roam-compat.el
- org-roam-db.el
- org-roam-graph.el
- org-roam.el
Same strategy Org uses. Consolidates backward compatibility into a
single location.
> (internal): Move aliases to org-roam-compat.el

- org-roam.el
Adds support for all org-ref recognized cite links
> (fix): Detect all org-ref cite types

- org-roam-buffer.el
- org-roam-db.el
- org-roam.el
Split functionality related to the org-roam-buffer into its own
feature/file.
Introduce `org-roam-buffer-prepare-hook' to allow customizations of the
org-roam-buffer content.
Related issues: #346 #323 #245 #219 #198 #95 #14
> Modularize org-roam-buffer

- org-roam-capture.el
- org-roam.el
Instead of using a global variable to check for a existing capture,
leverage the :org-roam plist property of the buffer-local variable
`org-roam-capture-current-plist`.
This prevents a lockout if the capture buffer is killed.
When killing the capture buffer instead of using <kbd>C-c C-k</kbd> I can't start new capture processes:
```
user-error: Nested Org-roam capture processes not supported
```
> (bugfix): Use predicate to check for a `org-roam-capture` process

- org-roam-buffer.el
- org-roam.el
While navigating links and back-links I'll end up with several buffers
open due to auto-splitting. When I `delete-other-windows` the org-roam
window will also close. With this option set to `t` it will keep the
org-roam window around even when closing other windows.
> Add customization to set no-delete-other-windows

- org-roam-db.el
Ensure the `when-let` macro definitions is available during
compile-time.
I encountered this issue today:
```
Debugger entered--Lisp error: (void-function links)
links((["/home/juergen/shared/org/roam/2020-04-10.org"   org-roam-db-build-cache()
....
org-roam-mode()
run-hooks(after-init-hook delayed-warnings-hook)
command-line()
normal-top-level()
```
Because the macro `when-let` macro was not available at compile time:
```
org-roam-db.el:325:32:Warning: reference to free variable ‘links’
org-roam-db.el:329:44:Warning: reference to free variable ‘ref’
```
Note: The problem might not occur in all environments because the `subr-x` macro definition might been preloaded by other packages.
> (bugfix): Explicitly load subr-x library

- org-roam.el
Hello,
This is a very small PR to implement `org-roam-find-directory`.  I was surprised to see that it didn't exist.  I often find myself going to the directory, both for managing names and testing stuff for development.
HTH.
> (feat) Add org-roam-find-directory

- org-roam-db.el
Prevents unnecessary evaluation when compiled .elc is loaded.
From the commentary of subr-x.el:
;; NB If you want to use this library, it's almost always correct to use:
;; (eval-when-compile (require 'subr-x))
See: #429
> (refactor): org-roam-db.el eval-when-compile subr-x

- org-roam.el
Spotted a little area where we could reuse a variable we computed in a wrapping `let`-form.
> (tiny-fix) reuse variable defined in let-form

- org-roam-db.el
- org-roam-graph.el
As a follow-up to #398 I wanted to investigate whether it's feasible to only traverse the link graph up to a given distance. This is helpful to get a quick (local) overview once the number of connections grow. (Because if all your notes are connected in one way or another, #398 is not going to help…)
To give you an idea, here is the entry on the "Kalman Filter" from https://github.com/jethrokuan/braindump with a maximum distance of one in the first image and two in the second image.
**M-1 M-x org-roam-graph-show-connected-component RET**
**M-2 M-x org-roam-graph-show-connected-component RET**
> Allow to limit the number of jumps when creating graph

- org-roam.el
> (fix) typo in doc, titles -> refs

- org-roam-buffer.el
- org-roam-compat.el
> (refactor): Move obsolete vars/functions to org-roam-compat

- CHANGELOG.md
- org-roam-graph.el
I want to change direction of edges, so a note points to notes it
references.
Introduce `org-roam-graph-edge-extra-config` in the spirit of
`org-roam-graph-node-extra-config`, so I can add `dir=back`.
Also, refactor so default node/edge properties are specified once.
> (feat): add org-roam-graph-edge-extra-config

- org-roam-graph.el
As discussed in #418 it's useful to free up the prefix of `org-graph-show-*` for other uses. To still allow only building the graph without displaying it, this part is split into a separate function in this PR.
> Split building and showing of the graph into two functions

- doc/installation.md
(#397): Add a subsection specific to Windows in the Installation section of official documentation
> (doc) add Windows installation instruction (#397)

- CHANGELOG.md
- org-roam-db.el
- org-roam-graph.el
Now that citations appear as backlinks in the backlinks buffer, it makes sense for them to also show
up in the graph.
I'm quite a novice as SQL, so this query probably could have been merged into the previous, but this
works for now.
Citation links appear in the backlinks buffer, so they should probably appear in the graph view
> Add edges in graph relating to org-ref cite links

- doc/installation.md
Thank you for accepting my earlier PR: #438. 
The format didn't turn out to be as intended. Here is my attempt to fix that, along with minor grammar and typo issues.
I don't have access MKDocs, so I was not able to ensure the format in the official documentation would be correct. This time, I was more careful and tried previewing the change in GitHub itself -- hopefully this is good enough to check the format in the final MKDocs format... I am noting GFM might be different from Python-Markdown that MKDocs uses.
> (doc) fix broken format+typo in win-install (#438)

- org-roam-graph.el
Create a new temporary file for each graph that is built.
See: #453
> (fix): Use make-temp-file in org-roam-graph-build

- doc/installation.md
The second fix made the format worse, in my eye. 
Jethro, all contributors, I do apologies for doing it so many times -- thank you for your patience. 
This time, I checked the output with Python-Markdown. It does output different HTML from that I see in MKDocs... But I have a reason to believe this will be fine (`<pre>` vs `<code>` , which worked in the previous attempts). Hopefully it should be good enough a test for fix.
>  (doc) fix broken format in win-install doc (#438)

- doc/org_export.md
`org-roam-sql` is obsolete now. Also changed the syntax that works for the new `org-roam-db-query` function.
> (docs) Correct database query function

- doc/installation.md
Now that org-roam is out on MELPA, let's suggest that people use it
instead of GitHub to install the package.
> Use MELPA for installing in Spacemacs

- CHANGELOG.md
- org-roam.el
Adds `org-roam-file-extensions`, which allows org-roam to detect file
extensions other than .org. Fixes #461
> (feat): Add support for different file extensions

- CHANGELOG.md
I had initially thought that keeping them separate would be cleaner, but
it's very easy to forget to add the links at the bottom of the
changelog. Relevant emacs-lisp that did this:
```
(replace-regexp "\\[gh-\\([0-9]+\\)\\]" "(https://github.com/jethrokuan/org-roam/pull/\\1)")
```
> (chore): inline links in changelog

- org-roam.el
This prevents and error being generated when the agenda is displayed.
Fixes #408
Agenda can't be displayed when using `~` in `org-roam-directory`.
This error was really hard to tackle down because match data is only modified when using tilde (expansion):
```
(progn
;; evals to 0 instead of 1
(progn
(string-match "b" "ab")
(file-truename "~/")
(match-beginning 0))
```
> (bugfix): add workaround for undocumented `file-truename` behavior

- doc/ecosystem.md
- doc/installation.md
- org-roam-capture.el
- org-roam-compat.el
- org-roam-dailies.el
- org-roam.el
This moves all the daily notes functionality into `org-roam-dailies.el`.
Beyond just an extraction, this is also a simplification. It removes two
variables: `org-roam-date-filename-format` and
`org-roam-date-title-format`, in favour of directly specifying them in
the `org-roam-dailies-capture-templates`.
`org-roam--file-for-time` is also vastly simplified to use org-capture's
default time expansion utilities, by setting the capture template's
`:default-time` appropriately.
Fixes #468
> (internal): extract daily notes functionality

- doc/org_export.md
It would be nice to have a complete `org-modes` like functionality in exports. This extra code snippet (slightly modified from [org-roam-buffer-insert-backlinks](https://github.com/jethrokuan/org-roam/blob/772505ba70c073ebc7905c4fcb8b9cc3759c775a/org-roam-buffer.el#L130)) provides that.
> Add option for exporting backlinks with contents.

- org-roam-capture.el
Trying to create a note with `org-roam-find-file` inside a sub-directory that does not exist results in a silent failure.
This PR fixes it by ensuring the existence of the sub-directory (and its parents).
> (fix) ensure that directory exists before capturing to dir

- org-roam.el
Motivation is described in #474.
Implements:
- Optional `FILTER` argument for `org-roam-find-file` and `org-roam-insert`
- `org-roam--get-non-ref-path-completions` to only get non-ref notes
- `org-roam-find-non-ref-file` & `org-roam-insert-non-ref` as convenience commands
Closes #474.
> Optional `FILTER` argument for `org-roam-find-file` and `org-roam-insert`

- org-roam.el
Fixes #487
#487 
IMO, this is especially useful because the file name is automatically generated in org roam.
> (feat): Use TITLE as description when linking before first heading

- doc/installation.md
- org-roam-compat.el
- org-roam-graph.el
- Consolidate graph build/display commands into org-roam-graph command
See #450
- Require org-roam-db
Rather than declaring its functions.
- Move obsolete variable org-roam-graph-node-shape to org-roam-compat
- org-roam-graph--build-connected-component accepts a file argument
Allows building a graph without having the target file as the current
buffer
- Eliminate repeating code
- Fix checkdoc warnings
> (refactor): org-roam-graph

- org-roam-graph.el
User may specify a function to open the org-roam graph.
Adds more error handling to org-roam-graph--open.
See #440
> Allow function for org-roam-graph-viewer

- org-roam-graph.el
> (fix): Remove old definition of org-roam-graph--open

- org-roam.el
Use destructive elisp functions to optimize for speed and memory
usage.
Refs #104
slight speedup:
Original:
```
ELISP> (benchmark 1000 '(org-roam--list-files org-roam-directory))
"Elapsed time: 29.403994s (6.193575s in 122 GCs)"
```
Commit:
```
ELISP> (benchmark 1000 '(org-roam--list-files org-roam-directory))
"Elapsed time: 27.186161s (5.973992s in 117 GCs)"
```
> (internal): Simplify `org-roam--list-files` implementation.

- doc/ecosystem.md
Mention @Zaeph 's [org-roam-bibtex](https://github.com/Zaeph/org-roam-bibtex) in the documentation.
> (docs): mention org-roam-bibtex

- doc/roam_protocol.md
JS Bookmarklet for org-roam-protocol was missing extra `/` in documentation.
> (docs): Fix org-roam-protocol JS Bookmarklet

- doc/ecosystem.md
I’ve recently changed my nickname on GitHub from ‘Zaeph’ to ‘zaeph’.  GitHub normally redirects properly, but it can cause issues in some instances.
> (fix) lowercase username in url to org-roam-bibtex

- CHANGELOG.md
- org-roam-db.el
- org-roam.el
In #470, the `and` clause was removed, so `org-roam--org-roam-file-p`
returns `t` on `foo.org~` backup files. This PR adds that back in.
In addition, the `after-save-hook` function was not checking for whether
the file was within the org-roam system, which meant files from outside
`org-roam` would also be added into the database. This PR adds a guard
clause.
> (bugfix): fix inserting backup files into database

- org-roam-graph.el
The error handler was never invoked when executing
`org-roam-graph-viewer` failed
No signal when executing `org-roam-graph-viewer` failed.
BTW: It would be nice to make byte compile errors fatal in the CI jobs. The above error was also revealed when byte-compiling:
```
In toplevel form:
org-roam-graph.el:212:1:Warning: Unused lexical variable ‘err’
```
> (bugfix): Fix invalid usage of error handler

- doc/configuration.md
This fixes a reference to the Roam Protocol documentation that was missed when it was renamed from Graph Setup.
> (docs) Update reference to Roam Protocol documentation.

- org-roam-buffer.el
Prompted by #520.
I've noticed that we didn't have a switch between singular and plural for the titles in `org-roam-buffer`:
So, I went ahead and implemented it.
Note that I've also done it for cite backlinks.
> (feat) conditionally pluralize heading in org-roam-buffer

- CHANGELOG.md
- org-roam-completion.el
Remove the fuzzy matching variable introduced in #289. The rationale is
addressed in
https://github.com/jethrokuan/org-roam/issues/514#issuecomment-619438401:
Helm, Ido and Ivy have their own mechanisms for fuzzy search, and can be
tweaked using their own configuration options outside of org-roam, e.g.
through `ivy-re-builders-alist`.
cc @hlissner
> (chore): remove org-roam-completion-fuzzy-match

- CHANGELOG.md
- org-roam-graph.el
Always quote graphviz configuration options. This allows passing
configurations with spaces. Fixes #535.
> (bugfix): quote graphviz configuration options

- doc/configuration.md
- org-roam.el
Implement a new command `org-roam-find-index` and helper function `org-roam--find-index` (note the `--` for internal) for finding an index file in `org-roam-directory`.
The resources I've read on the slip-box indicated that one should maintain an index file to lead you to your topic-notes.  From Ahrens (2017):
> After adding a note to the slip-box, **we need to make sure it can be found again**. This is what the index is for.
[…]
The organisation of the notes is in the network of references in the slip-box, so all we need from the index are entry points. A few wisely chosen notes are sufficient for each entry point. **The quicker we get from the index to the concrete notes, the quicker we move our attention from mentally preconceived ideas towards the fact-rich level of interconnected …
> (feat) implement org-roam-find-index

- CHANGELOG.md
- org-roam.el
Optionally pulls title from the first headline in Org file. Closes #506.
> (feat): optionally use headline as title

- org-roam.el
Fixes #517.
-----
Here's a prototype to address #517 (and help with #516).
The links created by `org-roam-insert` are relative.  This is well an good until we need to handle those relative links in `org-roam-buffer`.  The problem is `org-roam-buffer` is buffer-agnostic, and therefore file-path-agnostic as well.  Since we do not have the root from which to compute the relativity, we cannot reliably get the absolute path of a backlink.
#516 attempted to resolve the issue by exploiting the fact that `org-roam-buffer--insert-backlinks` inserted those backlinks under a heading which contained the absolute path to the file in which those backlinks were found.  It worked, yes, but it was hackish.  Also, it only covered an effect of the problem rather than its cause.
#517 then came along with its …
> (feat) expand rel-links upon extraction

- doc/configuration.md
- doc/installation.md
- org-roam-compat.el
- org-roam.el
I've forgotten to add the new command for finding the index in the default key-bindings.  This will further help the discoverability of the command.
I'm not sure about the key used for the key-binding, though.  I opted for `j` because it's easy to access, and you can kind of remember it like `jump to index`.  If we bring this idea to its logical conclusion, we might want to rename the command to `org-roam-jump-to-index`.
> (doc): Add key-binding for index in default configs

- CHANGELOG.md
- org-roam.el
org-ref multi-citations are handled by "cite:key1,key2". In the org-roam databases this was
previously stored as a single "cite" link to the (non-existing) key "key1,key2". This means that
cite backlinks and cite graph behaviour does not work correctly for these links.
This fix will split any cite links with a comma into separate links to each individual ref.
To be honest, I don't really  like how this patch changes the readability of `org-roam--extract-links`. Because I've basically wrapped the existing code in a `mapccan`, the code to split the multicite links now appears before the code to actually extract the links; in my mind these should be the other way around. In addition, properly indenting would cause a gross diff (I've currently left the original indentation). Not sure how to …
> Ensure that multicite links are correctly split

- org-roam-graph.el
Add an option to wrap the title in the graphviz graph instead of truncating it.
The value of `org-roam-graph-max-title-length` will be used for wrapping
Things will look nicer and no information is lost!
> graph: add an option of wrapping the title

- org-roam-buffer.el
Generate cite backlinks correctly when the `ROAM_KEY` is a cite-type other than `cite`
This fix would fail on pathological cases where the key itself contains other prefixes e.g. if the key
is `cite:parencite:autocite:key`. Although this is unlikely... Any quick and easy way to only chop the first prefix found? Or is this acceptable?
To use org-ref-cite-types, we must ensure that org-ref is loaded. This would likely already be done
otherwise as the user is obviously using cite links.
Lots of discussion in https://github.com/jethrokuan/org-roam/issues/540 https://github.com/jethrokuan/org-roam/pull/547 https://github.com/zaeph/org-roam-bibtex/pull/22 https://github.com/zaeph/org-roam-bibtex/pull/21
> Generate cite backlinks using all org ref cite types

- .gitignore
- Makefile
- default.mk
- doc/AUTHORS.md
- doc/Makefile
- doc/htmlxref.cnf
- doc/org-roam.org
- doc/org-roam.texi
This is partly motivated by #526 . We use Makefiles inspired by Magit and use-package, writing our manuals in Org, to be converted into pdf, html, texi, info and epub.
> (internal): use Make and Org to build manual

- CHANGELOG.md
- org-roam-db.el
Addresses https://github.com/jethrokuan/org-roam/pull/547#issuecomment-623080000
Running `C-u M-x org-roam-db-build-cache` will rebuild the database from scratch.
> (feat): add prefix argument to force database rebuild

- org-roam-graph.el
Allow showing/building the whole graph from any buffer.
Allow programatically specifying connected component path.
> (ehancement): Improve org-roam-graph

- .github/workflows/test.yml
- doc/org-roam.org
- doc/org-roam.texi
- doc/templating.md
- makem.sh
- org-roam-buffer.el
- org-roam-capture.el
- org-roam-compat.el
- org-roam-dailies.el
- org-roam-db.el
- org-roam-protocol.el
- org-roam.el
Lint errors such as compile errors now often slip past, since they don't cause the CI to fail.
> (internal): make lint errors fail CI, and disable spellcheck during linting

- org-roam.el
A better default for org-roam-link-current is the original org-link
face, rather than org-block.
> (chore): inherit org-roam-link-current from org-link

- org-roam.el
Follow-up to #563.
There's a small oddity going on with the syntax-highlighting of `error` in `emacs-lisp-mode` which formats it as the `symbol-function`, but I think this is just cosmetics:
https://github.com/jethrokuan/org-roam/blob/9ae2984bc7ebaf4c19db78618558c7e28c609ac8/org-roam.el#L675
> (feat): add custom face for links without destinations

- org-roam.el
The format of the `INFO` argument of `org-roam-find` has been simplified, thanks
to the split of `type` and `ref` in the db permitted by #547.
The non-interactive behaviour of `org-roam-find-ref` has also been isolated
into `org-roam--find-ref`.  Even if it makes us repeat ourselves a bit, it
avoids having to nil the interactive argument just to get the non-interactive
us, which I think is better syntax.
Fixes #565.
> (feat): simplify format of `INFO` for find-ref and add `FILTER`

- README.md
Can’t believe nobody told us that we used ‘screenshot’ instead of
‘screencast’. :(
> (doc): Improve wording 'A Preview'

- org-roam-capture.el
- org-roam-dailies.el
- org-roam-macs.el
- org-roam-protocol.el
- org-roam.el
Fixes #583.
@progfolio Do you think the pase is warranted, here?  Ever since you've shown me how to use `pred`, I want to use it all the time, even when its use isn't warranted.  But here, it allows to check `(str str)` quite nicely:
https://github.com/jethrokuan/org-roam/blob/cb448b6a325eb7c19574cf0e06d166bc6b1fe630/org-roam-capture.el#L288-L289
> (fix): allow group templates in capture-templates

- CHANGELOG.md
- doc/org-roam.org
- org-roam-doctor.el
- org-roam.el
This library provides `org-roam-doctor`, a utility for diagnosing and fixing
Org-roam files. Running `org-roam-doctor` launches a list of checks defined
by `org-roam-doctor--checkers`. Every checker is an instance of
`org-roam-doctor-checker`.
Each checker is given the Org parse tree (AST), and is expected to return a
list of errors. The checker can also provide "actions" for auto-fixing errors
(see `org-roam-doctor--remove-link' for an example).
The UX experience is inspired by both org-lint and checkdoc, and their code
is heavily referenced.
Closes #222
> (feat): org-roam-doctor: fix broken links

- org-roam-db.el
- org-roam-doctor.el
- org-roam-macs.el
- org-roam-protocol.el
This macro simplifies message printing, so we can respect
`org-roam-verbose` in more places. Also silences more messages when
`org-roam-verbose` set to false.
> (internal): add `org-roam-message`

- org-roam-macs.el
Add to commentary that org-roam-macs may contain other utility
functions (similar to org-macs).
Unless we need to use a macro, we should not.
> "Refactor org-roam-message as a function"

- org-roam.el
> (fix): enforce default for ‘org-roam-index-file’

- org-roam.el
> (fix): Respect `org-roam-file-extensions` during file creation

- .dir-locals.el
- org-roam-buffer.el
- org-roam-capture.el
- org-roam-compat.el
- org-roam-completion.el
- org-roam-dailies.el
- org-roam-db.el
- org-roam-dev.el
- org-roam-graph.el
- org-roam-macs.el
- org-roam-protocol.el
- org-roam.el
Sorry! Missed this refactor before the merge.
I forgot Emacs has directory local variables.
Using this prevents us from having to add it to file-local variable line of each file.
> Refactor org-roam-dev to utilize dir-local variable

- org-roam-db.el
Programatically pull tables from schemata, rather than manually
specifying.
> (refactor): org-roam-db--clear-file pull tables from schemata

- org-roam-db.el
Programatically pull tables from schemata, rather than manually
specifying each table.
> (refactor): org-roam-db--clear pull tables from schemata

- README.md
- org-roam.el
In an effort to consolidate efforts on documentation, we have moved all the documentation into an Org file, to allow for the generation of Info pages in Emacs, as well as the generation of a HTML manual.
This is perhaps a step backward from the previous, arguably more consumable, online documentation, but I hope that this makes it easier to access and contribute to the documentation within Emacs.
> (docs): update manual location

- org-roam-doctor.el
The checker originally returns reports of wrong format when there are no
errors
> (fix): fix org-roam-doctor broken-link checker

- doc/org-roam.org
- org-roam.el
- tests/roam-files/no-title.org
- tests/roam-files/titles/aliases.org
- tests/roam-files/titles/combination.org
- tests/roam-files/titles/headline.org
- tests/roam-files/titles/title.org
- tests/test-org-roam.el
Introduces `org-roam-title-sources,` which can be a list of lists,
infinitely deep. Each symbol corresponds to a function, that when called
returns a list of titles. If the element is a list, use the first
function in the list that returns a successful result.
> (refactor): refactor title extraction

- doc/org-roam.org
- doc/org-roam.texi
It appears the option has changed name, but this was not yet reflected
in the documentation.
>  (docs): Fix org-roam-buffer-no-delete-other-windows

- org-roam-dev.el
> (internal): org-roam-dev -> sentence-end-double-space nil

- doc/org-roam.org
- doc/org-roam.texi
- org-roam-capture.el
- org-roam-db.el
- org-roam.el
- tests/roam-files/base.org
- tests/roam-files/nested/deeply/deeply_nested_file.org
- tests/roam-files/tags/no_tag.org
- tests/roam-files/tags/tag.org
- tests/test-org-roam.el
Adds a tagging system to Org-roam. Addresses #572.
Tags are obtained in 2 ways:
1. Via sub-directories: "a/b/c/foo.org" will have tags `a, b, c`
2. Via `#+ROAM_TAG`: `#+ROAM_TAG: foo bar` will assign tags `foo bar`
These 2 means are freely combined.
@zaeph this PR removes your stuff on directory specific filtering, in favour of assigning tags based on directories, functionally they are equivalent, but this is more general.
> (feat): Add a tagging system

- org-roam.el
Yet another spot where we've forgotten to change to a hash-table.
> (fix): move from alist to hash for find-ref

- org-roam.el
Needed for smoother interaction with ORB.  I’ve elected to keep FILTER-FN for
the moment, even though it’s a bit redundant, and the description in the
docstring is not correct with the addition of tags.
> (feat): add COMPLETIONS argument to insert and find-file

- org-roam.el
Fixes #631.
I've preserved the conditional behaviour with `org-roam-include-type-in-ref-path-completions`.
> (fix): refactor get-ref-path-completions

- org-roam-capture.el
- org-roam.el
Initially we thought that using hash-tables would shave some seconds
because searching for a key is O(1), but when we present completions, we
typically want them sorted, and hash-tables do not support sorted keys.
> (internal): revert completions from hash table to alist

- org-roam-db.el
- org-roam.el
Broken by the switch from alist to hash-tables #604, although it was probably janky before as well.
> (fix): reimplement mtime sorting

- org-roam-completion.el
This reverts commit 47763f49fde56579658ed8b8ee33a52d38674515, after #643
reverted completions from hash-table to alist.
> (fix): fix parsing for ido

- org-roam.el
Spotted in org-roam/org-roam-bibtex/pull/48.
> (fix): adapt find-ref to new format

- org-roam.el
define-minor-mode macro creates appropriate symbol/documentation for
inlined keymaps.
> (internal): inline minor-mode keymaps

- org-roam.el
Useful for diagnostic information.
Should be supplemented with finer grained info (commit hash would be
ideal) once we figure out a more sophisticated approach.
> (feature): org-roam-version command

- .github/ISSUE_TEMPLATE/bug_report.md
- org-roam.el
Automates collection of user environment information.
An idea I had to help users provide us with useful debugging information.
Right now it just grabs `emacs-version`, the full `org-version` and prompts whether or not they are using a framework like Doom or Spacemacs. 
We might be able to grab org-roam git hash programatically as well, but I left that out for now.
Could easily be expanded to include more info  if needed.
Good idea?
> (feature): org-roam-diagnostics command

- org-roam.el
seq.el is is not guaranteed to be loaded otherwise.
> (fix): Require seq.el

- org-roam.el
Define org-roam-backlinks-mode before it is referenced.
> (internal): fix free variable reference

- org-roam.el
Instead of visiting file, insert library into temp buffer.
Prevents loading .dir-local dev environment, accompanying unsafe-variable prompt.
Prevents interference with org-roam.el if already open.
> (fix): prevent org-roam-version from loading org-roam-dev

- org-roam-capture.el
Set title correctly when no match found in prompt's candidates.
fixes #651
> (fix): org-roam-capture allow creating new file

- org-roam-capture.el
Lexically bind org-capture-templates-contexts to nil before calling org-capture
with org-roam-capture-templates. Otherwise, contexts may shadow
org-roam-templates which have same keys as org-capture-templates.
mentioned in #651
> (fix): org-roam-capture--capture shadow org-capture-templates-contexts

- doc/org-roam.org
This should point to the official repo, not a fork (right?)
> Update org-roam-bibtex link in docs

- org-roam-graph.el
org-roam-graph--build accepts a callback function which is passed the
resultant graph file as its sole argument. This prevents a race between
graph building and opening.
See: #666
> (fix): org-roam-graph--build in seperate process

- org-roam-graph.el
Displays a message to user to let them know the build (which may take
a variable amount of time) has started.
#666
> (fix): org-roam-graph--build notify user when build starts

- org-roam.el
Filenames that contain special characters like spaces are not handled correctly. This fixes it.
> hotfix org-roam--list-files

- org-roam.el
Prevent shell commands from passing ANSI color codes through to callers.
see: #688
> (fix): org-roam--list-files strip ANSI color codes

- org-roam.el
The new 'find and 'rg methods for obtaining the list of org-roam files aren't working well for Windows, so for Windows users, we fall-back to the elisp implementation.
> (fix): set default org-roam-list-files-commands for windows to nil

- org-roam.el
The implementations for org-roam--list-files-{find,rg} did not follow
symlinks, which cause them to not pick up symlinked files and
directories.
> (fix): fix symlinked directories and files not picked up

- CHANGELOG.md
- doc/org-roam.org
- doc/org-roam.texi
- org-roam-buffer.el
- org-roam-capture.el
- org-roam-compat.el
- org-roam-completion.el
- org-roam-dailies.el
- org-roam-db.el
- org-roam-dev.el
- org-roam-doctor.el
- org-roam-graph.el
- org-roam-macs.el
- org-roam.el
Emacsql-sqlite3 seems to work better for Windows, and has no effect for Linux users.
This is to address #682 .
> (internal): use emacsql-sqlite3 everywhere

- org-roam-db.el
If a shell command is used to find files, it may include
output from another command.
see: #706, #688
> (fix): org-roam-db-build-cache filter non-file input

- org-roam-buffer.el
- org-roam-capture.el
- org-roam-dailies.el
- org-roam-doctor.el
- org-roam-graph.el
- org-roam.el
Users should not have to explicitly enable the minor mode before using
autoloaded commands.
see #446,  #116 and I'm sure others.
I have hit this issue myself on occasion.
> (fix): autoloaded commands load org-roam-mode

- .github/workflows/test.yml
org-roam-compat.el may contain symbols that belong to other packages.
e.g. functions backported to older versions of Org mode.
see #711
> (internal): Exclude org-roam-compat.el from linting

- org-roam-compat.el
`org-link-make-string` is not defined until org version `9.3`. Emacs 26 ships with org `9.1`, so this function is undefined if the user is using the built-in org version. Backporting this function to support Emacs 26, Since that is the minimum supported version.
> (fix): fix support for Emacs 26 built-in org

- org-roam-doctor.el
> (internal): org-roam-doctor require s, dash

- org-roam-buffer.el
Change confusing behaviour where org-roam buffer prints "no citelinks"
even when org-ref is not present.
> (fix): don't print no citelinks if org-ref is not present

- org-roam.el
Fix typo, reword docstring, remove decorative ellipses
> (docs): org-roam.el clarify documentation

- org-roam-buffer.el
> (fix): hide citelinks if buffer has no ROAM_KEY

- org-roam.el
Unused function.
Do we need it?
> (internal): remove org-roam--touch-file

- org-roam.el
Symlinks in the org roam directory allows for multiple separate knowledge bases to be queried as one.
> (feat): Allow for symlinks in the org roam directory.

- doc/org-roam.org
- doc/org-roam.texi
Addresses https://github.com/org-roam/org-roam/issues/726#issuecomment-636127914
Closes #726
> (docs): Add missing Org package-install instructions

- org-roam-db.el
- org-roam.el
Paths with double slashes are causing trouble for some users. We canonicalize the file-names using elisp so it's more robust (at the risk of being slightly slower).
Fixes #724 , #732
> (fix): org-roam--list-files: canonicalize filenames

- org-roam.el
Emacs 26 does not have the follow-symlinks option in
`directory-files-recursively`, so we have to add it ourselves.
Fixes #736 
Ref #733
> (fix): add org-roam--directory-files-recursively

- org-roam.el
I found a regex very hard to read, so I translated it to rx form.
The only test I have done on this code is evaluating:
```
(equal "\\[\\[file:\\(\\(?:[^][\\]\\|\\\\\\(?:\\\\\\\\\\)*[][]\\|\\\\+[^][]\\)+\\)]\\(?:\\[\\(\\(?:.\\|
\\)+?\\)]\\)?]"
(rx "[[file:" (seq (group (one-or-more (or (not (any "]" "[" "\\"))
(seq "\\"
(zero-or-more "\\\\")
(any "[" "]"))
(seq (one-or-more "\\")
(not (any "]" "["))))))
"]"
(zero-or-one (seq "["
(group (+? anything))
"]"))
"]")))
```
But I think that should be sufficient.
> Make a regexp more intelligible

- org-roam-buffer.el
If the `org-roam-buffer--get-create` function is called from a hook
then `get-buffer-window` will return `nil` since the current buffer
may not have been placed in a window yet.  This eventually leads to an
error.
This change moves some code around so that we can use
`save-selected-window` to allow temporary focus on the org-roam
side window so the resizing functions can work.
I also added another window parameter: `no-other-window`.  I'm not
100% sure about this because I don't have a good feel for how the
side window is used.  I want `other-window` to avoid it but I'm not
sure if others do.
> Remove reliance on the current buffer when opening the *org-roam* window

- CHANGELOG.md
- org-roam-buffer.el
- org-roam-compat.el
The variable `org-roam-buffer-window-parameters` gives one more
flexibility in customizing the org-roam-buffer window parameters.
`org-roam-buffer-no-delete-other-windows` is deprecated in favour of
this.
> (feat): add org-roam-buffer-window-parameters

- CHANGELOG.md
- org-roam-doctor.el
- org-roam.el
Roam properties such as `ROAM_KEY` are now case-sensitive. This change makes it
case-insensitive, for people who prefer it that way. Supercedes #730.
> (feat): make roam properties case-insensitive

- org-roam-db.el
Don't add nil tags to the tags table when creating a note
#747 Couldn't manage to do `git rebase`.
> change `org-roam-db--update-tags` to only add non-nil tags

- org-roam-compat.el
This variable is made obsolete, and replaced with
`org-roam-buffer-window-parameters`, but their shape are different and
cannot be used interchangeably.
> (fix): remove alias for org-roam-buffer-no-delete-other-windows

- org-roam.el
This simplifies `org-roam--str-to-list`, and ensures that it parses
numbers correctly too. Fixes #745.
> (fix): simplify org-roam--str-to-list

- org-roam-db.el
- org-roam-doctor.el
- org-roam-graph.el
- org-roam-macs.el
- org-roam.el
- tests/test-org-roam.el
Org-roam now skips over bad properties and throws a warning for the
given file that contains a malformed property. This allows most of the
database rebuild to complete, and for the user to fix the offending
file.
Fixes #728.
> (fix): fix bad behaviour on malformed properties

- org-roam-capture.el
org-roam-capture was querying plist for :file-path
instead of :path.
See: #766
> (fix): org-roam-capture append to existing file

- org-roam-doctor.el
- org-roam.el
This fixes a bug introduced in #770. Interestingly,
`org-element-property` always returns the prop in allcaps, so a
string-equal would have been sufficient. This commit reverts all usages
of `org-roam--extract-global-props` to use the upcase version of the
properties.
Fixes #771
> (fix): fix prop extraction failures

- doc/org-roam.org
- doc/org-roam.texi
Add link to [Roam-migration](https://github.com/fabioberger/roam-migration) in manual.
Closes #411
> (docs): Add link to Roam-migration

- org-roam.el
I'm not one to `git blame`, which is why I won't say that eae97487dcbea2b09249455a390fa501154aec79 introduced it. 🤡
> (fix): Fix syntax for calling compiled versions of functions

- doc/org-roam.org
- doc/org-roam.texi
Add some documentation on how the template system can be used to create notes in sub-directories for tagging purposes. As well as how multiple different templates can be used.
This is important now that subdirectories for tagging is implemented.
I haven't done too much texinfo stuff so let me know if formatting/syntax is incorrect
> Add documentation about multiple templates for capture

- doc/org-roam.org
- doc/org-roam.texi
- org-roam-db.el
- org-roam.el
Context is [discussion in Discourse](https://org-roam.discourse.group/t/error-apply-cannot-find-executable-sqlite3/316).
When the computer is missing sqlite3 or the path is not correctly
set, you get an error message like this:
`Error: apply: Cannot find executable “sqlite3”!`
The motivation of this simple change is to see whether a simple
change to the error message might not change UX, and better
guide end-users who may not be familiar with dealing with
these terse error messages.
> (UX): Add more meaningful error message for sqlite3 

- CHANGELOG.md
- org-roam-db.el
- org-roam.el
Fixes #548.
This is the long-heralded PR to add support for headlines into Org-roam.  The goal is to support all the features that are currently supported for files.
I've been prototyping for couple of days to get a feel for the roadmap, and it's going to take me a couple more days to get it to a reviewable level.  I'll ping when it's ready to be reviewed, but in the meantime, you can check where I'm heading.
> Add support for headlines

- CHANGELOG.md
- org-roam.el
Closes #31 .
This depends on ripgrep, and uses a nasty PCRE regex to find titles that are not yet links.
TODO:
- Ignore `#+TITLE` lines
> (feat): find unlinked references

- org-roam.el
Emacs' in-built rx.el was rewritten in Emacs 27, and the form `anychar`
only exists in later versions. We use the older form `anything` that has
support even in Emacs 26.
Emacs 26: https://github.com/emacs-mirror/emacs/blob/emacs-26/lisp/emacs-lisp/rx.el#L889
> (fix): fix unlinked-references for older Emacs

- org-roam.el
`rg` might be unfamiliar to some, so let's mention the name of the full
executable name.
> (ux): update the error message for org-roam-unlinked-references

- README.md
Ensure use-package installs org-roam.
See: #803
> (doc): Add :ensure to use-package declaration

- org-roam-buffer.el
I want to create a hook for activating this buffer when I enter an org file and deactivating it when I leave.
> (feat): split org-roam-buffer-toggle into -activate and -deactivate

- org-roam-buffer.el
- org-roam-capture.el
- org-roam-protocol.el
- org-roam.el
Allow users to specify a function for finding files in various commands.
Can be let-bound to define new commands that suit user preferences.
See: #790
> (feat): org-roam-find-file-function customization

- tests/test-org-roam-perf.el
- tests/test-org-roam.el
We really want to start tracking down and optimizing cache builds, because it's causing issues for some.
Fixes #742, ref #834
> (tests): add performance tests to CI

- CHANGELOG.md
- org-roam.el
This is useful in scenarios when you want to automatically do something with the
context where the link was inserted. For example, if you are linking someone in
the task, you can add a special tag for this person.
```emacs-lisp
(defun +org-notes-insert ()
"Insert a link to the note."
(interactive)
(when-let* ((res (org-roam-insert))
(path (plist-get res :path))
(title (plist-get res :title))
(roam-tags (+seq-flatten
(+seq-flatten
(org-roam-db-query [:select tags
:from tags
:where (= file $s1)]
path)))))
(when (seq-contains-p roam-tags "People")
(save-excursion
(ignore-errors
(org-back-to-heading)
(let ((tags (org-get-tags)))
(org-set-tags (seq-uniq (cons (+org-notes--title-to-tag title) tags)))))))))
(defun +org-notes--title-to-tag (title)
"Convert TITLE to tag."
(concat "@" (s-replace " …
```
> return selected file from org-roam-insert

- README.md
I used the exsisting example from the README and was told:
> ‘org-roam-show-graph’ is an obsolete command (as of org-roam 1.0.0); use ‘org-roam-graph-show’ instead.
> s/org-roam-show-graph/org-roam-graph-show/ README

- org-roam.el
On old versions of emacsql-sqlite3, this will catastrophically fail. Ref #838
> (fix): fix emacsql-sqlite3-executable possibly unbound

- org-roam.el
> (fix): fix bad upcase for `org-roam-tag-sources`

- CHANGELOG.md
- doc/org-roam.org
- doc/org-roam.texi
- org-roam.el
- tests/test-org-roam.el
I use a directory structure where each subdirectory of `org-roam-directory` is a separate slip-box (e.g., literature notes, work notes, etc).
I believe that's a common enough setup to add built-in support.
> (feat): add 'first-directory option for org-roam-tag-sources

- CHANGELOG.md
- org-roam-db.el
- tests/test-org-roam-perf.el
We use sqlite transactions to commit changes into the database, rather than storing all the data in a list before running one big insert. Hopefully this gives a noticeable perf boost.
Also add `org-roam-db-gc-threshold`, which defaults to a large number. This allows expensive operations like `org-roam-db-build-cache` to execute faster (on 1000 files, cuts execution time from 70s to 50s).
Ref #834
> (perf): use sqlite transactions, and GC less

- CHANGELOG.md
- org-roam-db.el
Closes #816. Warn on duplicate IDs and refs, rather than fail catastrophically. Attempt is made to show a useful error message:
> (feat): warn on duplicate IDs rather than fail

- CHANGELOG.md
- org-roam.el
Resolves symlinks before computing relative paths. Fixes #855.
> (bugfix): fix tag extraction for symlinked directories

- org-roam-db.el
This will ensure atomicity with updates and should stop any partial
updates that may occur.
----
Possible future errors arising from database partial updates. I'm not aware of any bugs due to this currently
> Wrap updates in a sql transaction

- CHANGELOG.md
- org-roam-buffer.el
- org-roam.el
- tests/test-org-roam-perf.el
This simulates roam-research a bit more, adding heading levels to the backlinks buffer.
> (feat): Add header level to backlinks buffer

- doc/org-roam.org
- doc/org-roam.texi
The current documentation made me think that bookmarklet feature was
limited to Firefox. This patch slightly improves it.
> Improve roam-ref docs

- org-roam.el
This seemed to fix some link expansions for me.
> (internal): fix expand-file usage in org-roam--expand-links

- org-roam.el
Restore regex match results after outline extraction.
> (internal): save-match-data on outline extraction

- doc/org-roam.org
- doc/org-roam.texi
- org-roam-db.el
- tests/test-org-roam-perf.el
The high value has been reported to cause significant slowdowns, so we
reset the default, and add documentation for its customization instead.
Ref #834.
> (internal): lower default value of org-roam-db-gc-threshold

- org-roam-capture.el
Closes #875 
New option: `org-roam-capture-function`
Specifies which command is used by org-roam to run the org-capture
process. The default behaviour maintains compatibility with earlier
versions of org-roam. I.E.:
- uses `org-capture`.
- immeadiately chooses the first capture template when
`org-roam-capture-templates` has only one template.
When you've changed `org-roam-capture-function` AND
`org-roam-capture-templates` has multiple templates,
`org-roam-capture-function` is run interactively to
start the org capture process.
Eg. usage: `(setq org-roam-capture-function 'counsel-org-capture)`
> (feat): make customised org-capture function

- doc/org-roam.org
see #870
org-roam is very helpful not only for programmers but also for writers. So, the documentation should be as beginner friendly as possible. This pull request adds some instructions for Windows users and WSL2 related adjustments.
> Add instructions for Windows and WSL2

- tests/test-org-roam-perf.el
Things take more time to run now that we are also caching headline hierarchies.
> (tests): increase perf test threshold

- org-roam-db.el
This makes it clearer that the message shows the changes in the
database, and not the total number.
Ref: https://github.com/org-roam/org-roam/issues/881#issuecomment-653732953
> (internal): add delta symbol in org-roam message

- org-roam.el
Links like `/ssh:me@host:/` cause emacs to lock up asking for the password repeatedly due to using `file-exists-p` in a function passed to font lock.
> (bugfix): prevent file-exists-p opening tramp links

- CHANGELOG.md
- org-roam.el
Previously, if the new file is no longer an Org-roam file, links will
not be fixed. The current behaviour is now to perform the link fixes as
long as the old file as an Org-roam file.
Closes #893
> (fix): rename links as long as old file is Org-roam file

- CHANGELOG.md
- org-roam.el
Adds an interactive function that browses to a random note. Closes #856.
> (feat): add org-roam-random-note

- CHANGELOG.md
- org-roam-buffer.el
- org-roam.el
This adds support for all sorts of ref links (http, https, and any
custom link types). If the ref is not a file or org-ref citation link,
the full link path is used.
Closes #744.
> (feat): support more ref links

- org-roam-compat.el
- org-roam-db.el
Since it is a called interactive, it should be given a public name.
> (internal): org-roam-db--clear -> org-roam-db-clear

- org-roam.el
Adds titles and tags info for interactive calls to ‘org-roam-find-ref’.
I'm not entirely happy with the format of `org-roam--get-ref-path-completions`, and we could probably split the `interactive` behaviour into `org-roam--get-formatted-ref-path-completions`.  Since it's not the only function that would benefit from a clean-up, I'll keep this in mind for later.
Before:
After:
> (feat): Improve interactive format for ref completions

- org-roam.el
Follow-up to #906.
A `C-u` argument will output the unformatted completion-list.
I decided to add line-breaks to the docstring because it was becoming quite crowded, and I think we should probably do it with the rest of the codebase.
> (feat): Implement basic output for find-ref with C-u arg

- CHANGELOG.md
- org-roam-db.el
- org-roam.el
Instead of storing titles as a list within in the Org-roam cache, e.g.
file, ("title1" "title2"). We normalize it and store it as:
file, "title1"
file, "title2"
We need to be able to find a file given a title. This is in preparation for resolving fuzzy links such as `[[Title]]`.
In the old format, we need to do some elisp post-processing, but once we normalize, we can find all files that have that given title.
> (internal): normalize titles in database

- org-roam.el
Follow-up to #908.
I've grepped `org-roam--get-title-or-slug` in the repo, and we don't see to be expecting a list anywhere else.
> (fix): Adapt get-title-or-slug to new schemata

- org-roam.el
Caused by #908.
Again, I've grepped the directory for similar patterns, and this was the only one.
> (fix): Update rename-file-advice to new schemata

- org-roam.el
Exclude backup files from triggering the file/link renaming advice
> Exclude backup files from renaming advice

- org-roam-db.el
7f56df7f4d8b7da46096f084e906b7b0f64726ef introduced the delta symbol in the
db-rebuild message to make it clearer the the db was updated as opposed to
being completely rebuilt.
However, the unicode symbol used, U+1D6AB, which is the mathematical, bold
variant of the Greek letter is not present in many fonts.  Switching to
U+0394, the base Greek letter, is better for compatibility.
Example from before:
Note the large line-height that is a side-effect of Emacs's struggling to find a font with the appropriate symbol.
> (fix): Change symbol used for delta

- org-roam-capture.el
Declare `org-roam-capture-templates` with `defcustom` and update the
docstring
See #922
`org-roam-capture-templates` is a user variable and should be accessible from the Customize interface.
> defcustom `org-roam-capture-templates`

- org-roam.el
Caused problems with plain links, i.e., those not framed by
brackets (e.g. `file:foo.org` or `id:$uuid`).
Fixes #926.
> (fix): Check if link-description is empty prior to inserting

- org-roam-buffer.el
Don't modify line-breaks in preview content. Closes #630.
> (fix): fix display of preview content

- org-roam.el
Fixes #837.
The existing merged fixes do not actually work, because `fboundp` tests for a function.
>  (fix): Check sqlite3’s executability using boundp

- org-roam-macs.el
Fixes #956.
The extraction of links rely on appropriate regexp being set for
outline-mode, to determine the outline information. Because the
information were extracted in a temporary buffer, the outline regexp was
not set. This corrects for that, but probably adds significant
extraction time.
> (fix): enable org-mode in temp buffers

- org-roam-db.el
Before this patch all hash-sums were computed over the files or
buffers content.  For encrypted files this means that we first have
decrypt the file before we can compute the hash-sum.  So when the
cache gets updated all gpg files need to be decrypted which is a very
expensive operation and nearly defeats the purpose of having a cache
in the first place (for gpg files).
This changes the computation of hash-sums for gpg encrypted files.
Instead of the content the raw files on disk will be read.
This shouldn't interfere with the current use of hashes.
There is one ugly (but otherwise inconsequential) ward, though.
For open buffers of to be gpg encrypted files we need to compute the
hash sum over the contents as well.  This is because there is
no (easy) way to get the encrypted version.  The …
> Make the db caching more efficient for gpg encrypted files 

- CHANGELOG.md
- org-roam-capture.el
- org-roam-dailies.el
- org-roam.el
This PR enables the long-awaited nested-captures.
This PR introduces a number of changes:
1. Adds a hook to `org-capture-prepare-finalize-hook`, which installs `org-roam-capture--finalize` into `org-capture-after-finalize-hook` if the capture is an Org-roam capture. This function contains key functionality for Org-roam to Do The Right Thing after specific interactive functions, such as finding the file, or inserting a link.
2. A patch for `org-capture-finalize`. Specifically, we make `org-capture-plist` valid during `org-capture-finalize`.
3. Many hacks that were originally in place are now replaced with nicer alternatives.
> (feat): enable nested captures

- org-roam.el
When `tramp-mode` is active, calling `file-truename` on a non-existing/non-reachable remote path makes tramp to attempt at opening the non-reachable remote connection, and thus prevents `org-roam` from updating the cache database.
This is a hotfix for #967, not tested properly. 
`file-truename` is used throughout `org-roam`, so there may be other issues. It would be nice to wrap it in a protecting function that would check if the file is remote and behave accordingly.
> check if path is remote before using file-truename

- doc/org-roam.org
- doc/org-roam.texi
https://en.wikipedia.org/wiki/Emacs
Emacs development began during the 1970s.
> Emacs created in 76, not 85.

- CHANGELOG.md
- org-roam.el
Drop the wrapper, and refactor as an org-store-link function.
Fixes #853, #982.
Right now, as long as you're in an Org-roam file, it'll create an ID when you're capturing on a heading.  I think it's going to be hard to make it cleaner, i.e., only creating the ID when necessary.  Right now, if you cancel the capture, the ID remains, which leads to ID rot.  I'm investigating.
> (fix): Simplify org-roam-store-link

- org-roam-db.el
When using gpg encrypted files it might happen (intended) that on a
certain machine there is no key to decrypt that file.  Currently an
error of type 'file-error' will be raised and the cache building
process will be aborted.  So in a certain sense org-roam will not
be functional in that case.  Furthermore, when the the cache building
process is run from the emacs initialisation it will come to a halt as
well and the user will be left with a half working emacs instance.
This patch changes the behaviour to just skipping over offending files
while removing them from the db at the same time.  Here an offending
file is any file that cannot be read for indexing.  As it stands this
case only works reliably for the case of missing gpg keys.
An error buffer will still show up and be prominently …
> Skip unreadable files while building the cache

- CHANGELOG.md
- org-roam-buffer.el
- org-roam-macs.el
- org-roam.el
- tests/test-org-roam.el
This is an alternative implementation of #592, which I currently favour. Instead
of adding a `roam:` type link, we add support for linking org-roam files via
fuzzy links:
TODOs:
> (feat): support fuzzy links

- .readthedocs.yml
This has long been superceded by the internal and published online manual.
> (docs): remove readthedocs build

- org-roam-macs.el
- org-roam.el
Revert to emacsql vector format to retain escaping. Fixes #1007.
> (fix): fix get-backlinks failing for unescaped strings

- doc/org-roam.org
- doc/org-roam.texi
Org-fc now has it's own website, I've updated the link in the documentation accordingly.
Should I add an entry to the changelog even if this is just a minor change to the docs?
The main repository of org-fc is moving to sourcehut,
I prefer hosting the documentation on my own website instead of using a github readme for it.
> Update url of org-fc

- org-roam.el
Fuzzy links can now be auto-replaced on navigation and on file-save, if
there is already a match. This is now the default behaviour, controlled
via `org-roam-auto-replace-fuzzy-links`.
> (feat): fuzzy link auto-replacement

- org-roam.el
This can trigger a lot of hooks, which may not be desirable.
> (fix): remove save-buffer on id creation

- org-roam-db.el
- org-roam.el
Allow addition of tags via capf. Fixes #1001 .
> (feat): tag completion via capf

- org-roam-compat.el
- org-roam-macs.el
- org-roam-protocol.el
- org-roam.el
Following the advice from the coding conventions from the Emacs manual,
we preface the compatibility functions with the org-roam namespace.
> (internal): fix CI for compat functions

- org-roam-db.el
Fixes #1026 when compiling asynchronously. Basically org-roam-db.el references `org-with-wide-buffer` without it imported.
> Require org-macs in org-roam-db to fix undefined org-with-wide-buffer macro.

- CHANGELOG.md
- org-roam.el
On my setup (Samsung 970 EVO Plus NVMe SSD, Core i7 8750H, emacs 26.3 on WSL1 of Windows 20H2 beta channel, so not too slow) I see on average about 0.5 seconds per 500 lines of orgmode spent in `org-roam-db--update-file` as measured with the Emacs Lisp Profiler (elp).
As you can imagine, this is quite noticeable when you have files of a thousand or two lines. Many of my org-roam files are small, but my monthly journal files are usually in that range. Also, I habitually save quite often as I work.
I know I'm not the only one.
This PR moves the actual save-hook org-roam db updating into an idle handler. Every time you invoke save, the filename is added to an idle-save-list if it's not already there. Whenever the idle handler runs (it should do this after 2s of idle time as measured by …
> At after-save-hook schedule file for idle update

- org-roam-db.el
- org-roam.el
This small PR adds a customization variable with which org-roam's new headline linking functionality can be disabled.
This  means that:
- org-roam will not assign an auto-id when you use `org-store-link`
- org-roam will not scan the headlines of each org file for IDs to save into its database.
I would prefer not to have an org-id automatically assigned whenever I do `org-store-link`.  This is especially troublesome when I have already assigned a `CUSTOM_ID` as I often do for normal orgmode use, and then this code assigns an automatic ID and links to that instead.
Furthermore, I don't make use of org-roam's headline linking functionality, preferring its initial approach of supporting exclusively compact, single-thought files, a la zettelkasten, and so having org-roam extract the IDs of all …
> Add custom var to disable headline linking

- org-roam.el
This change ensures that `org-roam--file-update-timer` has only one
instance per Emacs instance. Fixes #1037
> (fix): fix possibility of multiple idle timers

- org-roam-capture.el
I want to bind `org-roam-capture` to a key by using a template. And I do not want to select a template every time.
Keeping `org-roam-capture` arguments the same as `org-capture`, then you can designate template by using KEYS. Which is useful if there are more than one template in `org-roam-capture-templates`.
> let org-roam-capture's arguments same as org-capture

- CHANGELOG.md
- doc/org-roam.org
- doc/org-roam.texi
- org-roam.el
I personally store all my finished tasks in one big archive file, and I want to be able to ignore its existence.
This PR modifies `org-roam--org-roam-file-p` to take a new user option, `org-roam-file-exclude-regexp`, into account. If a file matches that regular expression it is not considered an Org-roam file.
> Allow ignoring files with a regular expression

- CHANGELOG.md
- org-roam.el
- tests/test-org-roam.el
Org-roam takes a long time to process files. In addition, big files (10000+ lines) can take several seconds to process after it is modified. This becomes unbearable for eg. habit (`org-habit`) tracking files.
This PR introduces some optimizations:
- Replace unnecessary uses of `org-element-parse-buffer`
- `org-roam--extract-headlines`: Use `org-map-region` and `org-entry-get` instead of `org-element-parse-buffer`.
- `org-roam--extract-titles-headline`: Find the first headline with `org-outline-regexp-bol` instead of using `org-element-parse-buffer`.
- If it's available, use `org-collect-keywords` which is a lot faster as it also avoids `org-element-parse-buffer`. (As it is a relatively new function in Org, [added in April 2020](https://code.orgmode.org/bzg/org-mode/commit/b4e91b7e944c900db …
> Speed up extraction of global props, headlines, and title

- CHANGELOG.md
- org-roam.el
Completions for Org-roam files can be enabled everywhere by setting
`org-roam-completion-everywhere` to `t`.
Fixes #1051
> (feat): allow enabling of link completions everywhere

- org-roam.el
Replace call to org-element-parse-buffer with simple regexp search.
> (internal): use regexp search for link-extraction

- CHANGELOG.md
- org-roam.el
Previously the rename file advice was responsible for trying to update
the link descriptions as well. This was brittle and didn't work in some
cases.
The rename-file-advice has now been altered to solely deal with breaking
links. We use the before and after-save-hooks to determine whether the
title has changed, and update the link descriptions accordingly.
Fixes #1044
> (feat): rename link descriptions on title changes

- CHANGELOG.md
- doc/AUTHORS.md
- org-roam-doctor.el
- org-roam-macs.el
- org-roam.el
Generation of these preview is often expensive and completely unnecessary
when the buffer won't actually be viewed.
This will have the side effect of not showing latex or images when fixing something in a doctor run, but I think that is worth the sacrifice.
----
Should make DB builds and doctor runs faster when the user has `org-startup-with-latex-preview` or `org-startup-with-inline-images` set.
> Disable latex preview and images for temp buffers

- tests/test-org-roam-perf.el
Several performance improvements have vastly improved the cache build
time. We reduce it so CI catches any further degradation.
> (test): reduce expected cache time-to-build

- CHANGELOG.md
- org-roam-db.el
- org-roam.el
Adds `org-roam-title-change-hook`. This now contains two functions:
1. `org-roam--update-links-on-title-change`: updates the link
description of all files that link to the current file.
2. `org-roam--update-file-name-on-title-change`: updates the current
buffer's filename to reflect the updated title.
Resolves #939 .
> (feat): rename file on title change

- org-roam.el
Creating new files with org-roam-insert causes errors:
Wrong type argument: char-or-string-p, nil
> Handle new file title change.

- CHANGELOG.md
- org-roam-faces.el
- org-roam.el
`org-roam-tag-face` controls the appearance of tags in the minibuffer.
Defaults to a bold face.
> (feat): add org-roam-tag-face

- org-roam.el
Fixes #1082, #1077, #1074
When reverting link extraction to using the `org-element` api, the
preview content (org-element-at-point) was incorrectly extracted,
causing incorrect preview content and cryptic error messages.
> (fix): fix link-extraction extracting wrong element

- org-roam.el
- tests/test-org-roam-perf.el
In addition to getting the correct element, obtaining the outline path
requires the point to be correctly set.
cc @Wetlize, thanks for testing.
> (fix): fix link outline extraction

- org-roam.el
`seq-sort-by` does not modify the list in place, so we need set the `rows` variable directly.
> (fix): fix sort by mtime in completions

- org-roam.el
`org-roam-enable-fuzzy-links` controls whether to enable Org-roam's
fuzzy link behaviour. This can be undesirable to some users, who would
like to use [[foo]] links to reference named blocks.
> (feat): add org-roam-enable-fuzzy-links

- org-roam-buffer.el
Without this change nothing of value is displayed in `*org-roam*` buffer due to use of symbolic links to my org files.  The only thing I see is some path like "../../../x/y/z" as the first line, then simply "No backlinks!" as the third line.
With this fix, I see the title of the org file in bold as the first line as well as backlinks which I can click.
> added two file-truename calls to fix backlinks in *org-roam* buffer

- org-roam.el
Org expects face functions to save-match-data, or it would lead to
infinite recursions with use of some Org functionality such as
org-agenda (h.t. @myshevchuk for figuring this out)
Fixes #1096 and fixes #1045.
> (fix): fix org-agenda hangs on face computation

- org-roam-buffer.el
- org-roam-capture.el
- org-roam-compat.el
- org-roam-completion.el
- org-roam-dailies.el
- org-roam-db.el
- org-roam-dev.el
- org-roam-doctor.el
- org-roam-graph.el
- org-roam-macs.el
- org-roam.el
This version includes the fix that ignores the user .sqliterc which can
interfere with expected behaviour.
See https://github.com/cireu/emacsql-sqlite3/pull/15 for more details.
Depends on https://github.com/cireu/emacsql-sqlite3/pull/17/ too.
> (internal): bump required version of emacsql-sqlite3 to 1.0.2

- org-roam-dailies.el
The function org-roam-dailies--list-files includes backup files when
creating a list of all daily notes. This change filters those out, alongside
auto-save files which are already properly handled.
Without this change, navigating to the 'next-note' from 2020-09-10.org would take me to 2020-09-10.org~ instead of 2020-09-11.org
This applies to #978. I notice that this is the same issue that was fixed in org-roam--org-file-p in #98.
> Exclude backup files (i.e., *.org~*) when navigating notes

- org-roam-buffer.el
- org-roam-capture.el
- org-roam-compat.el
- org-roam-completion.el
- org-roam-dailies.el
- org-roam-db.el
- org-roam-dev.el
- org-roam-doctor.el
- org-roam-graph.el
- org-roam-macs.el
- org-roam.el
See the detail in issue #1038 
With using [test files](https://github.com/nobiot/org-roam-performance-test-v1.2.1-Windows) of five (5) `.org` notes with `https` URL links, the following performance improvement is observed:
---
```
#+begin_src emacs-lisp
;;(org-roam-db--close-all)
;; delete the db file manually
(benchmark 1 '(org-roam-db-build-cache))
#+end_src
```
[2020-09-15 Tue]
Before change
Elapsed time: 123.473523s (0.506992s in 12 GCs)
After change
1st: Elapsed time: 0.253582s
2nd: Elapsed time: 0.240944s
3rd: Elapsed time: 0.568807s (0.043532s in 1 GCs)
> (fix): #1038 long db build when notes contain URLs with https://

- CHANGELOG.md
- org-roam.el
URL links such as `https://google.com/hi/` get split into link-type `https` and path `google.com/hi/`.
On Linux, the `f-relative-p` check passes since `google.com` is a valid relative path on unix filesystems. It is possible that this path is not valid on Windows, so the db build gets stuck forever in this function.
Not sure if this is the true cause, but I think it makes sense to me, will require some testing.
cc @nobiot @ahristow
> possibly fix hang for windows

- org-roam.el
This prevents ID links from being expanded in the Org-roam buffer.
> (fix): perform link expansion only on file links

- org-roam.el
PR #1076 prevented the title change hook from causing errors for new files,
but completely disables the behaviour. To cause the title hooks to take
effect, we set the local variable `org-roam-current-title` upon save,
regardless of whether the hook ran.
This should have the effect of enabling the title change behaviour upon
first save, assuming the save succeeds.
Addresses https://org-roam.discourse.group/t/org-roam-update-file-name-on-title-change-works-discontinuously/767
> (fix): fix file-name change not working on new files

- CHANGELOG.md
- org-roam-buffer.el
- org-roam-db.el
- org-roam-graph.el
- org-roam.el
`file-truename` calls alone accounts for over 20% of CPU samples in `org-roam-db-build-cache`. It's expensive and unnecessary. To get an absolute path, `expand-file-name` alone is enough.
#1099 fixes org-roam-buffer by making it consistent with the DB. This PR should still keep them consistent while speeding up `org-roam-db-build-cache` by 40% (110s → 70s on my setup).
Org-roam shouldn't care if a file is a symlink or located in a symlinked directory, and therefore shouldn't be resolving symlinks. There is no point in canonicalizing everything: each Org-roam notes repository already has its own org-roam.db.
This can probably be considered an extended version of #928.
> Remove file-truename everywhere

- makem.sh
Package-lint gives errors that are not really fixable, as it makem does not install the version of Org we require for Org-roam, demanding a minimum version of Emacs 27.1 instead.
> (ci): do not return on package-lint error

- README.md
- emacs throws a warning. It's removed by using `org-roam-graph`
Fixes #1120
> update `org-roam-graph-show` in README.md:

- org-roam-buffer.el
- tests/test-org-roam-perf.el
- tests/test-org-roam.el
org-roam-buffer should no longer be resolving the symlinks as well.
> (fix): remove other occurrences of file-truename

- org-roam.el
My org-roam buffer list is very long. The number is about 200 files, and in my workflow I aways refile heading. So when the auto save trigger the push queue function will stuck. And then the idle timer will trigger in 2 secs. So In may situation I like to customize this idle timer interval to bigger value
> feat: extract idle timer interval as a customizable value

- org-roam-db.el
Treat encrypted and non-encrypted files the same.
> (perf): simplify hash computation

- org-roam.el
`org-roam-id-find` opens the file containing the ID to get the marker.
We don't need to get the exact point for face computation.
Fixes #1129.
> (fix): fix additional buffers opening from ID face

- org-roam-link.el
Please take this as a gentle inviting for a discussion with a concrete implementation.
The intention of this commit / PR is to suggest an alternative to the current
capf in org-roam-link.el. Currently, you need to type [[roam:]] for capf to
work for the link completion-at-point. This alternative enables capf to be
triggered without roam: for [[|]]. roam: is added automatically with
exit-fn (implemented as a lambda function as originally intended).
The keycord for `[[roam:]]` is not necessarily fluid for writing. I assumed this was a workaround, and ideally the way this alternative proposes is an originally intended behavior for completion-at-point for links with titles.
Up for discussion of course.
My initial testing shows that it works as intended.
In this animation, capf is not manually …
> (feat): enable capt for [[|]]; add exit-fn

- org-roam-buffer.el
- org-roam-macs.el
- org-roam.el
This changes ref extraction to parse the ref using the org plain-links
syntax. This works for arbitrary `cite` links, and web links.
Link storage and ref lookup is now based on the path (e.g.
`//google.com`) or `author_year`.
> (fix): fix refs not showing in backlinks buffer

- org-roam-capture.el
Remove unnecessary and unused variables in org-roam-capture.el.
> (internal): remove file-name and header default

- org-roam.el
Fix org-roam-completion-everywhere still producing fuzzy links
> (fix): fix org-roam-completions-everywhere

- org-roam-db.el
- org-roam.el
`find-file-noselect` is affected by the user's init.el, and there is
little control over what is being activated. For database updates, read
access is all we need, so we use `with-temp-file`.
> (internal): replace find-file-noselect with with-temp-buffer where possible

- org-roam-db.el
`org-mode` builds the `org-agenda-files` menu entry for every file
visited. This functionality isn't required and useful when building
the cache in temporary org buffers.
Performance improvement. Master:
```
ELISP> (benchmark 1 '(org-roam-db-build-cache 1))
"Elapsed time: 45.214780s (11.347281s in 219 GCs)"
```
This branch:
```
ELISP> (benchmark 1 '(org-roam-db-build-cache 1))
"Elapsed time: 10.499171s (2.793775s in 54 GCs)"
```
I have all my org-roam files (550 currently) in my agenda-files:
`(add-to-list 'org-agenda-files "~/shared/org/roam"))`
I was surprised that org makes 550 menu entries for every visited file, even if the buffer is only in temporary use (while building the cache).
> (perf): disable org-agenda while building the cache

- org-roam-db.el
Another location where filename needs to be passed down as per #1150.
> (fix): pass file name to extract-headlines.

- org-roam.el
same as #1146 without introducing a new macro
> (fix): fix org-roam-id-find buffer-kill logic

- org-roam-db.el
- org-roam.el
Previously we had overwritten the Org's store link function for files,
to create IDs if the point was under the headline. This has several
issues:
1. It becomes impossible to store a link to the file using `org-store-link`
2. This override is global across Org, although we had a guard in
`org-roam-store-link`
3. IDs are created during an org-capture, because org-capture calls `org-store-link`
This is unnecessary. Org provides `org-id-store-link` instead for this
purpose. Instead, we advice `org-id-new`, to queue the file for a DB
update if an ID was created.
Also, setting `org-id-link-to-org-use-id` to `t` restores this behaviour.
> (feat): remove IDs created during capture

- org-roam-buffer.el
- org-roam-link.el
- org-roam.el
Adds `org-roam-link-file-path-type`, used for link path computation
wherever sensible. This includes in the org-roam backlinks buffer, and
in link replacement.
Also moves link expansion/fixing from cache build to Org-roam buffer
render time. This reduces cache build time, but makes buffer rendering
slightly slower.
> (feat): clean up link expansions

- org-roam-buffer.el
remove stray `(org-roam-link-make-string)` call. Fixes https://github.com/org-roam/org-roam/issues/1158#issuecomment-701559392
> (fix): fix buffer ref-links

- CHANGELOG.md
- org-roam-buffer.el
- org-roam-capture.el
- org-roam-db.el
- org-roam-link.el
- org-roam.el
- tests/roam-files/headlines/headline.org
- tests/test-org-roam.el
Additionally cache IDs at outline-level 0, now that property drawers are supported in Org 9.4.
Update `org-roam--format-link` to prefer ID links wherever possible. That is, when a file has an ID, use an id link instead of file link.
Addresses #1091
> (feat): support file-level IDs

- CHANGELOG.md
- org-roam-compat.el
- org-roam-db.el
- tests/test-org-roam.el
Move the default location of `org-roam.db` to the user's Emacs
directory. This is a more sensible default: those who sync their
Org files would not have the database synced over as well.
> (internal): move org-roam.db default location

- org-roam-link.el
Links now complete to [[roam:*foo]] rather than the incorrect [[*roam:foo]]
Fixes #1165
> (fix): fix [[*]] completion

- org-roam-buffer.el
- org-roam-compat.el
- org-roam-protocol.el
- org-roam.el
Now that CI throws a non-fatal error, this cleans up the code quite a bit, since we already require a minimum of Org 9.3 in the package header.
> (internal): remove compat functions

- org-roam.el
* org-roam.el (org-roam--extract-ids): Only check for ID if first
character in file is at outline level 0. #1172
#1172
> (fix): Fix org-roam--extract-ids at outline level 0

- CHANGELOG.md
- org-roam.el
Fix `org-roam--extract-links` erroring at content boundaries. Cherry-picked commits from both @d12frosted and @Whil-'s PR.
> (fix): fix org-roam--extract-links

- doc/org-roam.org
- doc/org-roam.texi
also remove documentation on deprecated variable ~org-roam-buffer-no-delete-other-windows~
Fixes #1177
> (docs): document org-roam-buffer-window-parameters

- org-roam-db.el
- org-roam.el
This is in preparation to fix an unreported bug, and should cause no logical changes.
When processing the file update queue, we need to clear the database for all the files first, or there may be false reports on duplicate items (e.g. renaming a file with IDs in them).
> (internal): simplify internal db cache update api

- org-roam.el
- Prevent error when trying to move file to same name
- Prevent string matching in org from messing with the current re-search-forward
position which has caused infinite broken search and replace in testing (might
not affect all org versions or may be due to certain code paths)
I tried to change the title of a page from "Webassembly" to "WebAssembly", which caused an error due to renaming the file to the existing name.  After fixing that, auto-updating links began corrupting files in this case.  A file with a link to "Webassembly" began infinitely inserting (broken) links to the "webassembly.org" file at the beginning of the file, as something was evidently changing the match position and causing `replace-match` in `org-roam--replace-link` to replace the wrong area.
> (fix): allow title changes that don't modify filename

- CHANGELOG.md
- org-roam.el
Otherwise it breaks `org-roam-db-build-cache` as it relies on temporary buffer.
Without keeping the buffer, `org-roam--extract-links` kills it and any further
functionality of file processing breaks.
> (fix): do not kill temp buffer when extracting links for file

- CHANGELOG.md
- doc/org-roam.org
- doc/org-roam.texi
- org-roam.el
Fixes the scenario where the face is reported as invalid although it is part of Org's ID files (e.g. in the agenda).
Fixes #1191.
This can however slow face computation a lot (when there are many org id/agenda files). Here, we choose to focus on correctness. To mitigate this issue, we change the default scope of application of the face to Org-roam notes only.
> (fix): fall back to org-id search ID face computation

- CHANGELOG.md
- org-roam.el
Makes `org-roam-format-link` respect `org-roam-link-title-format`.
> (fix): use org-roam-link-title-format in link replacement

- org-roam-buffer.el
* org-roam-buffer.el (org-roam-buffer--find-file): Make
org-roam-buffer--find-file insensitive to mutation of global
variables.
Issue #1198.
> (fix): let-bind org-roam-last-window (#1198)

- CHANGELOG.md
- org-roam-db.el
Org-roam used to perform the removal of deleted files towards the end.
This can cause some issues with db rebuilds. Consider this scenario:
1. Create a file `foo.org` with `id:abc`
2. Run `org-roam-db-build-cache`
3. Delete `foo.org`
4. Create a file `bar.org` with `id:abc`
5. Run `org-roam-db-build-cache`
Here Org-roam will complain that the id `abc` is a duplicate, and error
out, because the data for `foo.org` has not yet been cleared from the
database. This PR reorders the db creation steps the following way:
1. Figure out which files no longer exist, and which files are modified
2. Clear the database for these files, leaving only files that are
unmodified in the database
3. Insert new data from modified files into the database
> (fix): org-roam-db-build-cache: fix order of processing

- org-roam-db.el
- org-roam-graph.el
- org-roam.el
- tests/test-org-roam.el
from -> source
to -> dest
"from" is a reserved keyword in sqlite, so we avoid it.
Closes #1207
> (internal): rename link columns

- org-roam-db.el
Async db updates should work with multi-dirs.  Followup to #1210, #1212.
> (fix): support multidir with dirty db flag

- org-roam.el
`org-roam-id-open` overrides the behavior of `org-id-open`, but it doesn't replicate the behavior of calling `org-mark-ring-push`: https://code.orgmode.org/bzg/org-mode/src/master/lisp/org-id.el#L713, so when using org-roam, it's not possible to go back with `C-c &` after opening ID links.
> (fix): save current position in mark ring before id-open

- org-roam-buffer.el
- org-roam.el
- tests/test-org-roam-perf.el
Prompted by https://github.com/org-roam/org-roam/issues/1209#issuecomment-716224554, I figured that font-locking was what was killing the org-roam buffer during backlink buffer population and causing `window-live-p` errors.
This PR changes that. `org-roam-id-get-file` no longer falls back onto the current buffer: It queries the org-roam database, and optionally `org-id-locations`, and declares that it does not exist if it isn't in either.
Fixes #1209
> (fix): fix id-face killing buffers

- org-roam-db.el
- org-roam-graph.el
- org-roam-link.el
- org-roam-macs.el
For undefined functions: for example, s.el and org-element should be `require`'d when their functions are used.
Unused lexical variables: if Org isn't loaded yet, dynamic variables defined in org.el would be treated as lexical and byte-comp would emit this warning. This is especially important in the future as native-comp / gccemacs will optimize away unused lexical variables, and we cannot rely on Org having been implicitly loaded before our modules are compiled.
(This is also the second culprit behind why the infinite loop happened in #1078: besides org-roam-mode being started in org-mode-hook, the code setting org-mode-hook to nil is optimized away.)
Explicitly stating in our modules that the variables are dynamic prevents that.
> (internal): make sure there are no byte-comp warnings about undefined functions or unused lexical variables

- CHANGELOG.md
- org-roam.el
Prevent renaming file and changing links incorrectly due to using `(org-narrow-to-subtree)` and saving.
The extract title functions will only use the narrowed contents when the buffer being read is narrowed.  These functions might ignore the `#+title` line, and use the first found subtree as the title instead.  Now all the links to the file and the filename has been changed, and won't be changed back unless narrowing is removed and another change is made and the file is saved again.  However if the file is reloaded and the title changed, it won't be since all the links no longer match the title, leaving the affected files with links that no longer match the title.
> (fix): widen before title extraction

- CHANGELOG.md
- org-roam.el
Fixes #1227. Targets bracket links only.
> (fix): fix relative link replacement

- org-roam-completion.el
This way, in case of the initial-input being an exact match, ivy will suggest this one first.
For example, say I have the two org-roam files with titles "vault" and "I like
vault" and I am writing a third file with the sentence "Let's discuss about
vault". If I want to transform the word vault into the link to the appropriate
org-roam file, I tend to highlight the word and press C-c n i. ivy would propose
the two files "vault" and "I like vault", with "I like vault" pre-selected. With
the `:preselect` clause, "vault" is pre-selected and I only have to press Enter to
create the link. IMHO, this default behavior quite sensible.
> Add the use of :preselect in ivy-read

- CHANGELOG.md
- org-roam.el
Adds a boolean variable `org-roam-prefer-id-links`. When non-nil, it
will create ID links where possible.
Addresses #1235
> (feat): add org-roam-prefer-id-links to select linking method

- CHANGELOG.md
- org-roam-buffer.el
- org-roam-db.el
- org-roam.el
- tests/roam-files/cite_ref.org
- tests/roam-files/multiple-refs.org
- tests/test-org-roam-perf.el
- tests/test-org-roam.el
I'd like to be able to associate multiple `ROAM_KEY` keywords to the same file. This will allow multiple bibliographical entries to share the same file.
My actual use case is that I want to add both a book and its chapters to my bibliographical database. If a file can only have one `ROAM_KEY` keyword, we have to create a note file for each chapter *and* the book. I'd like to have the choice of putting them all in one file.
Note that this is the inverse of #587. #587 wants one-key-to-many-files, while this implements many-keys-to-one-file.
This also allows setting both a URL and a cite key as referring to a file. For example:
```org
#+TITLE: swyx - Learn in public
#+ROAM_KEY: cite:shawnwang20180619
#+ROAM_KEY: https://www.swyx.io/learn-in-public/
```
This PR makes …
> (feat): Allow one file to have multiple roam_key statements

- CHANGELOG.md
- org-roam-capture.el
- org-roam-protocol.el
I believe we supported this feature a while ago, but an iteration must have overridden it.
You can now use `%i` in `org-roam-capture-ref-templates` to insert the selected text on the web-page you are capturing.  Note that it can either appear in `:head` (expanded once on file creation) or in the body of the template (expanded every time the ORP is called on a given webpage).  The latter makes it a good option for incremental reading.
Here's a use-case:
```el
(defun zp/org-protocol-insert-selection-dwim (selection)
"Insert SELECTION as an org blockquote."
(unless (string= selection "")
(format "#+begin_quote\n%s\n#+end_quote" selection)))
(setq org-roam-capture-ref-templates
'(("r" "ref" plain
(function org-roam-capture--get-point)
""
:file-name "web/${slug}"
:head "#+title: ${title} …
```
> Allow org-roam-protocol to capture the webpage's selection

- org-roam.el
I was trying to run `org-roam-unlinked-references` and it detected no unlinked references in all cases. After manually copying the command line from this file into my shell, I determine that the `rg` command was failing due to no PCRE2 support, without the Emacs command reporting any errors.
> Add error message if rg has no PCRE2 support

- org-roam-capture.el
- org-roam-dailies.el
For captures, enforce that `:file-name` needs to be specified, and
`:head` when not provided defaults to the empty string (i.e. no head)
> (internal): remove unnecessary variables

- doc/org-roam.org
- doc/org-roam.texi
This generates texi documents with understanding of variables and
functions.
When documentation is changed, maintainers will amend the commits to ensure that
the texi file is appropriately generated.
> (docs): use ox-texinfo+

- doc/org-roam.org
- doc/org-roam.texi
After #1215, "Each note can only have 1 ref" is no longer true.
Additionally, this PR rewrites the rest of the section in a way that makes it clear that website refs also enable ref backlinks, and aren't only useful for the roam-ref protocal.
> (doc): reflect that we now allow multiple refs per file and clarify ref usage

- doc/org-roam.org
- doc/org-roam.texi
These are various manual changes that I think are too small to be in their own individual PRs.
Motivation for each change:
- options: explicitly enable smart quotes on export
This prevents this file from accidentally being exported without smart quotes.
- zettelkasten introduction: put fleeting notes and permanent notes in their own sections
This IMO serves two purposes:
1. Show the fleeting / permanent notes concept up front in the table of contents, and
2. Allow people to eg. link to https://www.orgroam.com/manual/Fleeting-notes.html for easier reference of this concept.
- roam protocal: remove extraneous heading
I'm not sure if this heading had / has a purpose, but right now it just causes the table of contents to look like
```
14 Roam Protocol
14.1 _ :ignore:
```
These changes are …
> (doc): various improvements

- org-roam.el
Change `org-roam--backlink-to-current-p` to only perform a DB query.
Possibly address #1187, #1151
> (fix): fix backlink-to-current-p killing buffers

- CHANGELOG.md
- doc/org-roam.org
- doc/org-roam.texi
- org-roam-compat.el
- org-roam-db.el
- org-roam.el
Add `org-roam-db-update-method`, which can be one of two choices:
1. `immediate`: the cache is updated upon file changes
2. `idle-timer`: Marks the org-roam database as dirty. If Emacs idles
for some seconds, the Org-roam cache is updated. This is the default,
and current behaviour.
The idle method makes for a smoother editing experience, but some
inconsistencies can be faced.
Using the `immediate` method fixes #1137.
> (feat): add `org-roam-db-update-method`

- README.md
I was setting up the org-roam today and saw that the current link in `README.md` points to the 404 page. This change should fix this.
> (fix) Link to the documentation page

- CHANGELOG.md
- doc/org-roam.org
- doc/org-roam.texi
- org-roam-capture.el
Remove the requirement that the OLP already exists in the captured file.
Also, make OLP available beyond dailies functionality.
> (feat): capture: create OLP if does not exist

- doc/org-roam.org
- doc/org-roam.texi
The `olp` option in the lab notes example was swapped.
> documentation example for org-roam-dailies typo

- doc/org-roam.org
- doc/org-roam.texi
- org-roam-buffer.el
- org-roam-db.el
- org-roam.el
Every file has a title (or the slug) when saved into the database, so this
function is redundant in most cases (e.g. in org-roam-buffer, where backlinks
are fetched from the database).
> (internal): remove org-roam--get-title-or-slug function

- org-roam-db.el
> (fix): use correct type for `org-roam-db-update-method`

- org-roam-macs.el
This ensures that relative paths in keywords such as `#+setupfile:` and
`#+include:` work when building cache etc.
After some _very brief_ testing it didn't seem to break anything and it has fixed the issue I was having. However someone more familiar on where else and how `org-roam--with-temp-buffer` is used would probably want to double check that this won't break something.
Some discussion [here](https://org-roam.discourse.group/t/parsing-of-tmp-buffers-breaks-relative-include-handling/919). Basically every time the cache is built if you have a relative `#+setupfile:` it throws a warning (and doesn't include it). This is annoying and could potentially break if you need behaviour that is in that setupfile during cache builds (e.g. if you included roam tags, aliases, titles in it).
> Set default-directory in org-roam-with-temp-buffer

- org-roam-buffer.el
- org-roam-db.el
Finding an Org-roam file that does not exist yet triggers the find-file
hook, resulting in an Org-roam buffer update, attempting to show the
file. However, if the file does not yet exist, attempts to show the file
will not work, since the database does not contain the relevant
information yet.
This bug has always been present, but was only recently made visible by
the code cleanups in #1284.
Now, we ensure that the file has been processed by the database before
attempting to re-display the buffer.
Fixes #1297
> (fix): do not display buffer if it is not processed in db

- CHANGELOG.md
- org-roam-db.el
- org-roam.el
The rename file advice is passed relative file names: e.g. "foo.org" ->
"bar.org". This was not accounted for, and paths in the Org-roam
database are supposed to be absolute paths. This caused the storing of
relative paths in the Org-roam database, which were then never purged.
Fixes #1304
> (fix): fix rename file corrupting database

- org-roam-dailies.el
1. Remove calls to `file-truename`, fixing #1293
2. cleanup `find-next-note`
> (fix): dailies: misc fixes

- org-roam.el
> (fix): fix rename not triggered if new title contains old title

- org-roam-dailies.el
`*-capture` commands now maintain window configuration, while the
`*-find` commands change to the file.
> (fix): dailies: fix capture changing window configuration

- org-roam-macs.el
This fixes calls like (org-roam--with-temp-buffer nil ...). 
Fixes #1310, fixes #1316.
> (fix): don't set default-directory if no file is passed

- org-roam.el
Readd the buffer-local hooks to Org-roam buffers upon retoggling
Org-roam mode.
Fixes #1305
> (fix): fix mode toggle not re-enabling buffer-local hooks

- CHANGELOG.md
- org-roam.el
Remove duplicates from title and tag extraction, arising from
multiple (or the same) sources.
Fixes #1324
> (fix): uniqify title and tag extraction

- org-roam-capture.el
The `org-roam-capture-find-or-create-olp` function will throw the same
error, so we don't have to explicitly catch and throw.
> (internal): remove error-checking for olp

- doc/org-roam.org
> org-roam.org: fix link to org-capture

- doc/org-roam.org
The documentation said that C-u M-x org-roam-doctor checked the current file.
> Note that C-u M-X org-roam-doctor checks all files

- org-roam-link.el
- org-roam-macs.el
- org-roam.el
functions `org-roam--update-links-on-title-change`, `org-roam--rename-file-advice`, `org-roam-link--get-id-from-headline`, and ` rg-roam-link--get-headlines` don't close files after modifying them if they weren't already open.
there has been a long standing issue with org-roam where some operations leave files open when they shouldn't.
This PR ameliorates the issue.
refer to  #1171
> (fix): close files intelligently after modifying.

- CHANGELOG.md
- org-roam-link.el
Before, `[[roam:Abc][def]]` would be replaced with `[[file:abc.org][Abc]]`; the existing description "def" is replaced with the description fetched from abc.org.
This change makes it so that the existing description will be preserved:
- `[[roam:Abc][def]]` → `[[file:path/to/abc.org][def]]`
- `[[roam:Abc]]` → `[[file:path/to/abc.org][Abc]]`
This is useful for attaching links to existing text.
A word on retrieving the existing description: `org-element-link-parser` doesn't return the description itself, relying on the caller to be in the same buffer and retrieve with `buffer-substring-no-properties` themself. This is fine in `org-roam-link-replace-all`, where current buffer is known, but in `org-roam-link-follow-link` we're relying on Org not changing `current-buffer` during the link …
> (fix): preserve existing description in a roam: link on replace

- org-roam-buffer.el
This pr enables updating the org-roam buffer manually. It is useful when org-roam doesn't update the org-roam backlink buffer but new information is available.
> (feat): make buffer update interactive.

- org-roam.el
> (docs): fix docstring for org-roam--get-title-path-completions

- CHANGELOG.md
- org-roam.el
When `org-roam-directory` doesn't end with trailing slash and
`org-roam-index-file` contains relative filename, absolute path
to org-roam index file returned by `org-roam--get-index-path` is
malformed and invalid.
This commit removes redundant string concatenation and leverages
`expand-file-name` ability to construct valid absolute file path
when it is provided with directory as its 2nd argument.
> (fix): index file: prevent malformed absolute path

- CHANGELOG.md
- org-roam-capture.el
- org-roam-protocol.el
Previously we had set `org-capture-link-is-already-stored` to `t` in
org-roam captures, because org-roam-protocol stores links. This
prevented regular captures from utilizing the %a element in the
templates.
Instead, only set `org-capture-link-is-already-stored` in the
org-roam-protocol capture command.
Fixes #1341.
> (fix): allow link captures

- doc/org-roam.org
- doc/org-roam.texi
Follow on to #1345.
The discussion in the Slack thread further clarified what was exactly
confusing for a beginner reader of this Getting Started. When a user is using
the built-in completion (no ivy, no ido), then `org-roam-find-file` does not
immediately show any files -- instead, the user has to press TAB. This is not
explicitly mentioned.
https://orgroam.slack.com/archives/CV160S8EL/p1608121018061700?thread_ts=1608039505.055000&cid=CV160S8EL
@jethrokuan , you might consider this to be too much of a detail for User Manual -- it could be distracting more experienced user. It could be a candidate for more beginner-oriented tutorial, rather than User Manual. Another view would be that it is in the Getting Started, so a little more of explanation for beginner users might be appropriate.
In …
> (doc): Add footnote for Getting Started

- CHANGELOG.md
- org-roam.el
Prefer lower-case version of Org properties. Fixed bug where
adding/deleting props will alter the original case of the Org property.
Addresses #1342, and supercedes #1312
> (fix): set-global-prop: prefer lowercase

- CHANGELOG.md
- org-roam-macs.el
- org-roam.el
Add support for file-property drawers in property extraction. This means
the following is now supported:
:PROPERTIES:
:ROAM_ALIAS: alias
:ROAM_TAGS: tag1 tag2
:END:
Closes #1185, #1296
> (feat): Support file-property drawers

- org-roam.el
So that, like org-store-link, the computed description does not
contain the links that were captured.
> Use org-link-display-format in org-roam-insert

- org-roam-dailies.el
If the user creates a new daily via `org-roam-dailies-find-today`, they
will get a new buffer that hasn't yet been saved to disk. If they then try
to navigate to the previous daily via
`org-roam-dailies-find-previous-note`, they will get the error:
`Wrong type argument: number-or-marker-p, nil`
This is because the value of the local variable `position` is set only if
the current buffer exists as a file in the dailies directory. It doesn't
until the user explicitly saves it.
That's not a big problem, but the solution is not obvious from the error
message. I added a check that will provide the user with a more informative
error message, so they know how to fix the issue:
"Can't find current note file - have you saved it yet?"
> Add useful warning message to org-roam-dailies-find-next-note

- CHANGELOG.md
- org-roam-link.el
- org-roam-macs.el
updates org-roam-with-file to accept nil FILE arg, to operate on current
buffer. Fixes org-roam-link--get-headlines to kill buffer if not
obtaining markers.
Fixes #1373
----
> (fix): fix headline completions erroring

- org-roam.el
changing filename when title of file changes drops id links. This PR fixes that by reordering operations
to allow files-affected access to the new file's id before links within them are extracted and placed in database.
> (fix): keep id backlinks on filename change

- CHANGELOG.md
- org-roam-capture.el
- org-roam-protocol.el
- org-roam.el
We need to split the ref into its type/file before querying the db for a
match. Throw a warning when `org-roam--capture-new-file` tries to
recreate an existing file.
Fixes #1371
> (fix): fix org-roam-protocol--open-ref creating new files

- org-roam-buffer.el
This lets a user have a function decide, using run-time values, what
position the org-roam-buffer is placed in.
I frequently use both wide screens and tall screens, and want to have the org-roam buffer in different positions depending on the size of the frame it's opened in.  This provides for that, and does so in what I hope is a fairly simple manner.
> Allow `org-roam-buffer-position` to be a function

- doc/org-roam.org
- doc/org-roam.texi
The API for Homebrew Cask changed (https://brew.sh/)
> (doc) Update brew install script

- org-roam-buffer.el
- org-roam.el
Instead of storing preview content in the database, now provide a
function to fetch these on the fly. This paves the way for future
improvements (e.g. showing more lines)
> (feat): add org-roam-buffer-preview-function

- doc/org-roam.org
- doc/org-roam.texi
use native script editor, rather than Platypus.
ref #1372, closes #1372
> (doc): update mac protocol instructions

- doc/org-roam.org
- doc/org-roam.texi
Makes clear the difference between org-roam-find-file and org-roam-capture.  Closes #1391
> Clarify behavior of capture functions

- CHANGELOG.md
- org-roam-doctor.el
- org-roam.el
- tests/test-org-roam.el
Fixes #1403
Right noow we have an inconsistency between how we write and read props like tags and aliases. I might be missing the rasons for using `org-roam--str-to-list`, but it seems that it's purpose was to just handle not balanced quotation marks `"`. If my understand is correct, I think we should use `split-string-and-unquote` (opposite to `combine-and-quote-strings` that we are using for writing props). It has simple implementation and there is no need to convert between other types to string.
But again, I might be missing something.
```
ELISP> (split-string-and-unquote "hello my friends")
("hello" "my" "friends")
ELISP> (split-string-and-unquote "hello \"my friends")
*** Eval error ***  End of file during parsing
ELISP> (split-string-and-unquote "hello \"my\" friends")
("hello" …
```
> (fix) inconsistency between props writing and reading (alias, tags)

- org-roam.el
Followup from #1404
Found by https://github.com/d12frosted/vulpea/runs/1767274279?check_suite_focus=true
I will check later why `org-roam` tests didn't fail 🤔 
I applied these two changes locally and `vulpea` tests are passing now.
> (fix) parsing of missing props

- CHANGELOG.md
- org-roam-dailies.el
> (fix): dailies: prevent inclusion of non-org-roam files

- org-roam-dailies.el
I noticed that org-roam-dailies-capture-templates assumes that org-roam-dailies-directory has its default value, but if the latter has been tweaked, then the templates are wrong.  This should fix it so long as the user sets the variable before org-roam.el is loaded (as I believe will happen if the variable has been customized).
> (fix): dailies: avoid assuming value of org-roam-dailies-directory

- org-roam-node.el
- org-roam-utils.el
- Org-ref is hacking local variables in a very unexpected place that
leads to breaking the backlinks sections in org-roam-buffer. Prevent it
from doing that.
- silence byte compiler in several places
> (fix) workaround for cite backlinks crashing

- org-roam.el
The purpose of this patch is follows:
1. Instead of removing all `Mn` (Non-spacing mark) letters, trim only the [diacritical characters](https://en.wikipedia.org/wiki/Diacritic) for the [Latin script](https://en.wikipedia.org/wiki/Latin-script_alphabet).
2. After trimming the file name, normalize it again as NFC.
This patch is functionally compatible for users of English and European languages. This is an important improvement for Korean and Japanese users to use org-roam in their native language.
Fixes #1423
The `Mn` category contains not only the Latin script (also known as the Roman alphabet) for European languages, but also the combining characters for so many languages. (See [List of Unicode Characters of Category “Nonspacing Mark”](https://www.compart.com/en/unicode/category/Mn)) …
> Optimize filename normalize

- org-roam-link.el
Fixes  #1472
Headlines that includes links to others should be handled properly.
> (feat) Make roam headline link completion robust #1472

- README.md
- doc/org-roam.org
- doc/org-roam.texi
Refer this debuging Slack exchange:
https://orgroam.slack.com/archives/CV160S8EL/p1619089118195300
Not using `file-truename` to set
`org-roam-directory` can lead to an issue that is
hard to identify.
It appears that cache database may updates with
files but `org-roam-buffer` fails to find the file
as symbolic links do not resolve. This is
confusing as the table query to the table seems to
return what appears to be correct entries, but the
backlink fails to insert context around the
link (as Org-roam fails to find the file).
There have been similiar issues -- by making sure
`file-truename` is added in the documentation and
README, it is hoped to eliminate such issues to
recur.
This is probably relevant for V2 as well.
> (doc): Add file-truename to set org-roam-directory (README and documentation)

- org-roam-db.el
[copying the commit comment here]
In my case of testing with 8253 zettels (available on request if
anyone wants to test with them), this improves cleanup speed by 6x
and update speed by 2x.
Improvements will be smaller for smaller batches as this really just
removes the transaction overhead.
> speed up org-roam-db-sync by wrapping db activity in a transaction

- org-roam-mode.el
- org-roam.el
Haven't benchmarked (the areas I changed did not seem to warrant it), but mapconcat should be slightly more performant than string-join, as it's implemented in C. Also a little cleaner than the `(string-join (mapcar ...` idiom.
> Prefer mapconcat over string-join

- org-roam-doctor.el
`save-buffer` does not take a buffer as an argument, it always acts on the current buffer. So save was not actually taking place. This fixes that issue.
> Fix auto-save buffer in org-roam-doctor

- org-roam.el
It should match by title instead of id and the left join is not needed
here as data is not used in any case.
> (fix) fix aliases lookup in org-roam-node-from-title-or-alias

- org-roam-capture.el
Remove quotes before heading lists in olp examples, they do not belong
there. Quoting these lists will lead to an error.
The docstring provides an incorrect example
> update org-roam-capture-tempates docstring

- CHANGELOG.md
- org-roam-graph.el
I wanted to print the graphs that are generated on multiple sheets of paper, since they were getting too large for a single sheet. I learned that one easy way to do this is to create a PDF, and then use a program like Acrobat Reader that can 'posterize' your document by printing it over n x m pages. 
Then I noticed that "svg" was hard-coded in this file, so I thought it made sense to be a customizable variable. Only 2 lines of code needed to be changed, and 6 added, to affect this change. 
The issue I'd previously posted about this:  https://github.com/org-roam/org-roam/issues/1510
The discussion on Discourse: https://org-roam.discourse.group/t/allow-graph-output-filetype-to-be-configurable-currently-svg-is-hardcoded/1552/5
> Custom graph filetype

- org-roam-capture.el
Fix regression introduced in 7ed51329.
The function should return an ID.
> fix org-roam-capture--goto-location

- org-roam.el
This is a follow up of #1420/ for v2.
Basically:
1. Allow to pass a tag/alias/ref to remove.
2. Return removed tag/alias/ref.
3. Return added tag/alias/ref to mirror (2).
> (feat) allow to specify props to remove and return them

- org-roam.el
`string-blank-p` returns a non-nil value if the string is blank, and
nil (which you can't compare to 0) otherwise.
> (fix) setting non-blank keyword value

- org-roam-capture.el
- org-roam-db.el
- org-roam-faces.el
- org-roam-link.el
- org-roam.el
`org-roam-title-change-hook` conks out when links are added to an unsaved buffer.
Reproducible steps:
1. Go to an existing note `foo`
2. `org-roam-insert` → Create a new file `bar`
3. Validate the capture; notice that the link was added in `foo`, but the the buffer was not saved.
4. Go to `bar`
5. Rename the note to `baz` (via the title)
6. Link in `foo` is not updated
This is because we're retrieving `files-affected` from the db:
https://github.com/org-roam/org-roam/blob/89944230798e4a63b8ce5c345ac22c337414b734/org-roam.el#L1425
The db is updated prior to that, but it only includes what was saved:
https://github.com/org-roam/org-roam/blob/02e35e3b01914a0dceb39a116a978f523d5f4272/org-roam.el#L1436
I've elected to save the modified org-roam buffers prior to updating the db: …
> Save before link updates when renaming notes

- org-roam.el
Set `org-file-tags` before pulling tags from buffer. Should fix the
'vanilla option in `org-roam-tag-sources`
> (fix): tags: fix vanilla option

- org-roam-db.el
Behave more gracefully when ID conflicts are encountered when syncing org-roam files to the database.
Current behavior is to print "UNIQUE constraint failed: nodes.id" in the minibuffer and abort.
Proposed behavior: Do not abort. 
Log the offending entry details (ID, entry title, filename) to the *Warnings* buffer, and continue.
> More graceful handling of ID conflicts #1480

- org-roam-capture.el
Unless `:immediate-finish` is non-nil, capture process is asynchronous, meaning that there is no way to do something AFTER the note is created. There is `org-roam-capture-new-node-hook`, but it's being called to early, during the capture process and the hook is not easy to configure for one specific capture.
So `org-roam` could provide a finalization hook in addition to `org-capture-after-finalize-hook`, but I still love the idea to be able to configure finalization per capture.
> (feat) allow to provide custom finalize functions

- org-roam-capture.el
Sometimes it is useful to provide not only the title of captured node,
but an ID:
```emacs-lisp
(org-roam-capture-
:node (org-roam-node-create
:id some-id
:title some-title))
```
> (feat) allow to override node id during capture

- org-roam-db.el
1. Add an alias to a headline node by `org-roam-alias-add`
2. Save the buffer with `debug-on-error` enabled
=> error "table aliases has 2 columns but 3 values were supplied"
> fix org-roam-db-insert-aliases

- org-roam-capture.el
Unless `:region` is part of this list, it's the value is not put into
the context using `org-roam-capture--put` making it inaccessible via
`org-roam-capture--get`, meaning that, for example,
`org-roam-node-insert` doesn't replace selected region, but instead
simply appends a link to selected region, which is not desired
intention.
> (fix) add :region to capture keywords

- org-roam.el
Seems like I love to cause issues in this repository. I am sorry! 
Fix looks ugly, there might be a better solution (e.g. by having optional/nil-able values). This just to stop the bleeding :) 
See https://github.com/org-roam/org-roam/pull/1536#issuecomment-851036487 for explanation. Found in https://github.com/d12frosted/vulpea/runs/2705470297.
> (fix) allow to insert with no active region

- org-roam.el
I wanted to use the filter-fn functionality in `org-roam-node-find` to limit the node search to only the top-level files. However, I was unable to do so, because the level of the nodes loaded using `org-roam-node--completions` was set to nil. This fixes this, which should allow filtering based on the level of the node.
> Load node level from database when reading all nodes

- org-roam-refile.el
[org-roam-node-read](https://github.com/org-roam/org-roam/blob/304749a10003629c810fd00bf21f22d4237fc484/org-roam.el#L715) updated signature is incompatible with the way `org-roam-refile` calls it
Calling `org-roam-refile` produces an error: `sort: Symbol’s function definition is void: require-match`
> org-roam-refile: Update call to "org-roam-node-read" to fit updated signature

- org-roam-refile.el
- org-roam-utils.el
org-roam-refile should treat an entire file as a node if it is invoked at the top level (above any heading).
> V2 refile from top level 

- CHANGELOG.md
- org-roam.el
When `org-roam-list-files-commands` is nil and `org-roam--list-files-elisp` is used to list files, files excluded via `org-roam-file-exclude-regexp` still show up.
When using `rg` or `find` this doesn't happen, as `org-roam--list-files` filters their results with `org-roam--org-roam-file-p`.
> (fix): files not excluded when org-roam-list-files-commands is nil

- CHANGELOG.md
- org-roam.el
- tests/roam-files/tags/tag.org
- tests/roam-files/titles/aliases.org
- tests/test-org-roam.el
This brings them more in line with how other Org keywords, such as `#+PROPERTY`, are declared.
Previously
#+roam_alias: abc def
#+roam_alias: ghi
would result in only the last one ("ghi") being extracted. This PR makes it so that `("abc" "def" "ghi")` are all extracted.
* org-roam.el
- (org-roam--extract-tags-prop, org-roam--extract-titles-alias): Accept and return all values in a list, not just from one line.
- (org-roam--extract-prop-as-list): New function. List prop extraction refactored from `org-roam--extract-tags-prop` and `org-roam--extract-titles-alias`
* tests/test-org-roam.el: Add tests for defining tags and aliases in multiple lines
> Allow setting #+roam_alias and #+roam_tag on multiple lines

- org-roam-graph.el
Just remove an extra parentesis.
> (fix) Remove extra parentesis

- org-roam-capture.el
- org-roam-dailies.el
This commit fixes the currently invalid definitions of the customization types.
The current error can be reproduced by:
1. Running `org-roam-setup`
2. Starting `M-x customize`
3. Searching for "org-roam"
The error (truncated) should look like this:
``` emacs-lisp
Debugger entered--Lisp error: (wrong-type-argument listp "Headline")
widget-convert("Headline")
mapcar(widget-convert (string :tag "Headline"))
widget-types-convert-widget((repeat :args (string :tag "Headline")))
widget-convert((repeat string :tag "Headline"))
mapcar(widget-convert ((repeat string :tag "Headline")))
widget-types-convert-widget((list :tag "Outline path" :args ((repeat string :tag "Headline"))))
widget-convert((list :tag "Outline path" (repeat string :tag "Headline")))
...
```
> (fix): Fix invalid cutomization types

- org-roam-refile.el
Need to use internal naming ;)
> (fix): fix void variable `org-roam-kill-empty-buffer`

- org-roam.el
As already two issues addressing the "problem" of displaying nodes in the minibuffer (#1553 #1530), I found it necessary to clarify the documentation.
> Clarify 'org-roam-node-display-template' documentation

- org-roam-graph.el
Previously, when the command would be called with `universal-argument` it would simply fall through, without running any code and hence, not generating a node-local graph. This is because the command didn't account correctly all possible value of ARG, where with `universal-argument` it becomes a list of one element, which is an integer.
I've also refactored the command to handle non-interactive usage and to better trace values when debugging it.
> Fix `org-roam-graph` command when used with `universal-argument`

- org-roam.el
See https://github.com/org-roam/org-roam/commit/a199886ef7ae208b0b10dc45e0df9b54d210cd4d#r52949692
P.S. I checked this query only outside of `org-roam`. And it worked :) But more real testing would be useful.
> (fix) SQL for querying notes with tags, aliases and refs

- org-roam.el
> (dev) remove irrelevant note about refs missing their type

- org-roam-db.el
- org-roam.el
- Use `add-hook` instead of `add-to-list` to set hooks
- Setup automatic replace of `roam:` links buffer-locally, instead of doing so globally.
> Refactor some hooks for a better overall hygiene

- org-roam-mode.el
First call to `org-roam-buffer-toggle` would display the buffer empty, forcing to switch back to the note buffer to see any backlinks. Just swapping lines to set the current node while we're still in the note buffer, and then display the roam buffer.
> Display roam buffer after setting current node

- org-roam-dailies.el
- org-roam-db.el
- org-roam-migrate.el
- org-roam.el
So the user wouldn't have the need declare them on their own side if they want to lazy load the package.
> Add autoload cookies for missing global entry points

- org-roam.el
Fix inconsistency for filter-fn in ref and node functions, and update
docstrings to be consistent.
> (fix): update filter-fn docstring

- doc/org-roam.org
- doc/org-roam.texi
In the Post-Installation Tasks section, I suggest to add a sub-section for the C
compiler requirement for emacsql-sqlite. I have put an explanation for Windows
-- I have tried to make it as succinct as I can without losing some fine points
that I believe important for users to avoid confusion.
I have just removed MSYS2 and the PATH on my Windows machine and repeated the
process as I described it here to confirm that it works.
Since this new part is distinct from the existing paragraphs for SQLite, I also
suggest a sub-section heading for them -- I used "SQLite" as its title.
Please feel free to change any part as you see fit.
It might be also useful if macOS users added their parts. I believe XCode is the
easiest way to install a C compiler (I believe it would be clang for recent
XCode …
> (doc): Add section for C Compiler

- doc/org-roam.org
- doc/org-roam.texi
Just adding a note on encrypting the org-roam db itself.
Closes #835
> (docs): add note on encryption

- doc/org-roam.org
> (docs) Replace mention of org-roam-db-build-cache with org-roam-db-sync

- doc/org-roam.org
- doc/org-roam.texi
- Fixed the original example's extra parenthesis, which broke the alist.
- Added a second example for configuring the buffer as a side window.
When migrating to v2 I found that the configuration example for the backlinks buffer (both in the wiki and official documentation) had an extra parenthesis, which would work if `setq` was being used instead of `add-to-list`.
This pull request fixes the original example and adds a second example for using the buffer as a side window.
> Adjusted configuration examples for backlinks buffer.

- doc/org-roam.org
- doc/org-roam.texi
I believe `org-roam-mode-section` should be `org-roam-mode-section-functions`.
> Doc typo: org-roam-mode-sections -> org-roam-mode-section-functions

- org-roam-mode.el
Non-ASCII characters are displayed incorrectly because `org-roam-unlinked-references-preview-line` uses `insert-file-contents-literally` which ignores the encoding.
Use `insert-file-contents` which does the right thing.
fixes #1575
> fix(#1575): fix display of non-ASCII in unlinked references section

- doc/org-roam.org
- doc/org-roam.texi
Update documentation for installing from source to mention `magit` as a dependency.
Chatted with @nobiot in Slack #troubleshooting @ https://orgroam.slack.com/archives/CV160S8EL/p1626627482212700
> Mention magit-section as dependency in install from source

- doc/org-roam.org
- doc/org-roam.texi
Apt installation is only valid for Org-roam v1. To be re-added when
Debian updates their repos. Closes #1631.
> (docs): remove apt installation

- org-roam-migrate.el
Mention the requirement to set org-roam-directory before running the
migration wizard. Closes #1624.
> (migration): mention org-roam-directory

- org-roam.el
org-roam-file-p throws `wrong-type-argument stringp nil` on buffers that
do not have a corresponding file. This fix changes org-roam-file-p to
return nil instead of crashing in this scenario.
Addresses #1645
> (fix): fix org-roam-file-p crashing

- org-roam-migrate.el
- prevent botching of existing filetags
- insert new tag list using `org-make-tag-string` (colon-delimited) for resilience
Fixes #1642.
> (fix)tags: fix tags migration

- org-roam.el
Preview is now smarter in a few ways:
1. If it the link is at a headline, it shows the headline's content
instead of just repeating the headline
2. If the link is a bullet item in the plain-list, show the full list instead
Addresses #1005
> (feat)preview: improve org-roam link preview

- doc/org-roam.org
- doc/org-roam.texi
- org-roam-compat.el
- org-roam-mode.el
- org-roam.el
Replaces the `org-roam-buffer` command and formalizes the concept of node dedicated Org-roam buffers (compared to the persistent one). I'm not sure about the name, so if you have a better one let me know.
> (feat): formalize node dedicated buffers

- org-roam-migrate.el
`org-roam-migrate-v1-to-v2` requires the v2 db to already be in place,
so run `org-roam-db-sync` once first.
Fixes #1664
> (fix)migration: upgrade db to v2 before conversion

- doc/org-roam.org
- doc/org-roam.texi
Address a common question about Org-roam creating IDs
closes #1531
> (docs): add org-id-link-to-org-use-id to FAQ

- org-roam-utils.el
> (fix) org-roam-get-keyword: fix for cjk characters

- org-roam-capture.el
The previous fix[0] for capture targets did the right thing. However, it didn't account that `org-roam-capture--get-point` branches to 3 different paths, where each of them set the point to a different location, and the fix only addressed the branch in which `org-roam-capture--goto-location` would run.
This commit adjusts the point for all other branches, which fixes a problem where you would try to run capture to existing node with something like `org-roam-capture` and it wouldn't set the point to the right location; same with ref capturing through the `org-roam-protocol`.
I think this was the last missing piece to fully fix capturing (when it comes to correctly positioning the point), that I simply somehow didn't previously noticed.
[0]: …
> (fix)capture: Adjust the point for capture targets in missing places

- org-roam.el
> (fix)preview: fix link preview when headline contains link

- org-roam-capture.el
- org-roam-dailies.el
- org-roam-db.el
- org-roam-graph.el
- org-roam-migrate.el
- org-roam-mode.el
- org-roam-utils.el
At the current state autoloads from non `org-roam.el` unable to start
loading of the package from their own file. See the following to learn
more about the problem:
https://github.com/org-roam/org-roam/issues/1590#issuecomment-885817825
This is no more than a workaround to bandage a more deeper underlying
problem. Until the more fundamental problem won't be fixed, all autoload
cookies from non "org-roam.el" file will need to manually point to the
main entry point of the package -- "org-roam.el" file, to load it
without causing errors.
Fixes #1590, fixes #1620, #1600 and other similar issues.
Hey @jethrokuan, since you didn't response to my comment I don't really know what's your plan to move forward with this problem. Meanwhile, I don't think the status quo (with regards to the issue) is …
> (fix)autoloads: Point autoloads to org-roam.el file

- org-roam-capture.el
- org-roam.el
The rationale for this change is to allow context-specific capture
consideration.  That is to say, in my experience, when I'm working on a
project, I often want to scope my note finding and creation to that
project.  By adding `filter-fn` and `templates` I can easily craft
context-aware functions for my note-taking.
I chose to switch these to `cl-defun` to expose `&key` parameters, which I
find more useful as the method signature grows.
Closes #1681
From the Github Issue:
> Adding a `filter-fn` parameter to `org-roam-capture` and a `templates`
> parameter to `org-roam-capture` , `org-roam-node-insert`,
> `org-roam-node-find` would improve their general utility, and reduce
> fiddling with the more inner functionality of `org-roam-capture-` and
> `org-roam-node-read`
> Adding parameters to three core functions

- org-roam-capture.el
Allow 'ignore as a valid value in place of function. Closes #1699.
> (feat): allow special 'ignore key in capture template

- org-roam.el
Fixes https://github.com/org-roam/org-roam/issues/1640.
I'm not convinced this is the right fix for this issue because it is not solving the underlying problem of helm not respecting text properties, but it does fix the immediate problem of the default configuration of org-roam sometimes causing multiline completion candidates.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> (fix): remove invisible tag

- org-roam.el
Previously if a top-level file node is excluded, it would still be
picked up by org-roam-id-at-point. This adds another org-roam-db-node-p
check before returning an ID, fixing the broken behaviour. Fixes #1635.
> (fix)org-roam-id-at-point: ignore top-level excluded nodes

- CHANGELOG.md
- org-roam.el
Current, when fetching file level org tags (from the `#+filetags` property), multiple tags are split based on the default `split-string` separator. This is incorrect because the org documentation says that multiple file-level tags should be separated by `:` (like headline level tags). This results in a improper splitting (aka no split) of the tag string into multiple tags. This leads to the inability to delete tags that are there.
Similarly, when writing multiple `#+filetags`, the tags are joined by `" "` instead instead of `":"` as mentioned in the org docs. This leads to improperly added tags where newly added tags would not be recognized by org.
This PR fixes both problems, parsing is done by string splitting on `":"` (with the `OMIT-NULLS` parameter set to true so you don't get a null …
> fix: splitting and joining of multiple filetags

- org-roam-capture.el
Redefine a new file to Org-roam's capture system as one that does not
have a buffer visiting it yet. This means that if a buffer is already
visiting the file, then the HEAD template will not be inserted. This is
important because Org-roam capture does not enforce the save of files,
and this can lead to scenarios where the template is inserted multiple
times to a buffer for a file that has not yet been written to disk.
> (fix)capture: check for buffer existence before template insertion

- org-roam-capture.el
- org-roam-utils.el
- org-roam.el
Allow specification of default values in org-roam-format of the form ${key=default_val}. Closes #1003.
> (feat)org-roam-format: add default-value

- org-roam.el
Adds org-roam-extract-subtree, which converts the subtree at point
into a top-level file node. This is useful for when a node you are
expanding on gets too big, and deserves its own file.
Closes #1104
> (feat): add org-roam-extract-subtree

- org-roam-capture.el
According to the documentation of `org-roam-capture--info` and functions working with that variable, it is a property list and not an alist, so that should be stated correctly in the documentation for the `INFO` keyword argument.
Sorry for the minor PR, just found this while stepping through the code with edebug and looking at function signatures while trying to find the cause for another bug that I have.
> Correct type for INFO argument in org-roam-capture docstring

- org-roam-capture.el
We now check for either an unsaved buffer visiting the file path, or
the unvisited file on disk.
#1707 replaced checking if a file exists on disk with checking if a buffer is visiting it.
This PR combines both tests, so it is regarded as existing if either it is being visited in a buffer but is still unsaved, or is unvisited on disk.
See https://github.com/org-roam/org-roam/pull/1707#issuecomment-889415643
> When capturing a file, check if it exists on disk too

- org-roam-compat.el
Prefer Org's org-collect-keywords over org-roam-get-keyword. This
function is not used anywhere, but perhaps some people's configurations
depend on it, so it will be left as is for now.
> (minor)org-roam-get-keyword: make-obsolete

- doc/org-roam.org
- doc/org-roam.texi
- org-roam-db.el
- org-roam.el
Adds new variable org-roam-db-update-on-save, which when set to nil,
will disable db updates on file save. Closes #1717.
> (feat)db: add org-roam-db-update-on-save

- doc/org-roam.org
- doc/org-roam.texi
> (docs)capture: document default-val syntax and available expansions

- org-roam-db.el
A force resync of the database does not work in Windows (Cygwin):
apply: Removing old name: Device or resource busy, /home/brschoen/.emacs.d/org-roam.db
Therefore, close the connection first and then try to remove the database file.
> Force sync: close the database before removal

- org-roam-utils.el
Just a formatting issue I came across while figuring out a `org-roam-format` issue.
> (minor)org-roam-format: Fix code formatting

- doc/org-roam.org
Prefer headline links in docs, because internal id linking can cause
issues in documentation building. Closes #1749.
> (docs): Remove internal ID linking

- org-roam-capture.el
- org-roam-node.el
In adding this parameter, the external facing methods expose another
point of parameterization for the inner `org-roam-capture-` method.
This is most useful for the `org-roam-node-insert` method which has a
complicated inner logic; By adding the `:info` `&key` parameter, we
reduce the likelyhood of needing to duplicate that inner logic.
This relates to work done for #1693.
Closes #1740
> Adding :info &key to org-roam-(capture|node-insert)

- org-roam-db.el
When inserting the GPG decrypted org buffer to to DB, make sure that
the hash of the encrypted file is stored.
This prevents reparsing of GPG files over and over again when
synchronizing the database with the filesystem.
I use GPG encrypted org files and was wondering why every time I started Emacs, all GPG files were parsed again, even though they were not modified.
> (fix)org-roam-db--file-hash: Always compute hash of encrypted file

- org-roam-node.el
Preserve descriptions (if any) when replacing `roam:` links. Fixes #1737.
> (fix)replace-link-at-point: preserve description

- org-roam-node.el
When strings in org-roam-node-display-template are truncated, they are
no longer searchable using completions, resulting in suprising
behaviour. This change allows truncated strings to still be searched
according to their original value. Closes #1728.
> (fix)completions: use full string

- org-roam-node.el
Recent changes to how candidates are formatted (using a display property
to allow for searching in the full candidate while only showing enough
to fit in the frame), #1754, causes problems when the field value is already
preformatted (a user function, like the one provided in doom emacs,
already applies some faces with `propertize`). Generally the display
string get messed up and formatting gets applied to the whole display.
This PR updates the `propertize` call that adds the display property to the candidate
to remove all properties from the candidate before the styled (and
truncated) display string is added as a property. This allows the
display string to look correct according to the properties a user has
already assigned.
This PR also fixes another bug from this change, where if a …
> Fix candidate display.

- README.md
- doc/org-roam.org
- doc/org-roam.texi
- org-roam-compat.el
- org-roam-db.el
- org-roam.el
- tests/test-org-roam.el
Comply with the principle of least astonishment, where in Emacs having a global minor mode for this purpose would be the most expected thing to have.
> (feat): replace `org-roam-{setup,teardown}` with `org-roam-db-autosync-mode`

- org-roam-compat.el
- org-roam-node.el
This is the source of the errors reported in #1734, #1700, #1688. Ideally this problem should be handled by `org-id` itself, but for now this will be only patched in Org-roam.
Merging this fixes #1700 and fixes #1638.
> (fix)org-id: gracefully handle absence of `org-id-locations-file`

- org-roam-node.el
It lies in between org-in-regexp and replace-match. In some situations, like
when the link looks like roam:a s'b, it changes the match-data.
Get file file [test.txt](https://github.com/org-roam/org-roam/files/6975458/test.txt)
It is an elisp file, but github won't allow the extension .el...
It
- installs org-roam, 
- sets up a roam directory
- adds two files,
- one with title "a s'b"
- one with title "other" in it the content `[[roam:a s'b]]`
- run `org-roam-link-replace-all`
This simulates the behavior when you create a note and use the completion mecanism to add a link to another note.
Run this with emacs -Q --load test.txt, you will get the following error
`org-roam-link-replace-at-point: Args out of range: 0, 0`
Try removing the "'" character, so that the first file has the title "a …
> Make sure org-roam-node-from-title-or-alias won't mess up with the match-data

- org-roam-node.el
This allows the empty field-width to be used, but using an empty
field-width will result in misalignment. This is useful for people who
use completion frameworks like Ido.
> (fix)completions: allow empty field-width

- extensions/org-roam-graph.el
When a node links to the another node twice, two edges appear in the
graph. To keep the graph clean, remove all duplicate edges.
> Remove duplicate edges from graphs

- CHANGELOG.md
- org-roam-node.el
I'm using `org-roam-node-at-point` to fetch the title of the node when building the agenda. Not all my agenda-items are roam-nodes themself and I want to have access to the title of the parent node. However depending on whether the heading tree is visible or collapsed I'm getting different result. Turns out it's just a matter of `org-back-to-heading-or-point-min` which needed `invisible-ok` argument.
Example of the file that show different results depending on visibility
```
:PROPERTIES:
:ID:       dfe77ff7-7e27-4fdd-ad7c-ffd6aadc87bd
:END:
#+title: org-roam
#+startup: overview
* test
** inner
:PROPERTIES:
:ID:       4ced70aa-7b8c-41f0-b43e-3554dbbeeb10
:END:
*** item
SCHEDULED: <2021-08-21 Sat>
```
The result is either "inner" or "org-roam" depending on visibility.
> fix: Do not skip invisible headings when getting node at point.

- org-roam-utils.el
- org-roam.el
If org-roam-utils.el is byte-compiled when org-macs is not loaded (`org-with-point-at` macro not available), error can appear about missing `org-with-point-at`
> Require org-macs when compiling org-roam-utils.el

- CHANGELOG.md
- org-roam-db.el
Previously when ROAM_REFS is non-empty, but the refs are invalid, this
will cause an empty SQL expression and crash the db caching. This fixes
that scenario.
> (fix)db: prevent invalid refs from crashing db update

- org-roam-compat.el
It looks like Emacs' byte compiler is very naive and cannot properly
sometimes compile closures, which causes error like in #1814, at least
on Emacsen <28. One of the possible solutions is to write the code using
less abstractions in between, so the byte compiler would do the right
thing when arranging instructions.
Possibly addresses #1814.
> (fix)capture: refactor `org-roam-capture--get-if-new-target-a`

- org-roam-compat.el
- org-roam.el
48a5d017267af was wrong, and the closure wasn't the cause. The source of
the issue stems from a missing compile-time dependency on subr-x.
Emacs 28 doesn't seem to require it for the needed functions anymore,
while older Emacsen still do. What even worse, the byte compiler doesn't
seem to complain about such thing on older Emacsen and the error message
produced at the run-time isn't helpful to identify the cause.
Fixes #1814.
> (fix)compat: resolve all the missing compile-time dependencies

- CHANGELOG.md
- doc/org-roam.org
- doc/org-roam.texi
- org-roam-db.el
- org-roam-mode.el
Support caching the new Org 9.5 citations.
Because citations now has first-class support, and are treated
differently from links, they are now cached in their own table.
Org-ref citations, instead of being stored in the links table, are now
stored in the citations table instead.
To use a citation as a ROAM_REF, use the `@citeKey` syntax.
> (feat) core: support new org-mode citations

- org-roam-node.el
This function ignored the `force' optional argument because it always
quoted it, resulting in a non-nil value every time.
This makes the suggested code snippet in
https://github.com/org-roam/org-roam/issues/597#issuecomment-907743125
work as expected (not resetting point to the beginning of the "Index"
buffer on every invocation).
> org-roam-node-visit: fix typo

- CHANGELOG.md
- org-roam-db.el
This should lead to some performance gains on buffers with lots of
inserts required (e.g. when the buffer has a lot of links).
> (perf)db: wrap update-file in sql transaction

- org-roam-db.el
The current implementation uses `org-element-map` to iterate through all links in the current buffer. This function doesn't consider links within properties drawer. This implementation does consider such links.
This pull request solves #1464 and #1859 .
A minimal working example that proves that `org-element-map` doesn't consider links in properties drawer can be found below.
```lisp
(let ((lines '("* John Doe"
":PROPERTIES:"
":FOO: [[1]]"
":END:"
"[[2]]"
"[[3]]")))
(with-temp-buffer
(org-mode)
(insert (string-join lines "\n"))
(org-element-map (org-element-parse-buffer)
'link
(lambda (link) (org-element-property :raw-link link)))))
```
```
("2" "3")
```
Another solution would be to make a patch for `org-element-map` so that this get fixed in the Org Mode codebase, but I think this would …
> fix(org-roam-db-map-links): Consider link in properties drawers

- org-roam-capture.el
Currently, roam allows file template *nominally*, but, if one tries to set up, it causes trouble.
`goto` functions, like `org-roam-dailies-goto-*`, tries to expand file template with `org-roam-format-template`, which assumes template is string. Hence, complains about it.
This commit suppress such malfunctions by do nothing for non-string template.
Currently, this only affects a handful of quirks, like me, who wanting to exploit file templates for dailies; nevertheless, should work without trouble.
> (fix)capture: ignore file template upon capture goto

- org-roam-node.el
in org-roam-node-read, there is no need to check filter-fn for each node, so move the branch up and just check it once. 
the same logic could be used below, for `sort-fn`, instead of deviating with `setq`
found while debugging, easy fix
> optimize(node): org-roam-node-read: reduce checks on filter-fn, gain O(n) -> O(1)

- CHANGELOG.md
- extensions/org-roam-dailies.el
There is no reason `org-roam-dailies-capture-date` should ask for a time as only a date is necessary.
> fix: dailies: stop asking for time, only date

- org-roam-node.el
The current implementation doesn't cover the scenario where
org-roam-directory doesn't have a trailing slash. Because of this,
users are enforced to make org-roam-directory end with a trailing
slash. If they don't do this, then the value of the prompt that is shown when executing `org-roam-extract-subtree` is
```
Extract node to: ~/org-roam2021_09_25_14_14_03.org
```
instead of (note the slash between the directory name and the file name for the new node.
```
Extract node to: ~/org-roam/2021_09_25_14_14_03.org
``
> fix(org-roam-extract-subtree): Use file-name-as-directory

- org-roam-node.el
Fix `filter-fn` not working like its supposed to.
> fix(org-roam-node-read): fix regression introduced in #1876

- org-roam-db.el
The org-cite library is called [oc.el](https://code.orgmode.org/bzg/org-mode/src/master/lisp/oc.el), not `org-cite.el`.
> (fix)db: Require 'oc to get org-cite functionality.

- org-roam-node.el
This commit simplifies the code in org-roam-node-read--format-entry,
saving the entire processing of display properties when no
field-length is specified and thus no truncation needs to happen.
Since in this case, we don't truncate, the bug fixed in #1759 won't
reappear.
This has the beneficial side-effect that existing display properties
in the field-value, e.g., display properties that replace text by
images/icon, are not overridden by us when no field-length is
specified. Note that images anyway don't need truncation of the text
they replace.
This commit also fixes a wrong word in the comment.
> (refactor)completions: simplify org-roam-node-read--format-entry

- extensions/org-roam-graph.el
This affects the graphviz graph output:
Now https nodes display with the proper styling by default.
> Fix typo in default value of org-roam-graph-node-extra-config

- org-roam-db.el
- org-roam-utils.el
Require optional libraries 'org-ref and 'oc only once per function run:
org-roam-db-update-file and org-roam-db-sync will call these requires at
the top level instead of within the link mapper.
This is an alternative to #1932, but my own profiling on a file with a lot of
links show that this isn't actually the bottleneck.
> (perf)db: require optional libraries only once per function

- org-roam-db.el
Since we're only looking for a specific property, org-entry-get is much
faster. This should speed up link indexing significantly.
Related to #1752.
> (perf)db: prefer org-entry-get over org-entry-properties

- org-roam-db.el
Links within ROAM_REFS are no longer added as links into the database.
This prevents self-referencing. Links within other properties are still
valid.
Closes #1890
> (fix)db: don't consider links in ROAM_REFS as links

- org-roam-node.el
* org-roam-node.el (org-roam-bracket-completion-re): Make final regexp
group non-greedy.
Issue #1790, completions are not working due to incorrect regexp.
> Fix completion issue as described in #1790

- org-roam-db.el
- org-roam-utils.el
As per title cc @nobiot 
I think other uses of `string-equal` are fine.
> (minor)db: make check for property drawers case-insensitive

- org-roam-db.el
Use the file name without extension when no TITLE is specified.
> (minor)db: filename title sans-extension

- org-roam-utils.el
The old implementation
- did not handle duplicate keys well (the function would be applied to each value, but only the first value would be updated with the last value's result):
```
(let ((a (list :a 1 :a 2)))
(org-roam-plist-map! 'list a) a)
;; => (:a (:a 2) :a 2)
;; I expected (:a (:a 1) :a (:a 2))
```
- was quadratic in the length of the input list (for each key, `plist-put` would search for the first occurrence of the key by going through all previous elements again)
- copied the input sequence even though this was not really needed
- did not provide a result value that could be useful, thus encouraging imperative programming
- did not need to be a macro, and the macro implementation was evaluating `fn` multiple times and causing warnings in the native compiler because `k` and `v` …
> Make org-roam-plist-map! more efficient & really modifying in place

- org-roam-capture.el
- org-roam-db.el
- org-roam-mode.el
- org-roam-node.el
- org-roam-utils.el
- org-roam.el
After fixing #1958, there are more compiler warnings remaining, fixed in the first commit of this branch.  Note that
(declare-function org-roam--directory-files-recursively "org-roam-compat")
is a bit of a band-aid: I think (but failed) that the dependency structure of the various parts of org-roam should be reorganised to avoid the circular imports (currently "hidden" by `cl-eval-when` at the end of `org-roam.el`).  Then `org-roam.el` could simply `(require 'org-roam-compat)` at the beginning, if `org-roam-compat.el` could be rewritten not to have to `(require 'org-roam)`.
Apologies for not creating a separate branch for the drive-by fix of the `:group` value of `org-roam-database-connector` but I felt it was not worth it.
> Fix minor warnings by native compiler

- org-roam-node.el
Update org-roam-open-id-at-point to use regexp instead of org-element so
the function works wherever the link is.
Closes #1923.
> (fix)node: fix org-roam-open-id-at-point not working in PROPERTIES drawer

- org-roam-db.el
- org-roam-node.el
The column "filetitle" is populated with the document title or, if
there is none, the basic filename (sans extension) of the file. It is
copied into the org-roam-node when retrieving nodes.
See #1956
> Add column "filetitle" to table "file"; adapt queries to that change

- org-roam-db.el
Apparently, 4a2b44252ef4e71f183f627a49e6ec70c3cf8903 introduced a change that was not intended. The reason why I state this is because in that commit, `org-roam-db-map-links` evaluates `(point-min)` and it does nothing with the returned value. I think that `(goto-char (point-min))` was intended to be evaluated.
> fix(org-roam-db-map-links): goto-char added to point-min

- org-roam-db.el
- org-roam-utils.el
Org-ref v3 introduced a new citation syntax, and removed some functions
that org-roam had previously relied upon (e.g. for extracting keys from
multi-citations).
This commit introduces support on two fronts:
1. Add `org-roam-org-ref-path-to-keys` which converts a link path to a
list of keys. This supports both Org-ref v2 and v3.
2. Adds support for parsing multi-citations in refs.
Addresses #1973.
> (feat)db: support org-ref v3

- org-roam-capture.el
Given that this code
(let ((org-capture-plist (list :org-roam (list :z 26 :z "ignored"))))
(org-roam-capture--get :z))
returns 26, I would expect
(let ((org-capture-plist nil))
(org-roam-capture--put :z 26 :z "ignored")
(org-roam-capture--get :z))
to return 26, too, but it returns "ignored".
This patch fixes it by "reversing" the input list before using `plist-put` on its elements.
> Avoid surprises when STUFF contains the same key twice

- org-roam-utils.el
`org-roam-with-file` should not alter the major-mode if the
mode is already derived from org-mode.
> (fix)utils: fix org-roam-with-file changing the major-mode

- .dir-locals.el
- org-roam-db.el
- org-roam-utils.el
When update-file fails, clear the file from the database and show an
error.
Closes #1978.
> (fix)db: fix org-roam-db-sync exiting early on unhandled errors

- .dir-locals.el
- org-roam-mode.el
- org-roam-utils.el
This commit adds 3 custom variables:
1. org-roam-buffer-postrender-functions
This list of functions are run within the Org-roam buffer after the
Org-roam buffer is rendered. For example, one can produce latex previews
for all content within the Org-roam buffer:
``` emacs-lisp
(add-hook 'org-roam-buffer-postrender-functions
(lambda () (org--latex-preview-region (point-min) (point-max))))
```
2. org-roam-preview-function
This is the function used to extract the content to populate the buffer.
It defaults to `org-roam-preview-default-function`, which extracts all
contents within the headline up to the next headline.
3. org-roam-preview-postprocess-functions
This is a list of functions run to post-process the content retrieved
from org-roam-preview-function. It can be used to strip additional …
> (feat)buffer: add customization variables for buffer

- org-roam-db.el
Plain link in ROAM_REFS is not inserted into the database, which seems an oversight in https://github.com/org-roam/org-roam/pull/1977
> fix: plain link is not inserted into db

- doc/org-roam.org
- doc/org-roam.texi
- extensions/org-roam-graph.el
If a user wants to publish the graph with their notes, they need two things:
- a way to replace the org-protocol links in the generated graph
- the temporary files created so they can get access to them for publishing
PR 1727 can be closed as this is the same change done against the latest code.
> Allow customized graph links and access to the temporary filenames.

- org-roam-node.el
Ensure `org-roam-tag-remove` respects `tags` argument.
> (fix)node: org-roam-tag-remove respects tag argument (#1998)

- doc/org-roam.org
- doc/org-roam.texi
Two items:
1. The current example does not work; in order to call a function wihtin
`.dir-locals.el`, you should use `eval`.
- [StackExchange](https://emacs.stackexchange.com/questions/21955/calling-functions-in-dir-locals-in-emacs)
- [Working example buried in an issue](https://github.com/org-roam/org-roam/issues/1527#issuecomment-933674233)
- `(info "(emacs)Directory Variables")`
2. Add clear instruction to use an absolute path to define `org-roam-directory` in
this context (it's buried in this [issue](https://github.com/org-roam/org-roam/issues/1459#issuecomment-817259656)).
Questions relatd to mulitple Org-roam DB are occasionally posted on Discouse (a [recent example](https://org-roam.discourse.group/t/small-independent-org-roam-instances/2267))
There has been some issues around …
> (docs): fix examples for .dir-locals.el

- doc/org-roam.org
- doc/org-roam.texi
Correcting the example of .dir-locals using an absolute path to avoid confusion.
Lightly tested with a real absolute path in my system; works on my end with a
subdir.
Apologies for not having been more careful in the first time. I hope this PR does not cause any trouble in merging -- it seems to contain all the commits related to this change including the ones that you have already merged...
> (docs) minor correction to #2002

- org-roam-migrate.el
It's been long enough since the v2 release, removing the ack requirement
because it creates an annoying warning on native compilation.
Closes #2003
> (chore): remove org-roam-v2-ack

- org-roam-node.el
I have various capture templates that prompt for a node using `org-roam-node-read` with a filtered down set of nodes (using the handy `filter-fn` argument). This works great. A few of my templates prompt for multiple nodes, and use the selections for different purposes; it would be nice if I didn't have to remember what the order of the prompts was.
The trivial feature makes the prompt configurable, with a default of "Node: " just like this function previously had.
> Make the `org-roam-node-read` prompt configurable

- org-roam-db.el
Previously node caching used org-map-entries: this only mapped over agenda
entries, hence skipping various nodes. Instead, we should be using
org-map-region, which maps over the entire file.
Fixes #1989.
> (fix)db: fix node caching

- org-roam-db.el
Moving the PRAGMA foreign_keys invocation out of the transaction seems
to work now.
> fix(db): fix support for sqlite3 connector

- org-roam-capture.el
`org-roam-capture--fill-template` now returns templates without the newline added from org-capture. Also, now we support org-roam template OLP expansion. 
Supercedes #1828.
> fix(capture): fix whitespacing in org-roam-capture--fill-template

- doc/org-roam.org
- doc/org-roam.texi
PATH needs to be manually set on Windows. Previously, it was explicitly
mentioned that it was unnecessary. More recent experience is that it's necessary.
> docs: Correct how to install gcc on Windows

- org-roam-db.el
Then all advices on `locate-user-emacs-file` will work.
> Use `locate-user-emacs-file` instead of `expand-file-name`.

- doc/org-roam.org
- doc/org-roam.texi
- org-roam-db.el
Parse the Org-cite syntax in ROAM_REFS
> (feat)db: allow [cite:@foo] links in ROAM_REFS

- doc/org-roam.org
- doc/org-roam.texi
To add mention of the org-cite support.
Also, though I have not included it, should also help the reader understand when and why they would want to also or alternatively to use ORB.
> doc: Add mention of org-cite to bibliography

- org-roam-db.el
This commit is follow-up for PR #2009 should fix issues #1927 & #1910.
Currently, `[:pragma (= foreign_keys ON)]` is present only in function
`org-roam-db--init`. This means the `foreign_keys` is turned on only when the db
file is created for the first time. Subsequent Emacs sessions won't turn it on
as the db file is already present and does not evaluate `org-roam-db--init`.
This PRAGMA needs to be turned on each database connection at runtime according
to sqlite's documentation (https://sqlite.org/foreignkeys.html#fk_enable)
```
Foreign key constraints are disabled by default (for backwards compatibility),
so must be enabled separately for each database connection
```
I have observed that on Windows only the Emacs session that initially creates
the Org-roam db file works correctly with …
> (fix):db: pragma foreign keys to work with sqlite3

- org-roam-utils.el
When visiting a file, ensure that local variables are respected. Fixes #1917
> (fix)org-roam-with-file: ensure local variables are respected

- CHANGELOG.md
- extensions/org-roam-dailies.el
That gives convenience to create shorter keybindings that lead right into desired capture template buffer avoiding the need to select it each time in the capture selection screen. 
```elisp
(leader-def
"rt" '((lambda () (interactive) (org-roam-dailies-capture-today nil "d")) :wk "capture today daily")
"ri" '((lambda () (interactive) (org-roam-dailies-capture-today nil "i")) :wk "capture interruption"))
"ro" '(some-other-roam-bindings)
```
It makes `org-roam-dailies-capture-today` arguments to behave exactly as `org-capture` arguments do - (&optional goto keys).
> Add `keys` argument to `org-roam-dailies-capture-today` and `org-roam-dailies--capture` functions.

- org-roam.el
The `fd` backend for listing files, introduced in #1583, did not work for me, mainly because the command is actually:
fd -L --type file -e .org -e .org.gpg . "/home/user/org-roam"
In other words, the directory comes last, and a pattern (a match-all pattern `.`) needs to be specified (otherwise `fd` assumes the last argument is the pattern, in this case `/home/user/org-roam`). There was a slight bug in the creation of the `extensions`variable, where only the second pattern (`.org.gpg`) would be prefixed by `-e`.
P.S. It might be good if @Wetlize would chime in, as they wrote the original PR.
> Make 'fd and 'fdfind backend actually work for listing files

- CHANGELOG.md
- org-roam-node.el
Format minibuffer completion candidates using `window-width` instead of `frame-width`. This way completions render as a single line even if the frame is split.
Before: Empty line between completions
After: No empty line between completions
> (fix)Format completions to window-width, not frame-width

- CHANGELOG.md
- extensions/org-roam-dailies.el
- extensions/org-roam-graph.el
- org-roam-capture.el
- org-roam-db.el
- org-roam-migrate.el
- org-roam-mode.el
- org-roam-utils.el
- org-roam.el
It seems unnecessary to depend on an entire library just for one function that is trivially implemented ourselves. I suggest we drop that requirement.
Part of the motivation for this is that I am currently investigating if we can add this package to NonGNU ELPA, and we have not yet added f.el to that archive; and adding it will take more time.
Thanks!
> Drop f.el dependency

- CHANGELOG.md
- doc/org-roam.org
- doc/org-roam.texi
- org-roam-db.el
Adds two customizable variables: org-roam-db-extra-links-elements and
org-roam-db-extra-links-exclude-keys, which govern which elements are to
be considered for link parsing by Org-roam.
Also added sane defaults to org-roam-db-extra-links-exclude-keys.
Closes #2029
> (feat)db: add customizability of extra element link parsing

- CHANGELOG.md
- org-roam-capture.el
This allows the ID to be used as part of the capture template. Addresses #2048.
> (feat)capture: create ID before capture process

- CHANGELOG.md
- org-roam-node.el
Adds an argument `FILTER-FN` to `org-roam-node-random` to restrict selection for random Org-roam nodes.
E.g.
``` emacs-lisp
(defun my-org-roam-node-random (&optional other-window)
(interactive current-prefix-arg)
(org-roam-node-random
(lambda (node)
(member "draft" (org-roam-node-tags node)))
other-window))
```
Will restrict random notes to only those tagged `draft`. Closes #2022.
> (feat)org-roam-node-random: support filter-fn

- CHANGELOG.md
- README.md
- doc/org-roam.org
- doc/org-roam.texi
- org-roam-node.el
Revert to a simplified `org-roam-node-display-template`, because on
non-vertical completion frameworks it looks and behaves strangely. To
restore the original default behaviour, set
`org-roam-node-display-template` in your Emacs configuration as such:
```
(setq org-roam-node-display-template
(concat "${title:*} "
(propertize "${tags:10}" 'face 'org-tag)))
```
This should reduce confusion for newcomers, at the trouble of existing users,
eliminating issues of this sort:
#1778, #1735, #2044, #1941, #1627
> (breaking!)node: simplify default display-template

- CHANGELOG.md
- org-roam-node.el
Org-roam usually "normalizes" non-english characters in node titles, such as á becomes a, é becomes e, which is helpful with external programs which are finicky with this.
The double acute accent was left out, so ű, ő wouldn't normalize.
> [FIX] Added DOUBLE ACUTE ACCENT for unicode normalization

- org-roam-node.el
Also, make interactive argument actually apply for other-window
> (fix)node: make filter-fn for org-roam-node-random optional

- CHANGELOG.md
- extensions/org-roam-dailies.el
This is an extension of PR #2028 by @astery, where the `keys` argument was added to `org-roam-dailies--capture` `org-roam-dailies-capture-today`.
I extended this argument to also be available in other built-in dailies functions, as I didn't see any reason why not and it results in my opinion in more consistent behaviour. So far it seems to work for me. But I' wondering why @astery didn't implement that everywhere in the first place, so maybe there is a reason I don't know.
One thing that might be confusing for users is when they start adding the keys to all their dailies functions without reading their respective docstrings, since some have have already other optional arguments, so users might need to add some `nil`'s, e.g.
``` emacs-lisp
(org-roam-dailies-goto-date nil "<key>")
```
Then, …
> Allow specifying template keys in remaining org-roam-dailies capture/goto commands

- org-roam-id.el
- org-roam-node.el
- org-roam.el
Refactors ID-related items into its own module. The motivations are few-fold:
1. We shouldn't hijack `org-open-at-point-functions`, but instead replace some of `org-id` functionality. We scope these overrides within its own module for encapsulation.
2. 
With this change the following unreported (on GitHub) bug is fixed:
1. Following `id` links now respects`org-link-frame-setup`
> (feat)id: add org-roam-id module

- CHANGELOG.md
- extensions/org-roam-dailies.el
When dynamic binding `org-roam-directory` to the "dailies/"
subdirectory also bind `org-roam-dailies-directory` to "./" to prevent
invalid expansions in user-defined hook functions.
Fixes #2070
> (fix)dailies: prevent multiple "dailies/" subdirectory expansions

- CHANGELOG.md
- extensions/org-roam-protocol.el
- org-roam-capture.el
Let's assume we're evaluating the following region:
```elisp
(org-roam-capture-
:node (org-roam-node-create :title "Org Roam Homepage")
:info '(:ref "https://orgroam.com")
:props '(:immediate-finish nil))
```
Prior to this commit, if you did not require "org-roam-protocol" then
`org-roam-capture-` would ignore the `:info '(:ref
"https://orgroam.com")` parameter.  Once you required
"org-roam-protocol" then the callback hooks that process `:info`'s
`:ref` will fire regardless of whether it comes from org-roam-protocol.
After this commit, you no longer need to require "org-roam-protocol" to
ensure that you capture an `:info`'s `:ref`.
Why is this useful?  When I'm reading through my elfeed RSS feed, I want
to capture an article.  I could use the org-roam-protocol to do this,
but that seems a …
> Ensuring that :ref info capture in all cases

- CHANGELOG.md
- org-roam-mode.el
> (fix)buffer: buffer-toggle: don't destroy window if `org-roam-node-toggle` reuses window

- CHANGELOG.md
- org-roam-capture.el
Currently, Condition 1 below is met. A fix will need to meet Condition 2 in addition.
1. The new Org ID must be available to other functions during the capture
process
2. Adding the new Org ID to Org ID file/hash must be done after "Abort" check
-- i.e., when the user aborts the capture process, the new ID must not be
added to the Org ID file and hash database
> fix #2083 ID should be added to org-id-locations-file after capture

- org-roam-node.el
Previously, the file-path of the new node in `org-roam-extract-subtree`
was incorrect in many circumstances.  Expanding w.r.t. the initial
prompt directory (ie, `org-roam-directory`) fixes that.
Fixes #1811 and #1870.
-------
> (fix)node: properly expand extraction file path

- extensions/org-roam-dailies.el
- org-roam-utils.el
- org-roam.el
On Windows, `file-truename` and `directory-file-name` downcase drive label: "C:/" => "c:/", while `expand-file-name` keep the case unchanged.
If `org-roam-directory` use upper case drive label, `org-roam-descendant-of-p` will alway return `nil`.
This make `org-roam` totally unusable!!
From [here](https://github.com/org-roam/org-roam/blob/b163c900b8ec2e3637bc251d9b90421efc771c02/org-roam-compat.el#L64), all the candidates file names have a lowercase drive label.
> Fix `org-roam-descendant-of-p` bug on Windows

- org-roam-capture.el
This is a band-aid that prevents catastrophic situations where captures
have been manually saved, but deleted during a capture abort. Closes #2094.
> (fix)capture: always ask before deleting capture

- org-roam-capture.el
My attempt to address https://github.com/org-roam/org-roam/issues/2102 .
Feedback is welcome.
> (fix)capture: don't update org-id-locations if file is unknown

- CHANGELOG.md
- org-roam-capture.el
- org-roam-node.el
Special care is taken not to move the point if the original point is no
longer the same (i.e. the user moves the cursor after calling the
capture, but before finalizing it). Fixes #2108.
> (fix): place cursor after inserted link for new nodes

- extensions/org-roam-dailies.el
- org-roam-utils.el
- org-roam.el
It seems that the `file-in-directory-p` function proposed in #2089 is provided only for
*physical directories*, does not work as we would like with *symlinked directories*.
It dereferences all the symlinks in its path, and previously seemed related paths
cease to be such.
For example:
Source paths:
```
~/org-roam/ -> ~/MEGAsync/org-roam/
~/org-roam/note.org -> ~/Desktop/note.org
```
How `file-in-directory-p` sees them after dereference:
```
~/MEGAsync/org-roam/
~/Desktop/note.org
```
Because of this, such notes are ignored and not indexed, although they were indexed earlier.
This PR restores symlink support. Fixes #2111.
> (fix): caching symlinked files

- doc/org-roam.org
- doc/org-roam.texi
Add more notes about using `org-roam-protocol`.
> (docs): add docs for org-protocol

- CHANGELOG.md
- org-roam-capture.el
- org-roam-utils.el
- tests/test-org-roam-capture.el
- tests/test-org-roam-utils.el
Preserve the whitespace content given in the capture template, by
caching it and then appending it to the output template. For
Org-capture's purposes, we need to separately ensure that a newline is
present. Adds tests to the various helper functions to illustrate changes.
Addresses #2115
> (fix)capture: fill-template preserve whitespace content

- org-roam.el
The below was originally prepared for submitting an Issue, but once I realized a problem I am having with the "elisp" method was separate, I decided to update to the head of master and submit a PR for this.
Change #2025 broke all of the `org-roam-list-files-command` methods except `elisp`. This causes `org-roam--list-files` to iterate through all the variants executing their commands via `org-roam--shell-command-files` but to not see any output, until it finally lands upon `elisp` and gets some results.
I say that Change #2025 broke it because it replaced
```elisp
(seq-filter #'s-present? it)))
```
with
```elisp
(seq-filter (lambda (s)
(or (null s) (string= "" s))) it)))
```
effectively turning it into `#'s-blank?` and reversing the test. Wrapping the `or` in `(not ...)` addresses the …
> Fix the file listing methods broken by change #2025

- doc/org-roam.org
- doc/org-roam.texi
- org-roam-mode.el
Prior to this commit, when we would render backlinks in the
`org-buffer`, we would render each reference.  This meant that if a
source file referenced the node 5 times, there would be 5 backlink
references in the `org-buffer` (one for each position of the reference).
With this change, we add a parameter that specifies that backlink
sources should be unique.  In the above example, that would mean instead
of 5 backlinks we'd see 1.  And, as a concession, we'd use the lowest
position (e.g. the first reference in the source).
Closes #2119
> Adding unique option fro org-roam-backlinks-section

- doc/org-roam.org
- doc/org-roam.texi
- org-roam-mode.el
Update `org-mode-section-functions` to accept a list, that passes the arguments into the section rendering function. cc @jeremyf
> (feat)buffer: pass args to org-mode-section-functions

- CHANGELOG.md
- doc/org-roam.org
- doc/org-roam.texi
- org-roam-compat.el
- org-roam-mode.el
With #2123, we introduced an additional way to specify `org-roam-mode-section-functions`. Rename this to `org-roam-mode-sections` to reflect the changes, and update the defcustom.
> (fix)buffer: update defcustom for org-roam-mode-section-functions

- org-roam-capture.el
- org-roam-node.el
- org-roam.el
some times the node title and the tag are the same, so I added this callback to automatically add the label every time when I insert a node
> (feat): add org-roam-post-node-insert-hook

- org-roam-mode.el
Org-roam finds nodes across symlinked directories.  The `org-roam-unlinked-references-section` function does not.
This addresses that by adding the `-L` option to tell ripgrep to follow directory symlinks while looking for unlinked references. which matches what `org-roam--list-files-rg` does.
> (fix) unlinked-references: search symlinked directories

- CHANGELOG.md
- doc/org-roam.org
- doc/org-roam.texi
- extensions/org-roam-export.el
Initialize a new module `org-roam-publish` that can be `require`d to patch `org-export` to support publishing Org-roam files.
Addresses #2131.
> (feat)export: init

- doc/org-roam.org
debian packaging cannot use id links to build docs.
Fixes #2145.
> (docs): fix docs build

- CHANGELOG.md
- org-roam-mode.el
Fix #2151 
Using save-excursion in `org-roam-preview-default-function` to avoid copying next heading.
> (fix) org-roam-preview-default-function doesn't copy next node

- CHANGELOG.md
- org-roam-capture.el
- tests/test-org-roam-capture.el
Fix #2156 
See above issue for description of the cause.
Issue is addressed by processing the function templates before `org-roam-capture--fill-template` is being called.
> [Fix #2156] Process fn capture templates before whitespace-content

- CHANGELOG.md
- org-roam-db.el
Add support for emacsql-sqlite-builtin and emacs-sqlite-module. Fixes #2146.
> (db): support emacsql-sqlite-{builtin,module}

- CHANGELOG.md
- org-roam-db.el
Fixed cases where buffer is narrowed and `org-roam-db-update-file` is called. We need to widen and process everything before renarrowing.
Closes #2139.
> (db): fix db sync for narrowed buffers

- CHANGELOG.md
- org-roam.el
Update `org-roam-file-exclude-regexp` to support lists, and to include `org-attach-id-dir` by default.
Closes #2084
> (core): ignore org-attach-id-dir by default

- org-roam-db.el
Fixes https://github.com/org-roam/org-roam/issues/2146#issuecomment-1100790466
Tested on:
- Emacs: GNU Emacs 29.0.50 (build 1, aarch64-apple-darwin21.1.0, NS appkit-2113.00 Version 12.0.1 (Build 21A559))
of 2022-01-11
- Framework: Doom
- Org: Org mode version 9.6 (9.6-??-971eb6885 @ /Users/jethro/.emacs.d/.local/straight/build-29.0.50/org/)
- Org-roam: v2.2.1-10-ga8d9790
> (db)fix: fix sqlite-builtin and sqlite-module

- org-roam-utils.el
Add additional information about sqlite-connector to `org-roam-diagnostics`.
> (utils): add sqlite-connector to diagnostics output

- org-roam.el
Errors when opening a .epub file with nov.el (a package
that renders EPUB file) because nov.el doesn't store the filename
in `buffer-file-name`, opening it caused errors with `org-roam-file-p`.
The error is documented in #2163
> (fix) `org-roam-file-p` handle opening a buffer with no path

- CHANGELOG.md
- org-roam-node.el
Moves the optional node filter in org-roam-node-read--completions before
the mapcar `org-roam-node-read--to-candidate`.
This saves time for completion on org-roam-node-find and
org-roam-node-insert (but only when a filter-fn is passed).
-------
I have experienced slowness (several seconds) on every node-find and node-insert
command for a while, but finally made the time to dig into _why_ today.
I have about 1k files and 5k nodes in my roam db.
I realized while digging that my 'archived' org nodes are being included, which
could perhaps be filtered to speed things up. Alternatively, i mostly
only care to link to files anyway. Fortunately, `filter-fn` exists as a way to
filter some nodes.
I tried:
``` emacs-lisp
;;;###autoload
(defun russ/org-roam-insert-node-level-0 () …
```
> (perf)node-read: filter before map to candidate

- CHANGELOG.md
- org-roam.el
Don't exlude the org-roam-directory even if it matches
org-roam-file-exclude-regexp.
Should fix #2165.
This makes `org-roam-file-p` compare `org-roam-file-exclude-regexp` only with files and subdirectories within  `org-roam-directory`, not the entire path.
When someone has an `org-roam-directory` that contains a (sub)string that is a part of `org-roam-file-exclude-regexp`, the entire org-roam directory is excluded, and all files removed from the database.
For example, when `org-roam-directory` is "~/data/org-roam/" and `org-roam-file-exclude-regexp` is "data/", the entire roam directory is exluded, and no files are found.
> (fix)org-roam-file-p: don't exclude org-roam-directory

- org-roam-db.el
- org-roam-node.el
Previously we only updated the database on file save, but we need to
update the file's atime on file access, so we hook into `find-file-hook`
to do so. We only update the file atime if the file exists in the file table.
Fixes #2075
> (fix)db: update atime on file access

- org-roam-node.el
Calling org-roam-extract-subtree fails with current head.
This PR contains two fixes, making it work again for me:
- use cl-incf instead of incf
- call (save-buffer) before promoting it.
> Fix org-roam-extract-subtree

- org-roam-node.el
org-roam-node-at-point returned the wrong value if point-min is a
level-1 heading node. We make sure that everytime we go up one
heading, the outline-level changes (reduces by 1) to prevent this error.
> (node): fix org-roam-node-at-point check

- .github/workflows/test.yml
- org-roam-capture.el
- tests/test-org-roam-capture.el
Issue: https://github.com/org-roam/org-roam/issues/2192
Unwanted removal of `\n` characters in Org Roam template strings.
-----
`org-capture-fill-template` fills the template string, but it removes whitespace and newlines at the beginning and end of the template.*
`org-roam-capture--fill-template` removes all blank lines and restores them after calling `org-capture-fill-template`.
The regex formula used for this however (`\n$`) eliminates all blank lines in the template, whether or not they are at the beginning and end of the template.
By replacing it with `[\n]*\\'` only the blank lines at the end of the template will be removed -only the ones which will be later restored.
With a default template as follows:
```
(setq org-roam-capture-templates
'(("d" "default" plain "%?"
:target …
```
> Solved issue #2192 (Respect blank lines in capture templates)

- org-roam-node.el
Added support for custom `completion-read` predicate to the
`org-rom-node-find` function.
The `org-roam-node-find` function relies on `org-roam-node-read`,
which already provides the `require-match` argument to support this
behavior.
This PR adds an optional argument to `org-roam-node-find` which is
passed to the embedded `org-roam-node-read` call in order to support
custom `completion-read` predicates when searching for nodes in the
minibuffer.
Case-insensitive search in the minibuffer:
```elisp
(defun case-insensitive-matchp (nodes string)
"Check if the interactive prompt contains a case insensitive
substring of an Org Roam node title."
(interactive)
(lambda (needle haystack) (cl-search (downcase needle) (downcase haystack))) nodes)
(defun my-org-roam-node-find ()
"Wrapper to run …
```
> support custom minibuffer matching function

- org-roam-node.el
Add the id as an invisible propertized string to the candidates for org-roam-ref-find.
Fix #2207
> ensure unique candidates in `org-roam-ref-find`

- org-roam-db.el
When trying to save from a narrowed buffer, only the Roam nodes visible
in the narrowed buffer are written to the database.
This commit ensures that org-roam behaves the same whether the current
buffer is narrowed or not.
> (db)fix: FOREIGN KEY error in narrowed buffer

- org-roam.el
Autoload `org-roam-list-files`. Fixes #2224.
> (fix): autoload org-roam-list-files

- org-roam-utils.el
Closes #2228.
`org-fold` was recently implemented in Org Mode. The default `org-fold-core-style` is `text-properties`, which causes links to be displayed incorrectly as reported in #2228. Switching to the `overlays` style fixes this.
(My current `org` is pinned to https://github.com/emacs-straight/org-mode/commit/e9da29b6fafe63abbc2774e9d485ac13d2811b65).
> (fix): links not displayed properly in org-roam-buffer

- org-roam-utils.el
> (fix): remove use of deprecated org-font-lock-ensure

- org-roam-node.el
Without specifying `t`, it is only pushing the PROPERTIES drawer up  to
the file level, missing any other "planning information, clocking lines and
any kind of drawer." We want to promote all of this to the file level.
> was missing the FULL parameter to `org-end-of-meta-data` - fixes #2242

- org-roam-db.el
- org-roam-node.el
- tests/roam-files/ref_with_space.org
- tests/test-org-roam.el
Fix #2214
Some URLs and local links have space characters. `org-roam` can't handle these types of link.
- Add double quotes if the URL has a space when user is capturing.
- Update ref cache logic to handle the org-link which has spaces.
> Fix space chars in roam refs

- org-roam-node.el
Allows use of : in minibuffer to separate multiple selected tags.
-------
Tags in org are separated with a colon, so it makes sense to have them separated this way when selecting them in completing-read-multiple too. This is the approach taken by `org-set-tags`.
> org-roam-tag-add: use tags separator as crm-separator

- CHANGELOG.md
- org-roam-db.el
- tests/test-org-roam-utils.el
org-mode allows multi-line titles, for example:
```org
#+title: Spatiotemporal Variance-Guided Filtering:
#+title: Real-Time Reconstruction for Path-Traced Global Illumination
```
This helps with legibility. When exporting, org joins the multiple lines with a space as separator to produce the final title for the exported document.
Until now this functionality does not seem to be supported by org-roam. Only the first line will be used as the title.
I have to admit, I am not a elisp expert but I managed to narrow the problem down to the `org-roam-db--file-title` (thanks to its very hepful docstring!).
```lisp
(defun org-roam-db--file-title ()
"In current Org buffer, get the title.
If there is no title, return the file name relative to
`org-roam-directory'."
(org-link-display-format
(or …
```
> Support multi-line org titles

- doc/org-roam.org
See https://list.orgmode.org/87blb3epey.fsf@gnu.org/ for details. Removed it from the documentation in the manual to (try and) assist newcomers.
Trying to install `org-mode` according to the manual fails, and on my setup (Emacs 28.1) is unnecessary.
If it is still required for the manual to help users install a recent version of `org-mode`, its [installation docs](https://www.gnu.org/software/emacs/manual/html_mono/org.html#Installation) recommend:
1. Using Emacs packaging system (no mention of adding the elpa repo)
2. Using Org’s git repository
> (Docs): orgmode.org/elpa has been shut down

- org-roam-db.el
I added a link in the properties drawer, however it does not show up in the backlinks. so I checked org-roam.db. It turns out that the outline of the link is empty.
> fix outline of link in properties

- org-roam-mode.el
`org-roam-unlinked-references-section` would get nil org-roam-node-title
when create a headline node, which caused the issue #1625. This commit
add a check to make `org-roam-unlinked-references-section` work
correctly.
> (fix): update `org-roam-unlinked-references-section` check

- doc/org-roam.org
- org-roam-mode.el
See #1043.
Being able to filter things from the backlinks buffer (for instance, dailies) can be helpful to reduce on-screen clutter.
> Add support for filtering backlinks.

- org-roam-db.el
Default to sqlite-builtin when Emacs has sqlite functions available.
> (db): default to sqlite-builtin when possible

- org-roam-node.el
This fixes the following situation where
`org-roam-completion-everywhere = t` and you are working with org-babel
blocks in one of your org-roam nodes.
```
#+begin_src emac|
#+end_src
```
Before my nodes would be suggested, but after this change only valid
babel headers are suggested as desired.
Previously completions from org-roam nodes would be suggested
> don't complete org-roam nodes in source blocks

- org-roam-node.el
Adds `org-roam-node-category`. Closes #2290.
> (core): add org-roam-node-category

- org-roam.el
This PR adds discoverability for org-roam files that are encrypted in the .age format (https://age-encryption.org/v1)
Age encryption support is available for Emacs through https://github.com/anticomputer/age.el and provides a modern replacement for GPG based encryption of Emacs files in the style of EPA/EPG.
> add discoverability support for age encrypted org files

- org-roam-utils.el
This has an effect on find-file-hook for totally unrelated files, through the callchain of `org-roam-db-autosync--setup-file-h -> org-roam-file-p -> org-roam-descendant-of-p'.
From an org file, inside a project-el project, (find-file "some/other/file") will intermittently reproduce this error:
org-roam-descendant-of-p: Wrong type argument: arrayp, nil
If this fix seems inappropriate -- it could amount to surppressing a valid error in routine calls -- then I would advise throwing an explicit signal here, or finding a safer way to get the `path` inside `org-roam-file-p'; the current means:
(or file (buffer-file-name (buffer-base-buffer)))
.. can result in nil, which then bleeds errors into use elsewhere.
for posterity, here is the full calling context I'm referring to, from …
> utils: descendant-of-p: Defend against nils

- org-roam-node.el
I only use bibliography keys as refs, but I use a *lot* (e.g. for a book I'm half way through, I have nine nodes with the book's ref). When I want to add the ref to a node, at the moment I have to get the book's ref key somehow (e.g. with an embark action from citar, or by copying straight from Ebib), then run ``org-roam-ref-add`, *then* type '@', and finally insert the ref key and hit <kbd>RET</kbd>. This is a heavy workflow for something I do so often.
I imagine other users feel similarly. This PR lets the user set a prompt function for getting refs, which can streamline processes like this.
Personally, I could set this to a simple wrapper over `citar-select-ref`, though others might do otherwise. This makes the whole process of adding refs much simpler. Leaving the variable at nil …
> Add customisable function for prompting when adding refs

- org-roam-utils.el
Closes #2198
Related issues: #2228, #2236, [doomemacs#6542](https://github.com/doomemacs/doomemacs/issues/6542), [org-brain#387](https://github.com/Kungsgeten/org-brain/pull/387)
Strangely, Emacs 28.x and doom sync does optimize `org-fold-core-style` in a `let` clause. So `org-fold-core-style` in org-roam-buffer is still `text-properties`. People who doesn't use or skip bytecompiling didn't meet this issue. But some users who use bytecompiling see this issue.
On Emacs 30.0.50, `org-fold-core-style` doesn't be removed in `org-roam-utils.elc`. For 28.x, I think the best workaround is to change `let` binding to `setq-local`.
You can check this workaround.
1. cd `~/.emacs.d/.local/straight/build-*/org-roam`
2. `strings org-roam-utils.elc | grep org-fold-core-style`
- If the …
> Fix org-fold-core-style in org-roam-buffer

- org-roam-node.el
`=' assumes that both objects being compared are numbers. In some
buffers `outline-level' can return nil, so `=' returns an error. `eq'
does not assume this, but does return t when comparing two numbers.
-------
I use `org-roam-node-at-point` in my [related-files](https://github.com/DamienCassou/related-files) config to get the node at point when there is one, assuming that it returns nil if there *isn't* one.
In the case where `outline-level` can return nil, (e.g. for me in some elisp buffers where I use `outshine-mode`), nil is the compared with a number using `=`, which throws an error (when I should just get nil).
This change solves this issue.
> (node): org-roam-node-at-point: don't error in non-org buffers

- doc/org-roam.org
In its current form, the org-protocol applescript never finishes execution, and after being executed once, it has to be force-quit before it can be executed again. Adding `& filePath & " &> /dev/null &"` fixes this issue.
> (docs): update org-protocol instructions

- doc/org-roam.org
- doc/org-roam.texi
- org-roam-mode.el
For the sentence that was originally "These extensions may one or more of the following functionalities", I guessed that the intended meaning was "use". Let me know if I guessed wrong.
> Fix some typos

- doc/org-roam.org
Fix: #2392
As noted in the related issue, the example was not working due to the `my/` vs `my-` mismatch.
I decided to change to `my-` to be coherent with other variables and function in this document.
> (docs): fix name of my-org-roam-show-backlink-p

- org-roam-node.el
This mix of tabs and spaces was introduced recently in: https://github.com/org-roam/org-roam/commit/2e94f55cc58f6dce2772a6f33521eb5afcf67265
Example of failed ci job:
https://github.com/org-roam/org-roam/actions/runs/9748813724/job/26904611920
> (chore): fix indent blocking ci lint execution

- org-roam-mode.el
Fix Issue #2410 
In the function `org-roam-unlinked-references-section` the `org-roam-directory` variable is concated to form the `rg_command`. This doesn't cover any spaces in the `org-roam-directory` path.
So if the path is `/Users/user123/MyDrive/My Files/org-mode/org-roam`, due to the space in My Files rg returns an error:
```
rg: /Users/user123/MyDrive/My: No such file or directory (os error 2)
rg: Files/org-mode/org-roam: No such file or directory (os error 2)
```
This is due to the [lines here](https://github.com/org-roam/org-roam/blob/8667e441876cd2583fbf7282a65796ea149f0e5f/org-roam-mode.el#L667-L675):
```elisp
(rg-command (concat "rg -L -o --vimgrep -P -i "
(mapconcat (lambda (glob) (concat "-g " glob))
(org-roam--list-files-search-globs org-roam-file-extensions)
" ")
(format " …
```
> Fix Issue #2410 - Unlinked References doesnt work if the org-roam-directory has a space in it. 

- CHANGELOG.md
- org-roam-mode.el
- org-roam.el
After #2247 was merged, it is now possible to add multiple `org-roam-backlinks-section`s to `org-roam-section`, using different functions to filter the backlinks in the different sections.
However, all the sections have "Backlinks:" as the heading. This should enable the user to have different backlink sections with differing headings and filters.
> Backlink heading

- tests/roam-files/family.org
- tests/test-org-roam-id.el
- tests/test-org-roam.el
Improving test coverage to avoid regressions on future PRs merging.
> (test): add org-roam-id-find

- CHANGELOG.md
Hi
The date are now YYYY-MM-DD to avoid any confusion between the USA and the rest of the world.
Also mention obsolete symbols. Ref https://github.com/org-roam/org-roam/issues/1879
> (docs): add missing versions dates and obsolete notice

- org-roam.el
As explained in #2442 , the documentation `org-roam-file-exclude-regexp` may be more detailed to let the user know he/she can use a single regexp or a list of regexp to exlude files.
> (docs): explain org-roam-file-exclude-regexp

- org-roam-capture.el
- org-roam-utils.el
As described in https://github.com/org-roam/org-roam/issues/2348, the `org-roam-shield-region` function is not called anymore.
The reverse function and associated face can also be removed.
Fix: #2348
> (fix): remove dead-code about org-roam-shield feature

- doc/org-roam.org
Fix formatting for 2 code objects.
Reading the fine manual, I noticed two instances of what I think might have been meant to be formatting as ~code~ objects
> Doc formatting: 2 fixes

- org-roam-node.el
With this change, one can programmatically refile headings to org-roam-nodes.
> Take org-roam-node as argument to #'org-roam-refile

- org-roam-id.el
There have been recent changes in org-mode to improve `org-id-open` to be able to apply search strings in id: links.  But, org-roam overrides the `:follow` parameter for id: links to its own `org-roam-id-open` function and therefore misses this.
The only change that `org-roam-id-open` makes is to try calling `org-roam-id-find` before falling back on `org-id-find`.  This commit uses advice to do this directly, thereby integrating better with `org-id-open`.
There was some discussion on the org-mode list about adding a custom variable to avoid using advice, but this accomplishes the result without requiring changes in org:
https://list.orgmode.org/87jzlxjiuf.fsf@localhost/
> Compatibility with latest org-id version: advise org-id-find rather than overwriting id link

- org-roam-capture.el
- org-roam-db.el
- org-roam-log.el
- org-roam-migrate.el
- org-roam-mode.el
- org-roam.el
See https://github.com/magit/emacsql/issues/113.  Emacsql 4.0.0 has
been released and should now be used in the package-requires header.
> Depend on emacsql 4.0.0

- tests/test-org-roam-id.el
Hard-coded paths cause the tests to fail when building under different environments, e.g. under Debian sbuild it fails with the following errors:
```
,----
| ========================================
| org-roam-id-find finds the correct file node
| FAILED: Expected `(car location)' to be `equal' to `"/home/runner/work/org-roam/org-roam/tests/roam-files/foo.org"', but instead it was `"/build/reproducible-path/org-roam-2.2.2+git20250105.cad3518/tests/roam-files/foo.org"' which does not match because: (arrays-of-different-length 84 60 "/build/reproducible-path/org-roam-2.2.2+git20250105.cad3518/tests/roam-files/foo.org" "/home/runner/work/org-roam/org-roam/tests/roam-files/foo.org" first-mismatch-at 1). |
| ========================================
| org-roam-id-find finds the correct heading …
```
> Use regexp match to replace hard-coded path equal test

- org-roam-node.el
(kill-whole-line) kills folded text if called from column 1 Make sure to unfold text before calling it --
Prevents data loss if user has decided to extract subtree on a folded org headline.
As described in issue #2425 - org-roam-extract-subtree (by calling org-roam-promote-entire-buffer) deletes folded text because (kill-whole-line) when called from column 1 kills folded text -
Proposed change
```
-- org-roam-node-old.el	2024-06-26 00:04:34.713642244 +0530
+++ org-roam-node.el	2024-06-26 00:03:41.285582526 +0530
@@ -878,6 +878,7 @@
(org-with-point-at 1
(let ((title (nth 4 (org-heading-components)))
(tags (org-get-tags)))
+      (org-fold-show-all)
(kill-whole-line)
(org-roam-end-of-meta-data t)
(insert "#+title: " title "\n")
```
Best,
> fix #2425 Prevent data loss when user has called org-roam-extract-subtree on folded org headline

- extensions/org-roam-export.el
- extensions/org-roam-graph.el
- extensions/org-roam-overlay.el
- extensions/org-roam-protocol.el
- org-roam-capture.el
- org-roam-db.el
- org-roam-id.el
- org-roam-log.el
- org-roam-migrate.el
- org-roam-mode.el
- org-roam-node.el
- org-roam-utils.el
- org-roam.el
That function was added two years ago and the first release that
provided it was v4.0.0.  It automatically picks the best available
back-end, `emacsql-sqlite-builtin` or `emacsql-sqlite-module`.
In v4.0.0 it could also fall back to the legacy `emacsql-sqlite`.
The inferior third-party back-ends are no longer supported.
Emacsql v4.1.0, which will be releases in early December, removes
the legacy `emacsql-sqlite` back-end (which used a custom binary).
This means that we now require an Emacs that was built with SQLite
and/or module support.
-------
EmacSQL now takes care of picking the best back-end itself.  Let's
use that.
By removing an option that offers no longer valid choices, we make
sure users cannot pick an invalid choice.
> Rely on emacsql-sqlite-open to pick the best available back-end

- tests/test-org-roam.el
* In some rare case, the first expect of org-roam-file-p may return t when running in some environment (e.g. during autopkgtest in Debian).
* Setting org-roam-directory to a non-existent path ensure that the first check is always nil as expected.
> Set org-roam-directory to a non-existent path to ensure robust test
