- org-roam.el
> Add extension if none in org-roam-insert

- org-roam.el
So now I have 2 graph modes:
1. Ascii with graph-easy:
2. Graphviz
The ascii mode is a mess, but can possibly become interactive. The graphviz mode gives a nice overview, but is not interactive.
I think eventually what I'll do is create the n-degree graph: show all nodes at most n degrees away, and their edges, this should provide a good compromise for the ascii version.
> Add graph rendering

- org-roam.el
SVG makes the graph nodes clickable:
https://drive.google.com/file/d/1TqZyD98wSRkZ_h5uSVJvRXOuAW4-VofB/view?usp=sharing
Setup for this is a bit more involved (using a custom protocol, registering it in linux etc.). I like it and will likely keep it in. Shouldn't affect other users (just unclickable).
Move to an interactive d3 html page with clickable roam links.
> Clickable org-roam-graph

- org-roam.el
This change cleans up some code, and allows nested files in org-roam. Should resolve #15 .
Deft does really weird things with symlinks. Please specify the actual path of the deft-directory, otherwise there's no guarantee the links and stuff will work.
> Allow nested files

- README.md
- org-roam.el
We no longer need deft, although they can be used together. I find myself relying on deft a lot less now.
> Become deft-free 🎉

- README.md
There are a number of packages that play nice with org-roam. Related: #10
> Add documentation on synergistic packages

- org-roam-polyfill.el
- org-roam.el
Prevents current packaging mess. See #26 .
> Move polyfill into main file

- org-roam.el
Addressing #33 with 2 changes:
1. Instead of doing a file-directory traversal to check if it's part of a org-roam directory, we just do a simple directory traversal from child to parent.
1. The post-command hook is only added on org files that are part of the org-roam directory.
> Only enable post-command-hook on org-roam files

- org-roam.el
Big change... hopefully the last one before I cut the release.
Now the cache is only built once from scratch (asynchronously). The cache is now automatically updated at every buffer file save. This means that the cache is always up to date. To do so, I had to also store the forward links.
I've also changed the cache to store the true filename instead of ids, for ease of use. There's a lot of code duplication around cache building right now, which I should clean up.
> Incremental update of cache

- org-roam.el
> Fix interactive commands using the wrong paths

- org-roam.el
Adds additional cache for file titles, for use it downstream commands.
- Setting `org-roam-link-representation` to `'title` will now use the title in insertion and finding.
- The cache is used to populate the org-roam buffer.
> File-title cache and related functionality

- org-roam.el
Fixed some of the bad symlink handling. This is way more troublesome than I hoped it would be.
> Fix symlinks handling

- org-roam.el
org-roam--ensure-cache-built errors out if the cache is not yet built, and attempts to build the cache.
> Add org-roam--ensure-cache-built

- org-roam.el
The title is now automatically populated by default. This behaviour is customizable via `org-roam-autopopulate-title`. The title is either provided during prompt, or inferred from the file name.
> Add org-roam--populate-title

- LICENSE
> Add GPL License

- org-roam.el
Add an option to use timestamps for filenames without prompt.
> Add org-roam-timestamped-files option

- org-roam.el
In preparation for publishing to MELPA
> add more metadata into org-roam

- org-roam.el
See https://nullprogram.com/blog/2014/05/27/
> Refactored functions to buffer-passing style

- org-roam.el
> Fix org-roam-insert inserting absolute paths

- org-roam.el
There was a lot of duplication between the lambda for building the cache async, and the normal processing functions, because the processing functions needed to be available within the `async-start` function. I'm not sure of the proper way to inject defuns into `emacs-async`, but this seems to work. The downside is that help functions no longer work/point to the correct source.
Do you know of a better way? cc @l3kn
> deduplicate async/non-async functions

- org-roam-utils.el
- org-roam.el
This fixes #74 for some reason
> Move org-roam sync/async utilities to org-roam-utils

- org-roam.el
> Insert org-roam-links relative to current file

- org-roam.el
> Fix org-roam hooks not being attached on nested files

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
Add the changelog, and update readme
> Org-roam 0.1.1

- doc/ecosystem.md
h/t @tpeacock19 for pointing out that changes in org-roam made Deft's interface less useful, see:
https://github.com/jethrokuan/org-roam/issues/23#issuecomment-586627619
> Add documentation for deft-title patching

- tests/roam-files/f1.org
- tests/roam-files/f2.org
- tests/roam-files/nested/f1.org
- tests/roam-files/nested/f2.org
- tests/roam-files/no-title.org
- tests/test-org-roam.el
Add the first legit test cases 🎉 See #79
> Add test for org-roam--build-cache-async

- org-roam-utils.el
> (bugfix): fix org-roam--find-file picking up temporary files

- org-roam.el
@BarryLiCMU can I have you confirm this fix works for you? I changed `find-file` to `find-file-noselect`. 
Fixes #102
> (bugfix): force a cache update on making a new file

- CHANGELOG.md
- org-roam.el
- tests/test-org-roam.el
> (feature): insert link as downcased title with `org-roam-insert`

- CHANGELOG.md
- README.md
- doc/installation.md
- org-roam.el
> (chore): some cleanups

- doc/graph_setup.md
Thanks @naistran for instructions, and @leothelocust and @seandavi for
discussion and confirmation
Add documentation for graph setup on MacOS, closes #115
> (docs): Add graph setup documentation for MacOS

- CHANGELOG.md
- org-roam-utils.el
- org-roam.el
We've had a huge number of bug-fixes, performance improvements, breaking changes, and new features in the past 6 days. I think it's a good time to cut a new minor release.
This frequency will likely decrease once things become more stable.
> Org-roam v0.1.2

- org-roam.el
Prevent multiple async cache builds.  This can happen when restoring a session or loading multiple org-roam files before a build has completed.
> (bugfix): prevent multiple async build processes

- doc/graph_setup.md
> Enable Chrome external app checkbox on Linux

- org-roam.el
- tests/test-org-roam.el
> (feature): add `org-roam-mute-cache-build` to mute cache build message

- org-roam.el
Prevents that the `org-roam--build-cache-async` process is blocked forever if an async
error occurs.
Refs #149, #151
When [org-roam--build-cache-async fails to decrypt .gpg files](https://github.com/jethrokuan/org-roam/issues/151) there is currently no possibility for a 2nd attempt, because the lock `org-roam--ongoing-async-build` is still set.
> (bugfix): Check future status to prevent multiple async tasks

- CHANGELOG.md
> (chore): add changelog entry for #165

- doc/tour.md
> Fix typo in tour.md

- org-roam-utils.el
- org-roam.el
> (chore): require minimum org version of 9.0

- doc/configuration.md
Requested documentation
ref #80
> (docs): add multi dir config to doc/configuration

- org-roam.el
> (bugfix): populate database after org-roam--make-new-file

- org-roam.el
> (feature): add org-roam-yesterday

- README.md
- doc/anatomy.md
- doc/comparison.md
- doc/configuration.md
- doc/ecosystem.md
- doc/index.md
- doc/installation.md
- doc/notetaking_workflow.md
- doc/roam_protocol.md
- doc/tour.md
- mkdocs.yml
- org-roam-protocol.el
- org-roam.el
More documentation updates for #209
> (docs): docstring and docs update

- org-roam.el
Addresses #223 
Adds a string variable `org-roam-graph-exclude-matcher`, which is a regular string. If the file-path matches this string, it is excluded from the graph. defaults to nil, in which case no nodes are excluded from the graph.
> (feature): org-roam-graph-exclude-matcher: exclude nodes from graph

- org-roam.el
Fixes #234 .
1. Check for existence of file before calling `org-roam-capture`
2. Error out when file already exists, when attempting to create a new file.
> (fix): fix org-roam-today date functionality overriding old files

- org-roam-protocol.el
- org-roam.el
Final touchups for MELPA release.
> (chore): Cleanup for MELPA release

- org-roam-protocol.el
- org-roam.el
Address issues in comment https://github.com/melpa/melpa/pull/6738#issuecomment-596127594
> (chore): Cleanups for MELPA release

- doc/installation.md
> (docs): fix documentation for manual installation

- org-roam.el
Fix the small number of checkdoc errors in https://github.com/melpa/melpa/pull/6738#issuecomment-597164745
> (chore): fix more checkdoc errors

- doc/configuration.md
- org-roam.el
Some prefer using neato for generating a graph (ref #263). This
documents how to do so.
Closes #263
> (docs): add documentation for using neato

- company-org-roam.el
> (feat): Support multiple org-roam-directories for company backend

- org-roam.el
> (bugfix): remove nonexistent/redundant code

- org-roam.el
Fixes #304, using PR #305 as the base, thanks @khinsen
> (bugfix): Fix Helm integration for completing-read

- org-roam.el
Fixes #307 @khinsen can you check if this fixes Helm for you?
> (bugfix): fix Helm completing-read containing extra spaces on non-match

- org-roam.el
> (bugfix): prevent file open if capture is cancelled

- org-roam.el
> (bugfix): fix org-roam-capture not saving file

- org-roam.el
Fixes #327 
Instead of maintaining an external plist, we store all necessary information in the org-capture template. In addition, we maintain a nesting count for `org-roam-capture` calls, to ensure hooks do not get prematurely cleaned up.
> (bugfix): fix nested org-roam-inserts not working

- org-roam.el
Addresses #327 .
Supporting nested org-roam capture processes is hard, we do the next best thing and prevent the user from doing it.
> (bugfix): throw an error on nested org-roam capture processes

- org-roam.el
Following #332, nest all org-roam related customization in to a single
key.
> (internal): reduce org-roam-capture-templates pollution

- README.md
Adding @technoevangelist video onto the README :smile:
> (docs): Add Org-roam video

- doc/configuration.md
- org-roam-graph.el
See: https://github.com/jethrokuan/org-roam/issues/382
> Update org-roam-graph variable names

- org-roam-capture.el
Addresses https://github.com/jethrokuan/org-roam/issues/285#issuecomment-606724827
> (feat): Cache template variable entry

- doc/installation.md
Deprecation warning after installing on Spacemacs
> doc/installation: replace show-graph with graph-show

- README.md
> (chore): update Slack invite link

- doc/templating.md
> typo: eduring -> during

- org-roam-db.el
- org-roam-graph.el
As I found the graph increasingly unwieldy with a growing number of nodes, I wanted to only display the connected component containing the current node, which is implemented in the interactive function `org-roam-graph-show-connected-component`. It's based on `org-roam-db--connected-component`, which uses recursive common table expressions to retrieve all related file names.
To this end, I also adapted `org-roam-graph--build` and `org-roam-graph-show` to accept a node query, which was nice for playing around with different ideas. I'm not sure whether it should stay part of the interface of `org-roam-graph-show`, though. It could be moved to a separate function containing the current implementation.
In `org-roam-graph--build` the node query will be used to retrieve only those edges from the …
> Allow to create graph only of nodes connected to current entry

- doc/roam_protocol.md
> (doc): ref-capture-templates > capture-ref-templates

- org-roam.el
> (fix): org-roam.el eval-when-compile subr-x

- org-roam-graph.el
> (bugfix): fix org-roam-graph--open

- doc/installation.md
> (docs): mention company-org-roam in documentation

- doc/templating.md
Those excited about org-roam but new to Emacs and org-mode may not be familiar with the flexibility they can take advantage of. Providing some examples can help with this.
> (docs) Provide examples of using template expansion and function overrides.

- org-roam.el
> (feat) remove user-error for org-roam-insert

- org-roam-buffer.el
- org-roam-capture.el
- org-roam-compat.el
- org-roam-completion.el
- org-roam-dailies.el
- org-roam-db.el
- org-roam-graph.el
- org-roam-macs.el
- org-roam-protocol.el
- org-roam.el
Missed updating the version headers in #501
> (release): 1.1.0: update version headers in source

- doc/roam_protocol.md
> add keybinding to qutebrowser

- org-roam-db.el
> (fix): resolve symlinks during cache build

- org-roam-graph.el
Use settings provided by @tecosaur. Closes #539.
> (feat): prettier graph defaults

- CHANGELOG.md
- org-roam.el
> (feat): apply error face if file link is broken

- doc/org-roam.org
- doc/templating.md
> (docs): mention where to modify org-roam templates

- org-roam-graph.el
> (fix): improve error message on missing executable

- org-roam-graph.el
Follow up to #579 to improve the validation.
> (fix): make graph--build error on non-string

- org-roam.el
> (fix): do not store empty-string refs in db

- README.md
> (docs): link to discourse in README

- CHANGELOG.md
- README.md
- mkdocs.yml
- org-roam-buffer.el
- org-roam-capture.el
- org-roam-compat.el
- org-roam-completion.el
- org-roam-dailies.el
- org-roam-db.el
- org-roam-graph.el
- org-roam-macs.el
- org-roam-protocol.el
- org-roam.el
> (fix): update repo root to group

- org-roam-buffer.el
- org-roam-capture.el
- org-roam-compat.el
- org-roam-completion.el
- org-roam-dailies.el
- org-roam-db.el
- org-roam-dev.el
- org-roam-doctor.el
- org-roam-graph.el
- org-roam-macs.el
- org-roam-protocol.el
- org-roam.el
- tests/test-org-roam.el
Help ensure source code consistency.
emacsql indentation for now, but can easily be expanded as needed.
see #605
> Add org-roam-dev.el

- org-roam-buffer.el
- org-roam-capture.el
- org-roam-completion.el
- org-roam-dailies.el
- org-roam-db.el
- org-roam-doctor.el
- org-roam-graph.el
- org-roam-macs.el
- tests/test-org-roam.el
Replace generic package description in features' first line summary.
> (internal): Summarize features

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Used to be able to keep up with all the issues, now I'm finding it a bit of a struggle :sweat_smile:
> (internal): remove assignment in issue templates

- .github/workflows/docs.yml
- .github/workflows/test.yml
- Makefile
- doc/Makefile
- doc/org-roam.org
- doc/org-roam.texi
> (docs): use gh actions to deploy documentation

- .github/workflows/docs.yml
> (ci): makeinfo -> texinfo

- .github/workflows/docs.yml
- Makefile
> (ci): make multi-page manual

- .github/workflows/docs.yml
> (ci): run build commands directly

- org-roam-doctor.el
> Remove redundant "only"

- org-roam.el
Spotted this I was working on #631.
> (fix): replace `if` with `when`

- org-roam-completion.el
Bug Fix : https://github.com/org-roam/org-roam/issues/636
> Use hash-table-keys function to extract completion titles for ido

- .github/ISSUE_TEMPLATE/bug_report.md
Will help us identify bugs faster.
> (docs): Mention steps to provide backtrace in bug_report.md

- org-roam.el
> (fix): fix regression in find-ref

- .github/ISSUE_TEMPLATE/bug_report.md
Request interactive commands for more build/version info.
Request Org mode version.
> (doc): bug_report.md request more info

- org-roam.el
Don't lose user's point in org-roam.el
> (internal): org-roam-version save-excursion

- doc/Makefile
- doc/assets/page.css
> (docs): add a nice default theme

- org-roam-doctor.el
- org-roam.el
> (feat): org-roam-doctor: add ROAM_TAGS and ROAM_ALIAS checks

- org-roam.el
Organize org-roam.el:
- Move functions so they are defined before they are referenced
- Move defcustoms to appropriate section, sort alphabetically
- Move interactive commands to appropriate section, autoload, sort.
Should not change any behavior, but make review easier.
> (internal): org-roam.el formatting

- org-roam.el
Fail faster in case of nested capture.
Simplify logic for completions.
> (internal): refactor org-roam-find-file logic

- org-roam-doctor.el
Addresses https://github.com/org-roam/org-roam/issues/458#issuecomment-633658391
> (feat): doctor: add check for misspelled roam properties

- org-roam-doctor.el
> (fix): doctor: add ROAM_KEY to supported props

- doc/org-roam.org
- doc/org-roam.texi
Add documentation on the Zettelkasten method.
> (docs): Add section introducing the Zettelkasten method

- org-roam-buffer.el
> (fix): fix bug in org-roam-buffer-get-create

- org-roam-db.el
see https://github.com/org-roam/org-roam/pull/759#discussion_r435704588
> Fix update-tags to correct delete removed tags

- org-roam.el
Always fallback to the elisp implementation, when the shell commands
return garbage (possibly from shell configurations).
> (fix): fix org-roam--list-files elisp fallback

- doc/org-roam.org
- doc/org-roam.texi
- org-roam-capture.el
- org-roam-doctor.el
- org-roam.el
> (feat): prefer lowercase versions of org in-file settings

- CHANGELOG.md
- doc/org-roam.org
- doc/org-roam.texi
- org-roam-dailies.el
- org-roam-doctor.el
- org-roam.el
- tests/roam-files/alias.org
- tests/roam-files/bar.org
- tests/roam-files/base.org
- tests/roam-files/foo.org
- tests/roam-files/nested/bar.org
- tests/roam-files/nested/deeply/deeply_nested_file.org
- tests/roam-files/nested/foo.org
- tests/roam-files/tags/no_tag.org
- tests/roam-files/tags/tag.org
- tests/roam-files/titles/aliases.org
- tests/roam-files/titles/combination.org
- tests/roam-files/titles/title.org
- tests/roam-files/unlinked.org
- tests/roam-files/web_ref.org
> (internal): lowercase all properties

- doc/org-roam.org
- doc/org-roam.texi
Update qutebrowser configuration instructions: see #753
> (docs): update roam-ref qutebrowser configuration

- CHANGELOG.md
Just added some of the changes since 1.1.1 to the changelog.
There are a million small internal changes which I've omitted. There are also many many doc pull requests that I did not include
obviously feel free to edit/ask me to edit if I missed anything or wording is poor
> Add in a bunch of entries to the changelog

- org-roam-db.el
> (docs): update docstring for org-roam-db-location

- CHANGELOG.md
- README.md
- org-roam-capture.el
- org-roam.el
> (feat): Implement ‘org-roam-insert-immediate’

- org-roam.el
Fixes #837.
@endgame: Could you test the PR on your machine and tell us if it works?
> (fix): Check sqlite3’s executability before existence

- tests/roam-files/headlines/headline.org
- tests/test-org-roam.el
> (tests): add test for headline extraction

- org-roam.el
Adds `org-roam-find-file-immediate`. Ref #852.
> (feat): add org-roam-find-file-immediate

- doc/org-roam.org
- doc/org-roam.texi
> (docs): fix qutebrowser roam-protocol binding

- BACKERS.md
> (docs): Add forkrul to BACKERS

- org-roam-graph.el
- org-roam-macs.el
> (fix): fix escaping of backslashes in graph generation

- doc/org-roam.org
- doc/org-roam.texi
Make the incompatibility with regular org-capture explicit.
> (docs): Update org-roam-capture documentation

- org-roam-graph.el
Introduced by #908, Fixes #912.
> (fix): fix org-roam graph building with new db schema

- org-roam-db.el
> (fix): fix possible nil dbs on update operations

- doc/org-roam.org
- doc/org-roam.texi
> (docs): make explicit need to set org-roam-directory early

- CHANGELOG.md
- org-roam-capture.el
> (feat): cache entered template variables

- README.md
* README.md: Create FAQ section and mention `C-M-j` for ivy
Prompted by #958.
> (doc): Add a FAQ section

- README.md
* README.md: Add ‘Getting Help’
Prompted by #920.
@myshevchuk Anything you'd like to add?
> (doc): Create ‘Getting Help’

- doc/org-roam.org
- doc/org-roam.texi
> (doc): add debian/ubuntu installation instructions

- org-roam-capture.el
- org-roam-dailies.el
- org-roam-capture-ref-templates
- org-roam-dailies-capture-templates
#895
> customize settings for templates variables

- org-roam-faces.el
- org-roam.el
> (internal): move faces into own file

- org-roam.el
- Ensure `org-roam-store-link-file` has no effect if org-roam-mode is
disabled
- Remove custom styling for ID links when org-roam-mode is disabled
> (fix): fix face-related functionality

- README.md
- doc/org-roam.org
- doc/org-roam.texi
> (doc): Add target audience section

- org-roam.el
* org-roam.el (org-roam-link-use-custom-faces): New toggle
(org-roam--file-link-face): Refactor for new toggle
Fixes #996.
> (feat): Add toggle for custom-faces for Org-roam links

- org-roam.el
> (feat): Implement new face-toggle for id-links

- org-roam-dailies.el
- org-roam-macs.el
- org-roam-protocol.el
- org-roam.el
This has caused more confusion than it has helped.
> (internal): remove with-template-error wrapper

- org-roam-db.el
> (fix): Widen before updating file

- org-roam-db.el
Save buffer restriction for update. Ref #1014
> (fix): save-restriction for db update

- org-roam.el
- tests/test-org-roam.el
> (fix): fix fuzzy-links regex

- org-roam-capture.el
- org-roam-db.el
- org-roam.el
I'm sorry for the mess, I'm not very familiar with pull requesting. This is a continuation of #1002. I guess I made a mistake requesting from the `master` branch, now I can't understand how I can push there. So this request is from a separate branch. This is a general approach as you said, storing all links in the database.
> Implement link types

- doc/org-roam.org
- doc/org-roam.texi
> (docs): set org-roam-db-location with multiple org-roam-directories

- org-roam.el
> (fix) strip todo, priority, and tags from headline candidates

- org-roam.el
Case sensitivity for completions is already controlled via
`completion-ignore-case`, so we remove this variable that doesn't
actually do what is expected.
Instead, we add `org-roam-file-setup-hook`, which allows user customization on
the buffer setup for Org-roam files. To enable case-insensitivity, we can do:
``` emacs-lisp
(add-hook 'org-roam-file-setup-hook (lambda () (setq-local completion-ignore-case t)))
```
> (fix): remove org-roam-completion-case-sensitive

- org-roam.el
This should improve responsiveness on large files
> (internal): use regexp-search for fuzzy link replacement

- org-roam.el
This should result in some performance boost.
> (internal): replace org-element-parse-buffer calls with regexp search

- org-roam.el
Fuzzy links were initially were detected as anything within double brackets. 
This could include code in source blocks.
This PR introduces `(org-roam--fuzzy-link-p)`. This uses an additional
check using the `org-element` API, and ensures that the link type is
fuzzy (not a file: or https: link, for example).
Fixes #1069, and an array of unreported bugs:
1. Link extraction into the database should no longer pick up false
links (in code blocks, for example).
2. Link completion will only truly work within fuzzy links
> (fix): fix non-fuzzy links being treated as fuzzy links

- org-roam-buffer.el
Sort display of backlinks in backlinks buffer by occurrence. The default
link extraction behaviour causes it to be inserted roughly in the
reverse order.
Addresses https://github.com/org-roam/org-roam/pull/1085#issuecomment-687071635
> (feat): sort backlinks by occurrence

- CHANGELOG.md
- org-roam.el
> Add a vanilla org-mode tag source

- CHANGELOG.md
- doc/org-roam.org
- doc/org-roam.texi
- org-roam-completion.el
- org-roam-link.el
- org-roam-macs.el
- org-roam.el
- tests/test-org-roam.el
> Move fuzzy links to roam: links

- doc/org-roam.org
- doc/org-roam.texi
Fixing an open TODO in the manual.
> how to install from git repository

- org-roam-macs.el
- org-roam.el
> (fix): Wrap org-id-find-id-in-file to Fix issue #1129.

- org-roam.el
> (fix): add emacsql-sqlite3-executable null check

- org-roam.el
> (fix): fix emacsql-sqlite3 check

- doc/org-roam.org
- doc/org-roam.texi
> (docs): add docs for Org-roam unlinked references

- doc/org-roam.org
- doc/org-roam.texi
> (doc): add FAQ for completion into manual

- org-roam.el
content-end -> contents-end h.t. @Whil-
> (fix): correct usage of org-element api

- CHANGELOG.md
- org-roam.el
See my comment in https://github.com/org-roam/org-roam/issues/1149#issuecomment-706073127
See it in action:
> (feat): interactive functions for managing aliases and tags

- doc/org-roam.org
- doc/org-roam.texi
> (doc): fix org-roam-buffer-window-parameters documentation

- org-roam-db.el
- org-roam.el
Instead of maintaining a file queue to process for updating the Org-roam
database, we instead simply call `org-roam-db-build-cache` to rebuild
the db. `org-roam-db-build-cache` feels Fast Enough(TM), and basically
runs instantly if no files are modified. This greatly simplifies the
code, basically allowing to maintaining a single code path for db
operations.
This PR should also address the slowness wrt to ID links. Org-roam now
builds the headline information first, so there is no need to read the
file to check if the headline is there. The downside to this is that
this only works for IDs in Org-roam files.
> (internal): simplify db update operations

- doc/org-roam.org
- doc/org-roam.texi
> (doc): add note on unlinked references and encrypted files

- org-roam.el
Add quotes to allow filenames with spaces on it
> Add quotes to allow filenames with spaces on it

- doc/org-roam.org
- doc/org-roam.texi
Add keystroke, command, function and variable indexes.
> (doc): add indexes

- doc/org-roam.org
- doc/org-roam.texi
remove the first table of contents
> (doc): remove top-level TOC

- doc/assets/page.css
- doc/org-roam.org
- doc/org-roam.texi
- style tables properly
- reduce pre font-size
> (doc): doc stylistic changes

- doc/org-roam.org
- doc/org-roam.texi
Some minor changes to the documentation.
> (doc): minor changes

- CHANGELOG.md
- org-roam.el
> (fix): fix idle-timer not created on org-roam-mode

- org-roam.el
> (fix): Stop updating Cache on non-existing file

- org-roam-db.el
#1212 slowed down database updates considerably for me. I have 1493 files in my org roam directory. `(org-roam--list-all-files)` is too slow (2.4s) even on `rg` which slows down `org-roam-db-build-cache` considerably.
I understand the advantage of #1212 is that it allows for a single code path. Therefore, I extracted the core logic from `org-roam-db-build-cache` to allow applying database update on a list of files under a single code path.
I have tested it to be working on 'immediate method of database update but wouldn't be hard to back propagate stuff from previous commits that made `org-roam-db--update-file` work on a timer.
The following are benchmarks done on my largest file (184KB, 4820 lines).
`org-roam-db-build-cache` is the defacto database update mechanism. …
> (perf): Improve database update on 'immediate

- org-roam-compat.el
- org-roam-db.el
Just better naming for that function.
> (internal): org-roam-db--update-maybe -> org-roam-db--upgrade-maybe

- doc/org-roam.org
- doc/org-roam.texi
Clarification about the asycn db update seems helpful for beginners.
I tried my best to follow the writing style of the original. Please advise if this is appropriate.
Refer to this Slack thread
https://orgroam.slack.com/archives/CV160S8EL/p1608039505055000
> (doc): Add async update to Getting Started

- README.md
> (doc) Update README

- org-roam-capture.el
Fix broken org-roam-capture--get-point from #1375
> (fix): fix org-roam-capture--get-point

- README.md
I finally got to publishing my notes which (I think) is a good example to showcase: https://braindump.rasen.dev/
> (doc): add my braindump example (Alexey Shmalko)

- org-roam-capture.el
> (fix): org-roam-dailies: fix false warning on new file

- org-roam-buffer.el
> (fix): fix org-roam buffer insert out-of-order

- org-roam-protocol.el
Mostly to fix #1433 but also discuss the format of the file name (slug).
> (fix) Capture template initial text

- org-roam-db.el
> fix: #1455 replace let with let* [V2.]

- org-roam-mode.el
> org-roam-mode-sections: Convert to abnormal hook

- org-roam-mode.el
Related to #1504, commit 109917c
It needs to change dolist for `sections` to `section-functions`
> fix: persistent-redisplay (#1504)

- org-roam-utils.el
- org-roam.el
make process-display-format cache its value
> faster completion start (on ~8300 files) with caching

- org-roam.el
Should partially fix https://github.com/org-roam/org-roam/issues/1568
> (fix) org-roam-node--completions template

- org-roam-capture.el
This an alternative solution to #1579 to fix and close #1566. All it does is repositioning of the point, so each `org-capture-place-[type]` functions would do the the thing at the right position. From my internal semi-automated testing this works with all currently available `type`x`target` combinations in `org-roam-capture` and better than #1579, which still has some flows. For more details, please, read the commits message for this PR, the linked issue and the alternative PR.
> Adjust locations of where templates should be inserted for each target

- org-roam.el
[fd](https://github.com/sharkdp/fd) is a popular alternative to `find` and is an optional dependency of Doom Emacs to index files, so there's plenty of users that use it. In some ways it's superior to `find`, while in others worse (mostly when it comes to power options). It doesn't by the default index hidden and ignored files, and I didn't set the flags to include them either. Let me know if you think this should be changed.
> Add `fd` as another backend to list files

- org-roam.el
General maintenance. There's a lot of things that preserved from v1/early v2 and wasn't updated. This PR doesn't address all the accumulated litter in the codebase, but only specific to `org-roam.el`, and even then, not all of it. A more serious refactoring is needed in some places. I've also updated some other docstrings that looked more as placeholders or wouldn't look clear enough.
> Refactor some docstring and parameters in `org-roam.el`

- README.md
Hi,
I have been publishing my org roam notes in my blog. Would it be okay to include it here ?
https://sidhartharya.github.io/braindump/index.html
> (doc): add my braindump example (Sidharth Arya)

- org-roam-migrate.el
> (fix): allow migration for desc with backslash

- org-roam-compat.el
- org-roam-dailies.el
- org-roam.el
Just tidying up the codebase to ease maintenance and improve its understanding by the other users. See the commit messages for more details about the changes.
> Refactor backward compatibility related code

- org-roam-migrate.el
> (fix): migration: ensure empty roam_alias is removed

- org-roam-migrate.el
> migration: proper fix for file-link replacement

- org-roam-migrate.el
Following @jcguu95's suggestion on #1602.
Solves #1613.
> Include `desc` back into `replace-match` statement

- org-roam-db.el
> (fix): fix org-ref cite links

- org-roam-dailies.el
ht @mbafford for finding the cause
> (fix)dailies: prevent non-compliant dailies from breaking calendar

- org-roam-migrate.el
> (migration)docs: Warn requirement of at least Org 9.4

- org-roam-migrate.el
I don't see how v1 can be incompatible with v1, surely it must be v2 ;-)
> Corrects typo about v1 being incompatible with v1

- README.md
> (docs): Add intro video to README

- org-roam-db.el
In scenarios where a headline node has no title, skip the node instead
of erroring out. Fixes #1692.
> (fix)db: skip nodes with no title

- org-roam-migrate.el
> (fix): fix url in v2 warning

- doc/org-roam.org
- doc/org-roam.texi
> (docs): roam_key -> ROAM_REFS

- org-roam-db.el
Include the current headline in outline extraction for links, so the
org-roam-buffer contains this information as well.
> (feat)db: include self in outline

- org-roam-node.el
Adds `org-roam-template-key-prefixes`, which prefixing node properties
with a provided string acting as a query of sorts.
> (feat)completions: generalize template prefixes

- doc/index.html
> (docs): link to org-roam-ui

- org-roam-utils.el
Output the commit hash when it's available (e.g. when using straight to
install packages). This comes in handy during debugging during error
reporting.
> (feat)org-roam-version: output commit hash when available

- extensions/org-roam-protocol.el
- org-roam-node.el
This is an alternative PR to #1776, that also implements FORCE parameter and sets it accordingly for each caller needs.
> (feat): don't move the point when revisiting already visited nodes

- CHANGELOG.md
- org-roam-mode.el
Use SQL join instead of iterating over each ref and running another sql query.
> (feat)buffer: optimize reflinks fetch

- CHANGELOG.md
> Adding changelog entry

- doc/org-roam.org
- doc/org-roam.texi
- org-roam-capture.el
> fix typo in docs

- org-roam-node.el
> fix(org-roam-node-read): add aliases

- org-roam-compat.el
- org-roam-node.el
- org-roam-utils.el
> (chore)utils: standardize org-roam-property-add/remove fn signatures

- org-roam-utils.el
Previously org-roam-set-keyword was unable to handle the syntax of the
:LOGBOOK: drawer. We introduce `org-roam-skip-drawers` to move point
over all drawers, allowing us to set the keyword in the right place.
> (fix)utils: org-roam-set-keyword skip over all drawers

- org-roam-db.el
> (fix)db: expand org-roam-directory name as directory

- org-roam-db.el
> (fix)db: refresh CATEGORY before writing to db

- org-roam-node.el
Emacs commit 3f096eb3405b2fce7c35366eb2dcf025dda55783 introduced `string-glyph-compose` and `string-glyph-decompose`, autoloading these instead of the (still existing) `ucs-normalize-NFC-region` and `ucs-normalize-NFD-region`.
There are three cases:
- Emacs where these transitions have not happened yet (e.g. 27.1):  `ucs-normalize-NFC-region` and `ucs-normalize-NFD-region` are still  autoloaded, aliasing the new names to them will keep them usable
and the code still works.
- Emacs where the new functions are defined (not yet released): the new names  are autoloaded, no aliases are installed and the code still works.
- A (hypothetical?) Emacs where `string-glyph-compose` and  `string-glyph-decompose` are renamed.  If `ucs-normalize-NFC-region` and `ucs-normalize-NFD-region` do not get …
> Fix org-roam-node-slug for compatibility with future Emacs release #1981

- org-roam-node.el
> (fix)node: fix wrong string-glyph-* aliases

- doc/org-roam.org
- doc/org-roam.texi
> docs: symlink resolution with find-file-visit-truename

- extensions/org-roam-dailies.el
> Fixed some wording

- doc/org-roam.org
- doc/org-roam.texi
> (docs)completions: document org-roam-node-display-template

- org-roam-capture.el
> (fix)capture: return id in setup-target-location

- CHANGELOG.md
- extensions/org-roam-dailies.el
> (fix)dailies: remove f require

- org-roam-log.el
- org-roam.el
-------
Create initial log module for working with Org logs.
Fixes #2167 .
> (feat)log: init

- doc/org-roam.org
- doc/org-roam.texi
- extensions/org-roam-dailies.el
- extensions/org-roam-export.el
- extensions/org-roam-graph.el
- extensions/org-roam-overlay.el
- extensions/org-roam-protocol.el
- org-roam-capture.el
- org-roam-compat.el
- org-roam-db.el
- org-roam-id.el
- org-roam-log.el
- org-roam-migrate.el
- org-roam-mode.el
- org-roam-node.el
- org-roam-utils.el
- org-roam.el
> (chore) fix version numbers

- org-roam.el
> (fix) org-roam-file-p handle opening a buffer with no path

- org-roam.el
> (chore): reapply #2178

- org-roam-utils.el
> (feat): org-roam-property-* code duplication removed (#2217)

- org-roam-db.el
`org-roam-db--file-hash` potentially returns different values depending on whether it is run with the file path passed to it. That is,
```elisp
(equal (org-roam-db--file-hash)
(org-roam-db--file-hash (buffer-file-name))
```
can be nil.
One example of an edge case that triggers this:
- If a file has LF line endings,
- and is situated in a repository where .editorconfig asks for CRLF,
(Such repositories exist, for example <https://github.com/obsidianmd/obsidian-docs/>)
- and editorconfig-mode is enabled,
org-roam-db--file-hash would then return different results depending on whether the file path is passed to it or not.
The result is that these files will always be updated regardless of whether they are modified or not.
While this is a contrived edge case, there may be other cases like this …
> (db)fix: file modification detection failing in some edge cases

- doc/org-roam.org
- doc/org-roam.texi
- org-roam-mode.el
Hello all,
After going through nearly all of the Org-roam source code files, I found these small typos, and have corrected  them. Thus, this pull request will fix them.
Although I am conscious that it is not much, it is what I can give in return :).
Thank you for your hard work.
Kind regards,
HR
> (Docs): Fixed typos in the docs

- doc/org-roam.org
- doc/org-roam.texi
Update docs to reflect sqlite-bulitin and sqlite-module. Closes #2295.
> (docs): update documentation on database-connectors

- org-roam.el
> (minor): fix lints on main

- org-roam-capture.el
- org-roam-db.el
- org-roam-log.el
- org-roam-migrate.el
- org-roam-mode.el
- org-roam.el
Depend on snapshot of emacsql as per https://github.com/magit/emacsql/issues/113
> depend on snapshot of emacsql

- org-roam-node.el
> (node) add optional NOCASE parameter to org-roam-node-from-title-or-alias

- README.md
One more example.  Just a suggestion, but it's fine if you don't want to.
> Link Martin Edström's knowledge base

- CHANGELOG.md
- org-roam-mode.el
- tests/test-org-roam-mode.el
- tests/test-org-roam.el
This series of commit is dedicated to test this recent change: https://github.com/org-roam/org-roam/commit/edccf9be8429f9e549caff9b2d64f2a80913cf03
> (test): add "org-roam--list-files-search-globs"

- tests/test-org-roam-capture.el
- tests/test-org-roam-id.el
- tests/test-org-roam.el
> (test): add org-roam-id-at-point

- tests/roam-files/promoteable.org
- tests/test-org-roam-node.el
- tests/test-org-roam.el
> (test): add org-roam--buffer-promoteable-p

- tests/test-org-roam-node.el
> (test): add org-roam-alias-{add|remove}

- tests/roam-files/demoteable.org
- tests/roam-files/with-alias.org
- tests/test-org-roam-node.el
- tests/test-org-roam.el
> (test): add org-roam-demote-entire-buffer

- tests/test-org-roam.el
> (test): add org-roam-file-p

- tests/test-org-roam.el
> (test): add org-roam-buffer-p

- tests/test-org-roam-db.el
- tests/test-org-roam.el
> (test): add org-roam-db--file-hash

- tests/roam-files/with-times.org
- tests/test-org-roam-db.el
- tests/test-org-roam-node.el
- tests/test-org-roam.el
> (test): add org-roam-db-get-{scheduled|deadline}-time

- org-roam-db.el
-------
I think it makes sense that everyone needn't run into this error and look up the fix.
https://github.com/org-roam/org-roam/issues/2512
> Bump DB version to avoid error

- org-roam-db.el
This PR proposes a fix to missing database autosync when files are deleted through `vc-delete-file`.
Currently, `org-roam-db-autosync-mode` sets up a before-advice with `delete-file` to maintain cache consistency. When an Org is under version control, however, file deletion may be done through `vc-delete-file`, which might not use `delete-file` to perform deletion. In such a case, cache will be in an inconsistent state (which can be fix by manually running `org-roam-db-sync`). 
Therefore, this PR implements an around-advice with `vc-delete-file` to ensure cache consistency when the function is used but not `delete-file`.
> fix: run org-roam-db-clear-file on file deletion via vc-delete-file
